### ISSUE TITLE
DmsfContextMenusController:Class (NoMethodError)

### ISSUE THREAD

**Issue by psi-4ward** [danmunn/redmine_dmsf#1009]
```
/home/redmine/redmine/plugins/redmine_checklists/lib/redmine_checklists/patches/compatibility/application_controller_patch.rb:32:in `before_action': undefined method `before_filter' for DmsfContextMenusController:Class (NoMethodError)
        from /home/redmine/redmine/plugins/redmine_dmsf/app/controllers/dmsf_context_menus_controller.rb:25:in `<class:DmsfContextMenusController>'
        from /home/redmine/redmine/plugins/redmine_dmsf/app/controllers/dmsf_context_menus_controller.rb:21:in `<top (required)>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:356:in `require_or_load'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:334:in `depend_on'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:246:in `require_dependency'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `block in eager_load!'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `eager_load!'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/engine.rb:356:in `eager_load!'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
        from /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
        from config.ru:4:in `require'
        from config.ru:4:in `block in <main>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `eval'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `block in builder'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/unicorn-5.4.1/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:795:in `build_app!'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:139:in `start'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `load'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `<main>'
```

Redmine: 4.0.3 

Plugins:
* Clipboard image paste 1.13
* Agile 1.4.10
* Checklist 3.1.14

It works without dmsf so I assume the problem stays here?

**Comment by ahorek** [comment]
see https://github.com/imasdetres/redmine_checklists/blob/master/lib/redmine_checklists/patches/compatibility/application_controller_patch.rb#L31

before_filter has been removed in rails 5 and replaced by before_action

**Comment by psi-4ward** [comment]
so this problem has to be fixed in readmine_checklists?

But if I remove dms checklists work

**Comment by ahorek** [comment]
> so this problem has to be fixed in readmine_checklists?

yes

try to download a recent version, according to their changelog support for Redmine 4.0.3 was added in 3.1.15 and you're on 3.1.14. It looks like the patch in question was already removed.

**Comment by psi-4ward** [comment]
So it solved this bug, thanks!!

But I had to struggle with #992 after loading the devel branch I get:
```
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: dalli (>= 0) and dalli (~> 2.7.0). Bundler cannot continue.
#  from /home/redmine/redmine/Gemfile:102
#  -------------------------------------------
#  gem "unicorn", "~> 5.4", "!=5.5.0"
>  gem "dalli", "~> 2.7.0"
#  -------------------------------------------
```
Removing `gem dali` from Gemfile solves this. No it works as expected.
