### ISSUE TITLE
How to install DMSF plugin on docker

### ISSUE THREAD

**Issue by pianotako** [danmunn/redmine_dmsf#1011]
I want to install DMSF plugin on Redmine docker. I have read issue #901, so I pull container from https://hub.docker.com/_/redmine/ , and add following command to build my container.
`RUN apt-get update && apt-get install -y make gcc`
It is OK to build it. But when I try to run my container, it keeps on Install missing gems again and again. I don't know how to fix it. Is there any suggestion? 

here is my script and dockerfile to build container
```bash
### build.sh
rm -rf build
mkdir build
cp Dockerfile.yml build
cp -r redmine_dmsf build
cd build/redmine_dmsf
git checkout v2.0.0 -f && git clean -df
cd ..
docker build -t piko/redmine_dmsf -f Dockerfile.yml .
cd ..
```
 ```dockerfile
### Dockerfile.yml
FROM redmine:4.0
RUN apt-get update && apt-get install -y make gcc
ADD --chown=redmine:redmine ./redmine_dmsf ./plugins/redmine_dmsf
```
here is my script to run container
```bash
### deploy.sh
docker-compose down
sudo rm -rf data/redmine data/mysql
mkdir data/mysql \
      data/redmine \
      data/redmine/files \
      data/redmine/themes \
      data/redmine/plugins
docker-compose up -d
```
```yaml
### docker-compose.yml
version: '3.1'
services:
  redmine:
    image: piko/redmine_dmsf
    container_name: myredmine
    restart: always
    volumes:
      - ./data/redmine/files:/usr/src/redmine/files
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: red_db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: pass2357
      REDMINE_DB_DATABASE: redmine
    depends_on:
      - red_db
  red_db:
    image: mysql:5.7
    container_name: mysql57
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass2357
      MYSQL_USER: redmine
      MYSQL_PASSWORD: pass2357
      MYSQL_DATABASE: redmine

```
And it kept on showing these information again and again

```
=> Booting WEBrick
=> Rails 5.2.2.1 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
W, [2019-05-30T03:27:56.774526 #1]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
/usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require': No such file to load -- mime/types.rb (LoadError)
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/src/redmine/plugins/redmine_dmsf/lib/dav4rack/resources/mongo_resource.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:356:in `require_or_load'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:334:in `depend_on'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:246:in `require_dependency'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `each'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `block in eager_load!'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `each'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `eager_load!'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/engine.rb:356:in `eager_load!'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `each'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
	from /usr/src/redmine/config/environment.rb:14:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:27:in `app'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/server.rb:283:in `start'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:53:in `start'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/command/base.rb:65:in `perform'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/command.rb:46:in `invoke'
	from /usr/local/bundle/gems/railties-5.2.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
W, [2019-05-30T03:27:57.493983 #1]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
W, [2019-05-30T03:27:57.531996 #1]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2019-05-30T03:28:00.619961 #1]  WARN -- : No Xapian search engine interface for Ruby installed => Full-text search won't be available.
                      Install a ruby-xapian package or an alternative Xapian binding (https://xapian.org).
W, [2019-05-30T03:28:00.620099 #1]  WARN -- : cannot load such file -- xapian
Exiting
```

**Comment by pianotako** [comment]
Hi all, 
I have solve it, it is the dependency problem.
If you want to install on [redmine docker](https://hub.docker.com/_/redmine), here is the solution:

first, you have to do some modification base on redmine_dmsf v2.0.0
```bash
mkdir build && cd build
git clone https://github.com/danmunn/redmine_dmsf.git
git checkout v2.0.0
```
then apply this patch in Gemfile
```diff
@@ -35,7 +35,9 @@ end
 # Dav4Rack
 gem 'ox'
+gem 'mime-types'
+gem 'mongo'
 group :test do
   gem 'rails-controller-testing'
````
second, you have to build your own docker image
```dockerfile
### Dockerfile.yml
FROM redmine:4.0.1
    # ref https://github.com/danmunn/redmine_dmsf/issues/901
RUN apt-get update && apt-get install -y make gcc && \
    # ref https://github.com/danmunn/redmine_dmsf/issues/984
    sed -i -e 's/config.eager_load = true/config.eager_load = false/g' config/environments/production.rb
    # add modified redmine_dmsf
ADD --chown=redmine:redmine ./redmine_dmsf ./plugins/redmine_dmsf
```
finally, run your docker image.
