### ISSUE TITLE
unable to install plugin on redmine 4.0.3

### ISSUE THREAD

**Issue by elekgeek** [danmunn/redmine_dmsf#1012]
Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.2.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.21-master
  redmine_checklists             3.1.14
  redmine_issue_dynamic_edit     0.6.7
  redmine_lightbox2              0.5.0
  sidebar_hide                   0.0.8

I get this error:

```
App 17619 output: Error: The application encountered the following error: No such file to load -- mime/types.rb (LoadError)
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
App 17619 output:     /var/www/html/redmine/plugins/redmine_dmsf/lib/dav4rack/resources/mongo_resource.rb:4:in `<top (required)>'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:356:in `require_or_load'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:334:in `depend_on'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:246:in `require_dependency'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `each'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `block in eager_load!'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `each'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `eager_load!'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/engine.rb:356:in `eager_load!'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `each'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
App 17619 output:     /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
App 17619 output:     /var/www/html/redmine/config/environment.rb:14:in `<top (required)>'
App 17619 output:     config.ru:3:in `require'
App 17619 output:     config.ru:3:in `block in <main>'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
App 17619 output:     config.ru:1:in `new'
App 17619 output:     config.ru:1:in `<main>'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 17619 output:     /home/redmine/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2019-06-09 16:35:44.7654 17585/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/html/redmine: The application encountered the following error: No such file to load -- mime/types.rb (LoadError)
  Error ID: 4c18646e
  Error details saved to: /tmp/passenger-error-uznEsY.html

```

**Comment by picman** [comment]
Duplicates #992.
