### ISSUE TITLE
Internal Erro 500 when  enable "Act as attachable" and access Activity page

### ISSUE THREAD

**Issue by nop0x0000** [danmunn/redmine_dmsf#1019]
Thank you for your great plugin.

I use devel-2.0.1 branch
I have 500 error when access Activity page.

Steps to Reproduce
1. Login as admin
2. Enable "Act as attachable" in DMSF config page
3. Enable DMSF in the project setting page
4. Login as project member
5. Add a document to the project
6. Access Activity page in the project
7. Showed "Internal Error" 500

```
Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.6.2-p47 (2019-03-13) [x86_64-linux]
  Rails version                  5.2.2.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.5
  Mercurial                      4.0
  Bazaar                         2.8.0
  Git                            2.11.0
  Filesystem                     
  GitMirror                      2.11.0
Redmine plugins:
  redmine_absolute_dates         0.0.4
  redmine_code_review            1.0.0
  redmine_dmsf                   2.0.0
  redmine_git_mirror             0.8.0
  redmine_issue_templates        0.3.3
  redmine_japanese_help          0.0.1
  redmine_wysiwyg_editor         0.3.5
```

Let me apologize for my poor English.

**Comment by picman** [comment]
What is in `log/production.log`?

**Comment by nop0x0000** [comment]
I use Redmine with Docker
I could not find `log/production.log` in my docker container.
But there is error message in docker container log. 
Perhaps this is the same as what is printed to `log/production.log`

```
INFO -- : Started GET "/projects/hello-world/activity" for 172.19.0.2 at 2019-07-04 07:22:09 +0000
INFO -- : Processing by ActivitiesController#index as HTML
INFO -- :   Parameters: {"id"=>"hello-world"}
INFO -- :   Current user: test_user (id=44)
INFO -- :   Rendering activities/index.html.erb within layouts/base
INFO -- :   Rendered activities/_activities.html.erb (10.5ms)
INFO -- :   Rendered activities/index.html.erb within layouts/base (10.7ms)
INFO -- : Completed 500 Internal Server Error in 151ms (ActiveRecord: 84.1ms)
FATAL -- :
FATAL -- : ActionView::Template::Error (no implicit conversion of nil into String):
FATAL -- :      9:   <%= content_tag('span', e.project, :class => 'project') if @project.nil? || @project != e.project %>
    10:   <%= link_to format_activity_title(e.event_title), e.event_url %>
    11:   </dt>
    12:   <dd class="<%= "grouped" if in_group %>"><span class="description"><%= format_activity_description(e.event_description) %></span>
    13:   <span class="author"><%= link_to_user(e.event_author) if e.respond_to?(:event_author) %></span></dd>
    14: <% end -%>
    15: </dl>
FATAL -- :
FATAL -- : plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:61:in `+'
plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:61:in `block in <class:DmsfFileRevision>'
lib/plugins/acts_as_event/lib/acts_as_event.rb:62:in `event_description'
app/views/activities/_activities.html.erb:12:in `block (2 levels) in _app_views_activities__activities_html_erb__1978719001779625681_47081980371720'
app/views/activities/_activities.html.erb:5:in `each'
app/views/activities/_activities.html.erb:5:in `block in _app_views_activities__activities_html_erb__1978719001779625681_47081980371720'
app/views/activities/_activities.html.erb:2:in `reverse_each'
app/views/activities/_activities.html.erb:2:in `_app_views_activities__activities_html_erb__1978719001779625681_47081980371720'
app/views/activities/index.html.erb:5:in `_app_views_activities_index_html_erb___1758110204481647564_47081980075180'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
```

**Comment by nop0x0000** [comment]
Fix steps to reproduce

1. Login as admin
2. Enable "Act as attachable" in DMSF config page
3. Enable DMSF in the project setting page
4. Login as project member
5. **Add a new issure**
6. Add a document **to the issue**
7. Access Activity page in the project
8. Showed "Internal Error" 500

**Comment by picman** [comment]
Fixed. Thank you for reporting the issue.

**Comment by nop0x0000** [comment]
Thank you for your quickly response ;)
