### ISSUE TITLE
Plus (+) in a filename problem

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#1022]
```
Started PATCH "/issues/4660" for IP at 2019-07-16 08:58:45 +0200
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>" ^ ^ ", "authenticity_token"=>"cWQgLp/Z3Au7o59cIE4uOlMvNZV6OjgQ1HF6VdnR9JGEDNZjc4xszomBk3Jp4wj1weAGiKZPCJWN8HX0kCtaRQ==", "form_update_triggered_by"=>"", "issue"=>{"status_id"=>"1"$
  Current user: hidden (id=43)
An attachment not found by its token:
Completed 500 Internal Server Error in 250ms (ActiveRecord: 45.1ms)

NoMethodError (undefined method `disk_filename' for nil:NilClass):
  plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:59:in `block in controller_issues_after_save'
  plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:57:in `each_value'
  plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:57:in `controller_issues_after_save'
  plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:44:in `controller_issues_edit_after_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:528:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:515:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:184:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by acosonic** [comment]
This seems to be different problem...
