### ISSUE TITLE
NoMethodError undefined method `dmsf_folders'

### ISSUE THREAD

**Issue by RockyUs** [danmunn/redmine_dmsf#1027]
I have installed dmsf 1.6.2 on my redmine 3.4.11. I can enter the configuration screen. But I get the following error when I click dms tab in the project. 

Redmine: 3.4.11
Windows 2012 Server
SQL Server 2016
Ruby 2.3 x64

Any idea how to fix it? thanks. 

I, [2019-07-30T14:18:29.074503 #7008]  INFO -- : Completed 500 Internal Server Error in 47ms (ActiveRecord: 0.0ms)
F, [2019-07-30T14:18:29.074503 #7008] FATAL -- : 
NoMethodError (undefined method `dmsf_folders' for #<Project:0x00000005616908>
Did you mean?  dmsf_description):
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:664:in `get_display_params'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:56:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

**Comment by RockyUs** [comment]
I had the wrong version redmine_extension deployed. I update it to the latest version, and it works now.
