### ISSUE TITLE
Internal Server Error occured when moving a folder

### ISSUE THREAD

**Issue by n0nel** [danmunn/redmine_dmsf#1047]
When trying to move a folder to another, "Internal Server Error" occurred, and Redmine stopped working properly.

The environment is as follows:
Redmine 4.0.4
DMSF 2.0.0
Ruby 2.5.5

Below is the production.log when that operation was performed.

```
Started GET "/sub_uri/projects/some_project/dmsf/edit?folder_id=nnnn"
Processing by DmsfController#edit as HTML
  Parameters: {"folder_id"=>"nnnn", "id"=>"some_project"}
Completed 200 OK in 56ms (Views: 34.3ms | ActiveRecord: 12.6ms)
Started GET "/sub_uri/dmsf/folders/nnnn/copy"
Processing by DmsfFoldersCopyController#new as HTML
  Parameters: {"id"=>"nnnn"}
Completed 200 OK in 582ms (Views: 321.3ms | ActiveRecord: 58.2ms)
Started POST "/sub_uri/dmsf/folders/nnnn/copy/move"
Processing by DmsfFoldersCopyController#move as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"***", "target_project_id"=>"ID_some_project", "target_folder_id"=>"mmmm", "id"=>"nnnn"}
Redirected to http://server/sub_uri/projects/some_project/dmsf?folder_id=nnnn
Completed 302 Found in 39ms (ActiveRecord: 9.5ms)
Started GET "/sub_uri/projects/some_project/dmsf?folder_id=nnnn"
Processing by DmsfController#show as HTML
  Parameters: {"folder_id"=>"nnnn", "id"=>"some_project"}
Completed 500 Internal Server Error in 3165ms (ActiveRecord: 93.7ms)
  
SystemStackError (stack level too deep):
  
plugins/redmine_dmsf/app/models/dmsf_folder.rb:112:in `permissions?'
plugins/redmine_dmsf/app/models/dmsf_folder.rb:112:in `permissions?'
... (total 8106 lines)
plugins/redmine_dmsf/app/models/dmsf_folder.rb:112:in `permissions?'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:40:in `permissions'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
```

**Comment by picman** [comment]
It has been already fixed. It's caused by moving a folder into it's sub-folder. Upgrade to v2.4.1.

**Comment by n0nel** [comment]
Thank you for your information.
I will upgrade the version and check the operation.
