### ISSUE TITLE
Conflict with another plugin

### ISSUE THREAD

**Issue by mrPsycho** [danmunn/redmine_dmsf#1061]
Hello, 

looks like there is a conflict with other plugin: 
```
=== puma startup: 2019-12-07 17:16:19 +0300 ===
/home/redmine/redmine/plugins/redmine_checklists/lib/redmine_checklists/patches/compatibility/application_controller_patch.rb:32:in `before_action': undefined method `before_filter' for DmsfContextMenusController:Class (NoMethodError)
Did you mean?  before_action
        from /home/redmine/redmine/plugins/redmine_dmsf/app/controllers/dmsf_context_menus_controller.rb:25:in `<class:DmsfContextMenusController>'
        from /home/redmine/redmine/plugins/redmine_dmsf/app/controllers/dmsf_context_menus_controller.rb:21:in `<top (required)>'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:378:in `block in require_or_load'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:356:in `require_or_load'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:334:in `depend_on'
        from /home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:246:in `require_dependency'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `each'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `block in eager_load!'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `each'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `eager_load!'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:356:in `eager_load!'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `each'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
        from /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
        from config.ru:3:in `require'
        from config.ru:3:in `block in <main>'
        from /home/redmine/.bundler/ruby/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
        from /home/redmine/.bundler/ruby/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /home/redmine/.bundler/ruby/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
        from /home/redmine/.bundler/ruby/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
        from /home/redmine/.bundler/ruby/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
        from /home/redmine/.bundler/ruby/2.5.0/gems/puma-4.3.1/lib/puma/configuration.rb:321:in `load_rackup'
        from /home/redmine/.bundler/ruby/2.5.0/gems/puma-4.3.1/lib/puma/configuration.rb:246:in `app'
        from /home/redmine/.bundler/ruby/2.5.0/gems/puma-4.3.1/lib/puma/runner.rb:155:in `load_and_bind'
        from /home/redmine/.bundler/ruby/2.5.0/gems/puma-4.3.1/lib/puma/single.rb:98:in `run'
        from /home/redmine/.bundler/ruby/2.5.0/gems/puma-4.3.1/lib/puma/launcher.rb:172:in `run'
        from /home/redmine/.bundler/ruby/2.5.0/gems/puma-4.3.1/lib/puma/cli.rb:80:in `run'
        from /home/redmine/.bundler/ruby/2.5.0/gems/puma-4.3.1/bin/puma:10:in `<top (required)>'
        from /home/redmine/.bundler/ruby/2.5.0/bin/puma:23:in `load'
        from /home/redmine/.bundler/ruby/2.5.0/bin/puma:23:in `<main>'
```

i added same issue to author: https://www.redmineup.com/

**Comment by picman** [comment]
```before_filter``` is deprecated since Rails 4.
