### ISSUE TITLE
Error install plugin on Redmine 4.1.0

### ISSUE THREAD

**Issue by koren85** [danmunn/redmine_dmsf#1070]
Hi! Unable install plugin on Redmine 4.1.0:
```
NoMethodError: undefined method `assets' for #<Rails::Engine::Configuration:0x000000000555f280>
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:20:in `<class:Engine>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:9:in `<module:RedmineExtensions>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:8:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `require_relative'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `<top (required)>'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:74:in `require'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:69:in `each'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:69:in `block in require'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:58:in `each'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:58:in `require'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler.rb:174:in `require'
/home/redmine/redmine/config/application.rb:18:in `<top (required)>'
/home/redmine/redmine/Rakefile:5:in `require'
/home/redmine/redmine/Rakefile:5:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```
My Redmine:
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.4.9-p362 (2019-10-02) [x86_64-linux-gnu]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.24.1
  Filesystem                     
Redmine plugins:
  no plugin installed

**Comment by picman** [comment]
Duplicates #1065.
