### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by tknrng** [danmunn/redmine_dmsf#1093]
Error while installing plugin in docker
Using Redmine 4.1 + mysql + some plugins

redmine    | Using rich 1.4.8 from https://github.com/a-ono/rich.git (at 1.5.2@f5b5b07)
redmine    | Using redmine_crm 0.0.52
redmine    | Using redmine_extensions 0.3.10
redmine    | Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
redmine    | 
redmine    |     current directory: /usr/local/bundle/gems/ox-2.13.2/ext/ox
redmine    | /usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r
redmine    | ./siteconf20200218-20-1eaosrq.rb extconf.rb
redmine    | >>>>> Creating Makefile for ruby version 2.6.5 on x86_64-linux-musl <<<<<
redmine    | creating Makefile
redmine    | extconf.rb:71:in ``': No such file or directory - make (Errno::ENOENT)
redmine    | 	from extconf.rb:71:in `<main>'
redmine    | 
redmine    | extconf failed, exit code 1
redmine    | 
redmine    | Gem files will remain installed in /usr/local/bundle/gems/ox-2.13.2 for
redmine    | inspection.
redmine    | Results logged to
redmine    | /usr/local/bundle/extensions/x86_64-linux/2.6.0/ox-2.13.2/gem_make.out
redmine    | 
redmine    | An error occurred while installing ox (2.13.2), and Bundler cannot continue.
redmine    | Make sure that `gem install ox -v '2.13.2'` succeeds before bundling.
redmine    | 
redmine    | In Gemfile:
redmine    |   ox
redmine    | Your Gemfile lists the gem redmine_crm (>= 0) more than once.
redmine    | You should probably keep only one of them.
redmine    | Remove any duplicate entries and specify the gem only once (per group).

Plz advice

**Comment by tknrng** [comment]
Ok.
I resolve this issue.
**Resolution**
When u using redmine in docker need to create dockerfile with next lines (in my case):
```
FROM redmine:alpine

RUN apk update && apk upgrade && apk add gcc make sed libc-dev xapian xpdf antiword
RUN sed -i -e 's/config.eager_load = true/config.eager_load = false/g' config/environments/production.rb
```
Then add in docker compose file next lines (in my case):
```
redmine:
    build: ./build/redmine
    container_name: redmine
```
Then rebuild (docker-compose up -d --build)
