### ISSUE TITLE
redmine won't work with redmine_dmsf installed

### ISSUE THREAD

**Issue by elperepat** [danmunn/redmine_dmsf#1104]
Remine 4.1.1
Ubuntu 18.04
Apache 2.4.29
libapache2-mod-passenger 5.0.30

No other redmine plugin installed

I managed to install redmine_dmsf on my working redmine 4.1.1 installation. I get to the point where I restart the apache server and need to login. I get the following error:
What am I doing wrong?

```
EasyPatchManager->register_patch: The 'patching_module' (RedmineDmsf::Patches::IssuePatch) already exists! (ArgumentError)
  /var/lib/gems/2.5.0/gems/redmine_extensions-0.3.11/lib/redmine_extensions/patch_manager.rb:74:in `register_patch'
  /var/lib/gems/2.5.0/gems/redmine_extensions-0.3.11/lib/redmine_extensions/patch_manager.rb:120:in `register_model_patch'
  /var/www/redmine-4.1.1/plugins/redmine_dmsf/lib/redmine_dmsf/patches/issue_patch.rb:180:in `<top (required)>'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `load_interlock'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:356:in `require_or_load'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:334:in `depend_on'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:246:in `require_dependency'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `each'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `block in eager_load!'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `each'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `eager_load!'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:356:in `eager_load!'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `each'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
  /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
  /var/www/redmine-4.1.1/config/environment.rb:16:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:125:in `instance_eval'
  /var/lib/gems/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by ahorek** [comment]
it seems that you have this patch in more than one folder
https://github.com/danmunn/redmine_dmsf/blob/master/lib/redmine_dmsf/patches/issue_patch.rb

did you upgrade the dms from an older version or is it a clean installation?

**Comment by elperepat** [comment]
Seems like I created the problem:
To ease the update process of redmine itself, I symlink the plugins folder and redmine_dmsf doesn't seem to like to be somewhere else than directly in the plugins folder. All others plugins accepted this. Anyway, I'll be to moving my plugins folder around when upgrading instead of symlinking it.

You can close the issue.
