### ISSUE TITLE
Error redmine 4.1.1 after devel-2.4.3 dmsf upgrade

### ISSUE THREAD

**Issue by yurmala** [danmunn/redmine_dmsf#1110]
```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.8-p224 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine plugins:
...
  redmine_dmsf                   2.4.3
...
```
Errors from production.log:
```
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"portal_test"}
  Current user: yurmala (id=5)
  Rendering plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_main.html.erb (4.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (1.2ms)
  Rendered queries/_filters.html.erb (6.1ms)
  Rendered queries/_columns.html.erb (3.7ms)
  Rendered queries/_query_form.html.erb (42.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb (137.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb (147.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (219.2ms)
Completed 500 Internal Server Error in 404ms (ActiveRecord: 28.6ms)

ActionView::Template::Error (super: no superclass method `column_value' for #<#<Class:0x0000556abb5f7988>:0x0000556abb5fd8d8>
Did you mean?  column_value_with_tags):
    33:       <%= check_box_tag('ids[]', "#{node.type}-#{node.id}", false, id: nil) unless system %>
    34:     </td>
    35:     <% query.inline_columns.each do |column| %>
    36:       <%= content_tag 'td', column_content(column, node), class: column.css_classes %>
    37:     <% end %>
    38:     <td class="buttons">
    39:       <% unless system %>

plugins/redmine_dmsf/lib/redmine_dmsf/patches/queries_helper_patch.rb:142:in `column_value'
plugins/redmine_people/lib/redmine_people/patches/queries_helper_patch.rb:69:in `column_value_with_people'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/queries_helper_patch.rb:142:in `column_value'
app/helpers/queries_helper.rb:218:in `column_content'
plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:36:in `block (2 levels) in _6678e9654eb2316e47b945d81140421b'
plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:35:in `each'
plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:35:in `block in _6678e9654eb2316e47b945d81140421b'
plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:28:in `_6678e9654eb2316e47b945d81140421b'
plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb:49:in `block in _da2e1498e6d684890971494ded5abdc4'
plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb:26:in `_da2e1498e6d684890971494ded5abdc4'
plugins/redmine_dmsf/app/views/dmsf/show.html.erb:65:in `_61663517cc563ac264706e0ab9a803c8'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:74:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:70:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'

```

**Comment by yurmala** [comment]
I found IMPORTANT in CHANGELOG...

> 1. `alias_method_chain` has been replaced with `prepend`. Not directly but using `RedmineExtensions::PatchManager`.
>    Consequently, there might occure conficts with plugins which overwrite the same methods.

Ok. But i don't understand, what can i do in this case...

**Comment by yurmala** [comment]
I think it must be the same way like in other plugins (for example, Redmineup Tags plugin):
```
require_dependency 'queries_helper'
require_dependency 'issue_queries_query' if ActiveSupport::Dependencies::search_for_file('issue_queries_helper')

module RedmineupTags
  module Patches
    module QueriesHelperPatch
      def self.included(base)
        base.send(:include, InstanceMethods)

        base.class_eval do
          unloadable
          alias_method :column_value_without_tags, :column_value
          **alias_method :column_value, :column_value_with_tags**
        end
      end

      module InstanceMethods
        include TagsHelper

        **def column_value_with_tags(column, list_object, value)**
          if column.name == :tags_relations && list_object.is_a?(Issue)
            [value].flatten.collect{ |t| render_issue_tag_link(t) }.join(RedmineupTags.settings['issues_use_colors'].to_i > 0 ? ' ' : ', ').html_safe
          else
            column_value_without_tags(column, list_object, value)
          end
        end
      end
    end
  end
end

base = ActiveSupport::Dependencies::search_for_file('issue_queries_helper') ? IssueQueriesHelper : QueriesHelper
unless base.included_modules.include?(RedmineupTags::Patches::QueriesHelperPatch)
  base.send(:include, RedmineupTags::Patches::QueriesHelperPatch)
end

```

**Comment by picman** [comment]
Could you try the following modification of _lib/redmine_dmsf/patches/queries_helper_patch.rb_?

line 163

```ruby
# RedmineExtensions::PatchManager.register_helper_patch 'QueriesHelper',
#   'RedmineDmsf::Patches::QueriesHelperPatch', prepend: true

if Redmine::Plugin.installed?(:easy_extensions)
  RedmineExtensions::PatchManager.register_helper_patch 'QueriesHelper',
    'RedmineDmsf::Patches::QueriesHelperPatch', prepend: true
else
  DmsfController.send :helper, RedmineDmsf::Patches::QueriesHelperPatch
end
```

**Comment by yurmala** [comment]
it's worked now! thanks!
