### ISSUE TITLE
Migration 2.4.2 -> 2020-06-17 commits: Error 500 when attempting to modify a document

### ISSUE THREAD

**Issue by sunnyphone** [danmunn/redmine_dmsf#1139]
Hello

This issue is very close to #1134 but this time it happens when I attempt to modify a document. It is apparently not covered by the correction made for #1134.

The same error message appears to the user:
![image](https://user-images.githubusercontent.com/42149156/85282441-07f2df80-b48c-11ea-8706-e5d577dd0ef1.png)

The generated traces are close to #1134 but not identical:

```
`Started GET "/dmsf/files/2" for xxx.xxx.xxx.xxx at 2020-06-17 19:28:33 +0200
Processing by DmsfFilesController#show as HTML
  Parameters: {"id"=>"2"}
  Current user: pbreau (id=5)
  Rendering plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb within layouts/base
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_revisions.html.erb (0.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_file_new_revision.html.erb (14.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_revision_actions.html.erb (1.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (0.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb within layouts/base (60.5ms)
Completed 500 Internal Server Error in 72ms (ActiveRecord: 6.9ms)
  
ActionView::Template::Error (wrong number of arguments (given 2, expected 1)):
    156:       </div>
    157:       <div id="<%= "revision_access_#{revision.id}" %>">
    158:         <% if @file_manipulation_allowed %>
    159:           <% revision_access_query = DmsfFileRevisionAccessQuery.new %>
    160:           <% revision_access_query.revision_id = revision.id  %>
    161:           <% revision_access_count = revision_access_query.access_count  %>
    162:           <% revision_access_pages = Redmine::Pagination::Paginator.new revision_access_count,
  
plugins/redmine_dmsf/app/models/dmsf_file_revision_access_query.rb:38:in `initialize'
plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb:159:in `block in _2d69ff0ed242bb9267335613202da036'
plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb:69:in `each'
plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb:69:in `_2d69ff0ed242bb9267335613202da036'
plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:92:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:90:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
```
My config remains:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [amd64-freebsd12]
  Rails version                  5.2.4.2

Thank you very much for your help.

Best regards

**Comment by picman** [comment]
Fixed. Thank you for reporting that.
