### ISSUE TITLE
After having pulled new commits of 2020-06-22: New Error 500 when attempting to modify a document

### ISSUE THREAD

**Issue by sunnyphone** [danmunn/redmine_dmsf#1140]
Hello

This issue comes after case #1139. I confirm that the cause of the issue was fixed but I keep getting an error 500 apparently for a different reason:
![firefox_bPINXVCBrY](https://user-images.githubusercontent.com/42149156/85413300-eddbfe80-b56a-11ea-954a-5bea9a11d68a.png)

This time I get the following traces:
```
Started GET "/dmsf/files/11" for xxx.xxx.xxx.xxx at 2020-06-23 11:46:34 +0200
Processing by DmsfFilesController#show as HTML
  Parameters: {"id"=>"11"}
  Current user: pbreau (id=5)
  Rendering plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb within layouts/base
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_revisions.html.erb (1.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (4.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_file_new_revision.html.erb (25.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_revision_actions.html.erb (2.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (1.0ms)
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "`count` DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from accesses at /usr/local/www/redmine-4.1.1/plugins/redmine_dmsf/app/models/dmsf_file_revision_access_query.rb:85)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (32.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb within layouts/base (112.2ms)
Completed 500 Internal Server Error in 129ms (ActiveRecord: 8.7ms)
  
ActionView::Template::Error (PG::UndefinedColumn: ERREUR:  la colonne « count » n'existe pas
LINE 1: ..."dmsf_file_revision_accesses"."user_id" ORDER BY `count` DES...
                                                             ^
: SELECT user_id, COUNT(*) AS count, MIN(created_at) AS first_at, MAX(created_at) AS last_at FROM "dmsf_file_revision_accesses" INNER JOIN "users" ON "users"."id" = "dmsf_file_revision_accesses"."user_id" AND "users"."type" IN ('User', 'AnonymousUser') WHERE "dmsf_file_revision_accesses"."dmsf_file_revision_id" = $1 GROUP BY "dmsf_file_revision_accesses"."user_id" ORDER BY `count` DESC):
    34:     </tr>
    35:     </thead>
    36:     <tbody>
    37:     <% query.accesses.each do |access| %>
    38:       <tr>
    39:         <% query.inline_columns.each do |column| %>
    40:           <%= content_tag 'td', column_content(column, access), class: column.css_classes %>
  
plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb:37:in `_25e0a66d03171a05b3670fd84594af5f'
plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb:164:in `block in _8e6d52f31afcf60fcce56f5b775b301e'
plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb:69:in `each'
plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb:69:in `_8e6d52f31afcf60fcce56f5b775b301e'
plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:92:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:90:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
```
The database is PostgreSQL 11.8.
Translation for 'ERREUR:  la colonne « count » n'existe pas' is 'ERROR: the column "count" doesn't exist'.

Invoking the request `SELECT user_id, COUNT(*) AS count, MIN(created_at) AS first_at, MAX(created_at) AS last_at FROM "dmsf_file_revision_accesses" INNER JOIN "users" ON "users"."id" = "dmsf_file_revision_accesses"."user_id" AND "users"."type" IN ('User', 'AnonymousUser') WHERE "dmsf_file_revision_accesses"."dmsf_file_revision_id" = 11 GROUP BY "dmsf_file_revision_accesses"."user_id" ORDER BY `count` DESC` with psql makes no error.

Here is my config:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [amd64-freebsd12]
  Rails version                  5.2.4.2
  Database adapter               PostgreSQL 11.8

Thank you very much for your help

Best regards

**Comment by VVD** [comment]
Same here.

**Comment by VVD** [comment]
This hack fixed this issue:
```
--- app/models/dmsf_file_revision_access_query.rb.orig
+++ app/models/dmsf_file_revision_access_query.rb
@@ -82,7 +82,7 @@
     base_scope.
         access_grouped.
         joins(:user).
-        order('`count` DESC').
+        order('"count" DESC').
         limit(options[:limit]).
         offset(options[:offset])
   end
```
But probably it will break MySQL (and clones) support.

**Comment by sunnyphone** [comment]
Yes I am using now the hack as a temporary workaround but I understand that it will not be the solution.

**Comment by picman** [comment]
Fixed. Test it, please and provide me a feedback.

**Comment by VVD** [comment]
> Fixed. Test it, please and provide me a feedback.

Work for me fine! Thanks!

Waiting confirmation from @sunnyphone.

**Comment by VVD** [comment]
BTW, the difference between 2.4.2, 2.4.3 and master is so big - maybe increase version number to 2.5.0?

**Comment by sunnyphone** [comment]
It also works fine for me.
Thank you very much!
