### ISSUE TITLE
HTTP 500 on trying to access global redmine admin -> settings

### ISSUE THREAD

**Issue by sseide** [danmunn/redmine_dmsf#1143]
currently i cannot access the "MyAccount" page (all user) and the "Administration -> Settings" page (as admin) anymore.
As soon as i click on one of these to i get a white page saying "Internal Error..."

The log file contains the following error messages for these two pages. As there is the reference to the redmine_dmfs middleware file inside both i thought i ask here. I already found some closed issues with similiar error messages suggesting its some kind of incomatibility but im lost here as i am no ruby dev... 

```Started GET "/settings" for 2003:f1:170d:a300:380d:4315:6d42:e6c2 at 2020-06-27 00:07:36 +0200
Processing by SettingsController#index as HTML
  Current user: admin (id=1)
  Rendering settings/edit.html.erb within layouts/admin
  Rendered settings/_general.html.erb (6.8ms)
  Rendered settings/_display.html.erb (2.5ms)
  Rendered common/_tabs.html.erb (15.3ms)
  Rendered settings/edit.html.erb within layouts/admin (17.5ms)
Completed 500 Internal Server Error in 41ms (ActiveRecord: 11.6ms)
  
ActionView::Template::Error (wrong number of arguments (given 3, expected 2)):
    3: <div class="box tabular settings">
    4: <p><%= setting_select :ui_theme, Redmine::Themes.themes.collect {|t| [t.name, t.id]}, :blank => :label_default, :label => :label_theme %></p>
    5: 
    6: <p><%= setting_select :default_language, lang_options_for_select(false) %></p>
    7: 
    8: <p><%= setting_check_box :force_default_language_for_anonymous %></p>
    9: 
  
lib/redmine/i18n.rb:121:in `block in languages_options'
lib/redmine/i18n.rb:121:in `select'
lib/redmine/i18n.rb:121:in `languages_options'
lib/redmine/i18n.rb:126:in `block in languages_options'
lib/redmine/i18n.rb:125:in `languages_options'
app/helpers/application_helper.rb:1232:in `lang_options_for_select'
app/views/settings/_display.html.erb:6:in `block in _e1a149ab45154c35a042fdbf4155ecca'
app/views/settings/_display.html.erb:1:in `_e1a149ab45154c35a042fdbf4155ecca'
app/views/common/_tabs.html.erb:17:in `block in _3d7c52668cd1cae2690cbde2426f82d7'
app/views/common/_tabs.html.erb:16:in `each'
app/views/common/_tabs.html.erb:16:in `_3d7c52668cd1cae2690cbde2426f82d7'
app/helpers/application_helper.rb:386:in `render_tabs'
app/views/settings/edit.html.erb:5:in `_18a21e857f2b5341238b2054bca67987'
app/controllers/settings_controller.rb:31:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'

Started GET "/my/account" for 2003:f1:170d:a300:380d:4315:6d42:e6c2 at 2020-06-27 00:05:13 +0200
Processing by MyController#account as HTML
  Current user: admin (id=1)
  Rendering my/account.html.erb within layouts/base
  Rendered my/account.html.erb within layouts/base (4.3ms)
Completed 500 Internal Server Error in 14ms (ActiveRecord: 6.7ms)
  
ActionView::Template::Error (wrong number of arguments (given 3, expected 2)):
    22:   <p><%= f.text_field :lastname, :required => true %></p>
    23:   <p><%= f.text_field :mail, :required => true %></p>
    24:   <% unless @user.force_default_language? %>
    25:   <p><%= f.select :language, lang_options_for_select %></p>
    26:   <% end %>
    27:   <% if Setting.openid? %>
    28:   <p><%= f.text_field :identity_url  %></p>
  
lib/redmine/i18n.rb:121:in `block in languages_options'
lib/redmine/i18n.rb:121:in `select'
lib/redmine/i18n.rb:121:in `languages_options'
lib/redmine/i18n.rb:126:in `block in languages_options'
lib/redmine/i18n.rb:125:in `languages_options'
app/helpers/application_helper.rb:1232:in `lang_options_for_select'
app/views/my/account.html.erb:25:in `block in _6cc033b3720466b6349ff918fe7fd7d4'
app/helpers/application_helper.rb:1242:in `labelled_form_for'
app/views/my/account.html.erb:14:in `_6cc033b3720466b6349ff918fe7fd7d4'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
```
My simple test installation to check if your plugin is working with Redmine 4.0.7 does not show this behaviour, but there redmine_dmfs is the only plugin installed and maybe other versions of ruby gems are used...

Any thougths where to look for this error?

Debain 10 Linux
Redmine 4.0.7, Redmine DMSF 2.4.3
Ruby 2.5.5p157 with Rails 5.2.4.3

Thanks in advance,
Stefan Seide

**Comment by picman** [comment]
Does it work If you remove dmsf plugin? I see no relation to DMSF in the log.

**Comment by picman** [comment]
No feedback => closing

**Comment by sseide** [comment]
Sorry for no answer - was at a longer summer holiday and forgot about it afterwards.
Kinda "fixed" it by moving `/usr/share/redmine/tmp/cache/D3D/520/i18n%2Flanguages_options%2F4.0.7.stable` from working installation to the other one with the error above. Now its working without problems. Deleting this cache file it shows the error, moving it back again its working.

Therefore some problem of redmine itself and not redmine_dmsf not being able to create the cache file (while a lot of other cache files gets created during runtime, therefor no file system access rights problem).

Can stay closed.

Thanks a lot for help!
