### ISSUE TITLE
Install on dockerized redmine

### ISSUE THREAD

**Issue by mcondarelli** [danmunn/redmine_dmsf#1146]
Hi,
I'm trying to update my Redmine installation and failing badly with this plugin.

OLD installation is:
```
Environment:
  Redmine version                3.3.10.stable
  Ruby version                   2.3.8-p459 (2018-10-18) [x86_64-linux-gnu]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.24.0
  Filesystem                     
Redmine plugins:
  plantuml                       0.5.1
  redmine_dmsf                   1.5.9
```
While NEW installation is:
```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.4.9-p362 (2019-10-02) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.27.0
  Filesystem                     
Redmine plugins:
  plantuml                       0.5.1
```
Dockerized Redmine is from [here](https://github.com/sameersbn/docker-redmine) in both versions.

Plain `git clone https://github.com/danmunn/redmine_dmsf.git` fails because of different versions required for `dalli` by `Redmine` and `redmine_dmsf` (this looks pretty dumb because `redmine_dmsf` does *not* require a specific version.
This can be trivially cured by: `sed -i '/dalli/ s/$/,  "~> 2.7.0"/' redmine_dmsf/Gemfile`.

Next problem is not so easily overcome:
```
Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::incoming_email...
Configuring redmine::backups...
Configuring nginx...
Configuring nginx::redmine...
Installing plugins...
Installing gems required by plugins...
Your application has set without to "development:test". This will override the global value you are currently setting
Migrating plugins. Please be patient, this could take a while...
== 20170323131231 DmsfDescriptionLimit: migrating =============================
-- change_column(:projects, :dmsf_description, :text, {:null=>true, :limit=>65535})
   -> 0.0071s
-- change_column(:dmsf_folders, :description, :text, {:null=>true, :limit=>65535})
   -> 0.0040s
== 20170323131231 DmsfDescriptionLimit: migrated (0.0111s) ====================

== 20170330131901 CreateDmsfFolderPermissions: migrating ======================
-- create_table(:dmsf_folder_permissions, {:id=>:integer})
   -> 0.0004s
-- add_index(:dmsf_folder_permissions, :dmsf_folder_id)
   -> 0.0004s
== 20170330131901 CreateDmsfFolderPermissions: migrated (0.0009s) =============

== 20170421101901 DmsfFileContainerRollback: migrating ========================
-- add_column(:dmsf_folders, :system, :boolean, {:null=>false, :default=>false})
   -> 0.0004s
-- remove_index(:dmsf_files, {:column=>[:container_id, :container_type], :name=>"index_dmsf_files_on_container_id_and_container_type"})
   -> 0.0004s
-- remove_column(:dmsf_files, :container_type)
   -> 0.0028s
-- rename_column(:dmsf_files, :container_id, :project_id)
   -> 0.0029s
-- add_index(:dmsf_files, :project_id)
   -> 0.0004s
== 20170421101901 DmsfFileContainerRollback: migrated (0.0403s) ===============

== 20170422104901 MigrateDocuments: migrating =================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Permission denied @ dir_s_mkdir - /var/www/redmine
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:142:in `disk_file'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:28:in `block in up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `loop'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:69:in `find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/querying.rb:11:in `find_each'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:25:in `up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:817:in `exec_migration'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:797:in `block in migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:796:in `migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1212:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:510:in `up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:542:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:483:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:497:in `block in migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:496:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:496:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
Errno::EACCES: Permission denied @ dir_s_mkdir - /var/www/redmine
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:142:in `disk_file'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:28:in `block in up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `loop'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:69:in `find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/querying.rb:11:in `find_each'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:25:in `up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:817:in `exec_migration'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:797:in `block in migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:796:in `migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1212:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:510:in `up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:542:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:483:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:497:in `block in migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:496:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:496:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```
I assume this is due to the missing `chown -R www-data:www-data plugins/redmine_dmsf`.
I cannot do that because dockerized Redmine will forcefully reset ownership of `/home/redmine` to the `redmine` user (UID=1000; GID=1000).
I tried using a very permissive: `chmod -R ugo+w plugins/redmine_dmsf`, but this doesn't change anything.

Any idea?

**Comment by mcondarelli** [comment]
UPDATE!
Problem was with `redmine_dmsf` unable to create `/var/www/redmine` as user `redmine`.
Giving a very permissive:
```
chown -Rc www-data:www-data /var/www
chmod ugo+w /var/www
```
leads to a working `DMS`.

I would like to understand if I did something really wrong with `dalli` gem, if and how a "normal user" is supposed to create a directory in `/var/www` and, finally, what is the mess with `www-data` (which doesn't _seem_ used at all).

Any hint very welcome.
Thanks in Advance

**Comment by picman** [comment]
The plugin requires a folder on the disk where are stored uploaded files. During the migration the plugin moves files from the original folders eg. _dmsf/p_p1identifier_ to a new system _dmsf/2020/06_. The error is caused by missing permission for the destination folder. I wonder if your Redmine is located in _/home/redmine_, your files are in _/var/www/redmine_. All in all the user under which Redmine is run, obviously _redmine_ in your case, must have write permission to the folder where are stored files. The folder is set in the plugin settings.

**Comment by picman** [comment]
Concerning dalli, Redmine doesn't require dalli.

**Comment by mcondarelli** [comment]
Thanks.

`dalli` is actually used by `sameersbn/docker-redmine` which apparently uses:
```ruby
gem "dalli", "~> 2.7.0"
```
It seems Your plugin does not have specific version requirements; is there a way to tell ruby to chose the best fit (highest version?) instead of just die? (I am *not* a Ruby programmer).

In my old setup (Redmine 3.3.10) `dmsf` files were kept in `.../files/dmsf/<year>/<month>/...` I have no idea why they moved to `/var/www`.
I can move them back using `/settings/plugin/redmine_dmsf` but I'm unsure if this is the right fix for two reasons:
- New installation seems able to find the "old files", still in the "old place" (`.../files/dmsf/...`) without any changes.
- This change can be done *after* plugin is installed, but it won't install with standard settings (I have to make `/var/www` world writable).

I am clearly missing something; what should  check?

**Comment by picman** [comment]
If there is a conflict in in gems, I think that you must comment out one of them.
Files are being searched in the folder set in the plugin's settings. You can move them wherever you want.

**Comment by CSCSxx** [comment]
Hi, i am also using redmine on sameersbn docker. So i everytime get the same error by setting up a new version.
Maybe it would be safer for all to specify an actual version ?
