### ISSUE TITLE
WebDAV access with subdir-URL fails

### ISSUE THREAD

**Issue by s-tkt** [danmunn/redmine_dmsf#1160]
Accessing to subdir-URL like https://mydomain.com/new/redmine/dmsf/webdav fails with 'No route matches'.

```
---
Started OPTIONS "/new/redmine/dmsf/webdav" for 203.138.115.155 at 2020-08-04 07:07:34 +0900

ActionController::RoutingError (No route matches [OPTIONS] "/dmsf/webdav"):

actionpack (5.2.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.4.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
(snip)
---
```
Other operations to https://mydomain.com/new/redmine/... works very well, of course including dmsf with Web-UI.
I am using Redmine 4.1.1(bitnami), dmsf plugin 2.4.4, and WinSCP 5.17.7

**Comment by s-tkt** [comment]
Additional information.

Access to https://mydomain.com/new/redmine/new/redmine/dmsf/webdav succeeded.

```
Started PROPFIND "/new/redmine/new/redmine/dmsf/webdav" for 203.138.115.155 at 2020-08-04 10:10:57 +0900
Processing WebDAV request: /new/redmine/new/redmine/dmsf/webdav/ (for 203.138.115.155 at 2020-08-04 01:10:57 UTC) [PROPFIND]
```

I am setting at additional_environment.rb
```
config.relative_url_root = '/new/redmine'
```

and setting at environment.rb
```
Redmine::Utils::relative_url_root = "/new/redmine"
```

**Comment by picman** [comment]
And if you remove `config.relative_url_root = '/new/redmine'` from *additional_environment.rb*?

**Comment by s-tkt** [comment]
I found issue #1088.
This problem seems to duplicate #1088.

**Comment by s-tkt** [comment]
Additional information.
I found a small change in _lib/redmine_dmsf/webdav/custom_middleware.rb_:

```
 29       def initialize(app)
 30         @rails_app = app
 31         #path = File.join(Redmine::Utils::relative_url_root, %w(dmsf webdav)    )
 32         path = "/dmsf/webdav"
 33         @dav_app = Rack::Builder.new{
 34           map path do
```

makes everything go well.

**Comment by picman** [comment]
Duplicates #1088.

**Comment by picman** [comment]
Okay. I will change it back. Exactly oposite change has been done here https://github.com/willuhn/redmine_dmsf/commit/cd650de902581f8c19f84f1dbc3849df5aa7f60f.
