### ISSUE TITLE
Available in CSV Internal Error

### ISSUE THREAD

**Issue by AnestisK** [danmunn/redmine_dmsf#1175]
We've installed the DMSF Plugin on our test Redmine server, and when we select "Also Available in CSV: we get thje following:

> Internal error
> An error occurred on the page you were trying to access.
> If you continue to experience problems please contact your Redmine administrator for assistance.
> 
> If you are the Redmine administrator, check your log files for details about the error.

Let me know if you need any info from log files/etc.

Any help on how to fix this issue?

**Comment by picman** [comment]
1) Which version of DMSF?
2) What is in production.log?

**Comment by AnestisK** [comment]
DMSF Version 2.44
Redmine Version 4.0.7.stable installed form packages on Debian.
Ruby Version  2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
Rails version 5.2.4.3

```
`Started GET "/projects/itadmin/dmsf.csv" for 172.16.90.3 at 2020-09-18 00:43:48 +1000
Processing by DmsfController#show as CSV
  Parameters: {"id"=>"itadmin"}
  Current user: anestisk (id=95)
Completed 500 Internal Server Error in 248ms (ActiveRecord: 145.0ms)

FrozenError (can't modify frozen String):

lib/redmine/codeset_util.rb:59:in `force_encoding'
lib/redmine/codeset_util.rb:59:in `from_utf8'
lib/redmine/export/csv.rb:52:in `block in <<'
lib/redmine/export/csv.rb:49:in `map'
lib/redmine/export/csv.rb:49:in `<<'
app/helpers/queries_helper.rb:280:in `block in query_to_csv'
lib/redmine/export/csv.rb:44:in `generate'
lib/redmine/export/csv.rb:26:in `generate'
app/helpers/queries_helper.rb:278:in `query_to_csv'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:83:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:73:in `show'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
```
`

**Comment by picman** [comment]
Either upgrade to Redmine 4.1 or try to modify _lib/redmine/export/csv.rb_ as follows:

```ruby
38 -- str = ''.force_encoding(encoding)
38 ++ str = (+'').force_encoding(encoding)
39 if encoding == Encoding::UTF_8
40   # BOM
41 --   str = "\xEF\xBB\xBF".force_encoding(encoding)
41 ++   str = (+"\xEF\xBB\xBF").force_encoding(encoding)
42 end
```

**Comment by AnestisK** [comment]
There is no deb package for 4.1 available.

I made the changes to csv.rb as above and restarted the Apache server, but the same issue occurs,. with the same error messages in production.log.

`Processing by DmsfController#show as CSV
  Parameters: {"id"=>"itadmin"}
  Current user: anestisk (id=95)
Completed 500 Internal Server Error in 24ms (ActiveRecord: 2.8ms)

FrozenError (can't modify frozen String):

lib/redmine/codeset_util.rb:59:in `force_encoding'
lib/redmine/codeset_util.rb:59:in `from_utf8'
lib/redmine/export/csv.rb:52:in `block in <<'
lib/redmine/export/csv.rb:49:in `map'
lib/redmine/export/csv.rb:49:in `<<'
app/helpers/queries_helper.rb:280:in `block in query_to_csv'
lib/redmine/export/csv.rb:44:in `generate'
lib/redmine/export/csv.rb:26:in `generate'
app/helpers/queries_helper.rb:278:in `query_to_csv'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:83:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:73:in `show'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
`

**Comment by picman** [comment]
Try to add the following line as the first line of the file.

```ruby
# frozen_string_literal: true
```

**Comment by picman** [comment]
Or better check the lines from the log and if there is a string assignment, where string is later modified, add '+' befor the string, e.g.:

```str ||= ''```

=>

```str ||= +''```

**Comment by AnestisK** [comment]
I'm not an expert (or even a beginner) in Ruby.
It's still not working unless I did something incorrectly..
Perhaps if you can provide the list of changes and in which files they need to be made would help.

**Comment by picman** [comment]
Obviously , Redmine 4.0.7 and DMSF 2.4.4 are incompatible. So either install Redmine from source codes in order to have the latest stable version 4.1 or downgrade DMSF plugin to v2.4.1.

**Comment by AnestisK** [comment]
I deleted the 2.4.4 plugin and installed the 2.4.1 plugin (after rolling back the VM to before the changes to the files above were made).,
Now, when I select the DMSF module in a project I get 500 Internal error.
From prdouction.log
```
Started GET "/projects/itadmin/dmsf" for 172.16.90.3 at 2020-09-18 22:57:12 +1000
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"itadmin"}
  Current user: anestisk (id=95)
  Rendering plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (18.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (12.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dmsf_rows.erb (49.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_tree_view.erb (51.6ms)
public/plugin_assets/redmine_dmsf/javascripts/jquery.dataTables/locales/en.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (69.0ms)
Completed 500 Internal Server Error in 96ms (ActiveRecord: 10.5ms)

ActionView::Template::Error (no implicit conversion of true into String):
    153:               details: false
    154:           },
    155:           language: {
    156:               url: "<%= plugin_asset_path(:redmine_dmsf, 'javascripts', json_url) %>"
    157:           },
    158:           oLanguage: {
    159:             sSearch: "<%= l(:description_filter) %>:"

plugins/redmine_dmsf/app/helpers/dmsf_helper.rb:76:in `join'
plugins/redmine_dmsf/app/helpers/dmsf_helper.rb:76:in `plugin_asset_path'
plugins/redmine_dmsf/app/views/dmsf/show.html.erb:156:in `block (2 levels) in _plugins_redmine_dmsf_app_views_dmsf_show_html_erb___3876518338975700378_47286403937980'
plugins/redmine_dmsf/app/views/dmsf/show.html.erb:149:in `block in _plugins_redmine_dmsf_app_views_dmsf_show_html_erb___3876518338975700378_47286403937980'
plugins/redmine_dmsf/app/views/dmsf/show.html.erb:133:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb___3876518338975700378_47286403937980'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:64:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:62:in `show'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

```

**Comment by picman** [comment]
Check this problem. The file is a part of the plugin. Check the file permissions, restart the web server, ...
`public/plugin_assets/redmine_dmsf/javascripts/jquery.dataTables/locales/en.json not found`

**Comment by AnestisK** [comment]
The plugin (which is downloaded direct form the your git instance) has no such files.  They seem to be missing.

```
redmine_dmsf-2.4.4/assets/
redmine_dmsf-2.4.4/assets/images/
redmine_dmsf-2.4.4/assets/images/assigned.png
redmine_dmsf-2.4.4/assets/images/dmsf.png
redmine_dmsf-2.4.4/assets/images/filetypes/
redmine_dmsf-2.4.4/assets/images/filetypes/c_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/csharp_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/css_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/doc.png
redmine_dmsf-2.4.4/assets/images/filetypes/doc_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/docx.png
redmine_dmsf-2.4.4/assets/images/filetypes/html_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/image_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/java_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/js_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/mpp.png
redmine_dmsf-2.4.4/assets/images/filetypes/mpp_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/odg.png
redmine_dmsf-2.4.4/assets/images/filetypes/odg_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/odp.png
redmine_dmsf-2.4.4/assets/images/filetypes/odp_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/ods.png
redmine_dmsf-2.4.4/assets/images/filetypes/ods_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/odt.png
redmine_dmsf-2.4.4/assets/images/filetypes/odt_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/ott.png
redmine_dmsf-2.4.4/assets/images/filetypes/ott_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/pdf_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/php_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/ppt.png
redmine_dmsf-2.4.4/assets/images/filetypes/ppt_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/pptx.png
redmine_dmsf-2.4.4/assets/images/filetypes/ruby_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/vsd.png
redmine_dmsf-2.4.4/assets/images/filetypes/vsd_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/vsdx.png
redmine_dmsf-2.4.4/assets/images/filetypes/xls.png
redmine_dmsf-2.4.4/assets/images/filetypes/xls_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/xlsx.png
redmine_dmsf-2.4.4/assets/images/filetypes/xml_gray.png
redmine_dmsf-2.4.4/assets/images/filetypes/zip_gray.png
redmine_dmsf-2.4.4/assets/images/folder_gray.png
redmine_dmsf-2.4.4/assets/images/folder_system.png
redmine_dmsf-2.4.4/assets/images/none.png
redmine_dmsf-2.4.4/assets/images/waiting_for_approval.png
redmine_dmsf-2.4.4/assets/javascripts/
redmine_dmsf-2.4.4/assets/javascripts/attachments_dmsf.js
redmine_dmsf-2.4.4/assets/javascripts/bowser.min.js
redmine_dmsf-2.4.4/assets/javascripts/redmine_dmsf.js
redmine_dmsf-2.4.4/assets/javascripts/select2.min.js
redmine_dmsf-2.4.4/assets/stylesheets/
redmine_dmsf-2.4.4/assets/stylesheets/easy_extensions.css
redmine_dmsf-2.4.4/assets/stylesheets/img/
redmine_dmsf-2.4.4/assets/stylesheets/img/loading.gif
redmine_dmsf-2.4.4/assets/stylesheets/img/plupload.png
redmine_dmsf-2.4.4/assets/stylesheets/redmine_dmsf.css
redmine_dmsf-2.4.4/assets/stylesheets/select2.min.css

```

**Comment by AnestisK** [comment]
OK, had to copy assets folder directly into the public/plugin_assets/redmine_dmsf instead of public/plugin_assets/redmine_dmsf/assets/ as is the normal case for most redmine plugins.
CSV now works, but look and feel does not match Redmine 4 UI.
Is there a chance you could modify the v2.4.4. version of the plugin to work with Redmine 4.0.7

**Comment by picman** [comment]
I'd recommend you installing the latest version of Redmine from source codes instead of Debian's package. It's easy.

**Comment by AnestisK** [comment]
Unfortunately our organisation's processes prefers installing/upgrading from packages for easy maintenance and upgradability.

**Comment by picman** [comment]
I've just tested the following configuration. Everything including CSV export seemed to work fine. So, please test the branch _2.4.5-devel_ in your environment.
```
Environment:
  Redmine version                4.0.7.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    development
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   2.4.5 devel
```

**Comment by AnestisK** [comment]
CSV still gives the same error for v2.4.5 devel:

```
Started GET "/projects/itadmin/dmsf.csv" for 172.16.90.2 at 2020-09-24 09:00:06 +1000
Processing by DmsfController#show as CSV
  Parameters: {"id"=>"itadmin"}
  Current user: anestisk (id=95)
Completed 500 Internal Server Error in 18ms (ActiveRecord: 4.1ms)

FrozenError (can't modify frozen String):

lib/redmine/codeset_util.rb:59:in `force_encoding'
lib/redmine/codeset_util.rb:59:in `from_utf8'
lib/redmine/export/csv.rb:52:in `block in <<'
lib/redmine/export/csv.rb:49:in `map'
lib/redmine/export/csv.rb:49:in `<<'
app/helpers/queries_helper.rb:280:in `block in query_to_csv'
lib/redmine/export/csv.rb:44:in `generate'
lib/redmine/export/csv.rb:26:in `generate'
app/helpers/queries_helper.rb:278:in `query_to_csv'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:83:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:73:in `show'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'

```

**Comment by picman** [comment]
Could you post a similar screen-shot from your environment, please?

![image](https://user-images.githubusercontent.com/779003/94116244-15cd4d80-fe4b-11ea-84df-cdc90fcd9d58.png)

**Comment by AnestisK** [comment]
That section works fine.
![image](https://user-images.githubusercontent.com/13781656/94323340-bf8e1500-ffd8-11ea-8b97-b76b95a4bba7.png)

But clicking on CSV gives the following:

![image](https://user-images.githubusercontent.com/13781656/94323360-d7fe2f80-ffd8-11ea-9572-f34a58e6f981.png)

As before, production.log:

```
Started GET "/projects/itadmin/dmsf.csv" for 172.16.90.2 at 2020-09-26 09:16:12 +1000
Processing by DmsfController#show as CSV
  Parameters: {"id"=>"itadmin"}
  Current user: anestisk (id=95)
Completed 500 Internal Server Error in 29ms (ActiveRecord: 2.3ms)

FrozenError (can't modify frozen String):

lib/redmine/codeset_util.rb:59:in `force_encoding'
lib/redmine/codeset_util.rb:59:in `from_utf8'
lib/redmine/export/csv.rb:52:in `block in <<'
lib/redmine/export/csv.rb:49:in `map'
lib/redmine/export/csv.rb:49:in `<<'
app/helpers/queries_helper.rb:280:in `block in query_to_csv'
lib/redmine/export/csv.rb:44:in `generate'
lib/redmine/export/csv.rb:26:in `generate'
app/helpers/queries_helper.rb:278:in `query_to_csv'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:83:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:73:in `show'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'


```

**Comment by picman** [comment]
Excellent! I'm able reproduce the error. The problem is caused by the column `id`. As a quick workaround you can hide `id` column in the plugin's settings. I will fix it in v2.4.5.

**Comment by AnestisK** [comment]
Unchecking the Id column in the plugin settings worked.

**Comment by picman** [comment]
Fixed.
