### ISSUE TITLE
Error 500 when create new revision

### ISSUE THREAD

**Issue by teddyvn** [danmunn/redmine_dmsf#1214]
I am using Redmine 3.2.5 and DMSF version 1.5.6.
Recently, we receive Error 500 every times we create new revision.
Log:
```
2021-02-23 09:52:51 username@IP/: new revision dmsf://ivis_mnt/3293/
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (3.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (4.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (4.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (3.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (4.4ms)
Redirected to 
Completed 500 Internal Server Error in 15504ms (ActiveRecord: 598.6ms)

ActionController::RedirectBackError (No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].):
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:202:in `create_revision'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
```
I don't know how to fix it. Could you shed me a light?
Thanks

**Comment by picman** [comment]
1. Restart the app.
2. Restart the server.
3. Upgrade to Redmine 4.1 / DMSF 2.4.5

**Comment by teddyvn** [comment]
Thank picman. The enterprise production server isnot easy to upgrade. It has many rules, processed and policies.
I am tried to install Redmine same version in my workstation, install DMSF version 1.5.6 and run WebBrick. The probelm isn't producible. I think the problem is related to web server settings.

**Comment by picman** [comment]
Fixed. However, it doesn't solve your problem.
