### ISSUE TITLE
SQL Error when trying to list certain folders

### ISSUE THREAD

**Issue by nicupavel** [danmunn/redmine_dmsf#1254]
Hi, 

Out of the blue, clicking on certain folders (not all) to view files doesn't work. The error on logs is below. I inspected the tables and nothing out of the ordinary/different for those folders that spew this error. Any idea where to look ? 

Running redmine 4.2.1 and latest (from master a96624448eeea530e999c668b94fc4c24df7cacd)

```
ActionView::Template::Error (Mysql2::Error: Subquery returns more than 1 row: SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT DISTINCT
          dmsf_folders.id AS id,
          dmsf_folders.project_id AS project_id,
          CAST(NULL AS signed) AS revision_id,
          dmsf_folders.title AS title,
          NULL AS filename,
          CAST(NULL AS signed) AS size,
          dmsf_folders.updated_at AS updated,
          CAST(NULL AS signed) AS major_version,
          CAST(NULL AS signed) AS minor_version,
          CAST(NULL AS signed) AS workflow,
          CAST(NULL AS signed) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          'folder' AS type,
          dmsf_folders.deleted AS deleted,
          1 AS sort ,(SELECT value from custom_values WHERE custom_field_id = 1 AND customized_type = 'DmsfFolder' AND customized_id = dmsf_folders.id) AS cf_1,(SELECT value from custom_values WHERE custom_field_id = 2 AND customized_type = 'DmsfFolder' AND customized_id = dmsf_folders.id) AS cf_2 FROM `dmsf_folders` INNER JOIN `projects` ON `projects`.`id` = `dmsf_folders`.`project_id` LEFT JOIN users ON dmsf_folders.user_id = users.id LEFT JOIN dmsf_folder_permissions ON dmsf_folders.id = dmsf_folder_permissions.dmsf_folder_id WHERE `dmsf_folders`.`deleted` = 0 AND (projects.status <> 9 AND EXISTS (SELECT 1 AS one FROM enabled_modules em WHERE em.project_id = projects.id AND em.name='dmsf')) AND `dmsf_folders`.`dmsf_folder_id` = 15 AND `dmsf_folders`.`deleted` = 0) UNION ALL (SELECT
          dmsf_links.id AS id,
          COALESCE(dmsf_folders.project_id, dmsf_links.project_id) AS project_id,
          dmsf_links.target_id AS revision_id,
          dmsf_links.name AS title,
          dmsf_folders.title AS filename,
          CAST(NULL AS signed) AS size,
          COALESCE(dmsf_folders.updated_at, dmsf_links.updated_at) AS updated,
          CAST(NULL AS signed) AS major_version,
          CAST(NULL AS signed) AS minor_version,
          CAST(NULL AS signed) AS workflow,
          CAST(NULL AS signed) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          'folder-link' AS type,
          dmsf_links.deleted AS deleted,
          1 AS sort ,(SELECT value from custom_values WHERE custom_field_id = 1 AND customized_type = 'DmsfFolder' AND customized_id = dmsf_folders.id) AS cf_1,(SELECT value from custom_values WHERE custom_field_id = 2 AND customized_type = 'DmsfFolder' AND customized_id = dmsf_folders.id) AS cf_2 FROM `dmsf_links` LEFT JOIN dmsf_folders ON dmsf_links.target_id = dmsf_folders.id LEFT JOIN users ON users.id = COALESCE(dmsf_folders.user_id, dmsf_links.user_id) WHERE `dmsf_links`.`target_type` = 'DmsfFolder' AND `dmsf_links`.`dmsf_folder_id` = 15 AND `dmsf_links`.`deleted` = 0) ) `dmsf_folders`) UNION ALL (SELECT
        projects.id AS id,
        projects.id AS project_id,
        CAST(NULL AS signed) AS revision_id,
        projects.name AS title,
        projects.identifier AS filename,
        CAST(NULL AS signed) AS size,
        projects.updated_on AS updated,
        CAST(NULL AS signed) AS major_version,
        CAST(NULL AS signed) AS minor_version,
        CAST(NULL AS signed) AS workflow,
        CAST(NULL AS signed) AS workflow_id,
        '' AS firstname,
        '' AS lastname,
        CAST(NULL AS signed) AS author,
        'project' AS type,
        CAST(0 AS signed) AS deleted,
        0 AS sort ,NULL AS cf_1,NULL AS cf_2 FROM `projects` WHERE (projects.status <> 9) AND (1=0)) ) `dmsf_folders`) UNION ALL (SELECT
          dmsf_files.id AS id,
          dmsf_files.project_id AS project_id,
          dmsf_file_revisions.id AS revision_id,
          dmsf_file_revisions.title AS title,
          dmsf_file_revisions.name AS filename,
          dmsf_file_revisions.size AS size,
          dmsf_file_revisions.updated_at AS updated,
          dmsf_file_revisions.major_version AS major_version,
          dmsf_file_revisions.minor_version AS minor_version,
          dmsf_file_revisions.workflow AS workflow,
          dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          'file' AS type,
          dmsf_files.deleted AS deleted,
          2 AS sort ,(SELECT value from custom_values WHERE custom_field_id = 1 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id) AS cf_1,(SELECT value from custom_values WHERE custom_field_id = 2 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id) AS cf_2 FROM `dmsf_files` INNER JOIN `dmsf_file_revisions` ON `dmsf_file_revisions`.`dmsf_file_id` = `dmsf_files`.`id` LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) AND `dmsf_files`.`dmsf_folder_id` = 15 AND `dmsf_files`.`deleted` = 0) ) `dmsf_folders`) UNION ALL (SELECT
          dmsf_links.id AS id,
          dmsf_files.project_id AS project_id,
          dmsf_files.id AS revision_id,
          dmsf_links.name AS title,
          dmsf_file_revisions.name AS filename,
          dmsf_file_revisions.size AS size,
          dmsf_file_revisions.updated_at AS updated,
          dmsf_file_revisions.major_version AS major_version,
          dmsf_file_revisions.minor_version AS minor_version,
          dmsf_file_revisions.workflow AS workflow,
          dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          'file-link' AS type,
          dmsf_links.deleted AS deleted,
          2 AS sort ,(SELECT value from custom_values WHERE custom_field_id = 1 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id) AS cf_1,(SELECT value from custom_values WHERE custom_field_id = 2 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id) AS cf_2 FROM `dmsf_links` JOIN dmsf_files ON dmsf_files.id = dmsf_links.target_id JOIN dmsf_file_revisions ON dmsf_file_revisions.dmsf_file_id = dmsf_files.id LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) AND `dmsf_links`.`target_type` = 'DmsfFile' AND `dmsf_links`.`dmsf_folder_id` = 15 AND `dmsf_links`.`deleted` = 0) ) `dmsf_folders`) UNION ALL (SELECT
          dmsf_links.id AS id,
          dmsf_links.project_id AS project_id,
          CAST(NULL AS signed) AS revision_id,
          dmsf_links.name AS title,
          dmsf_links.external_url AS filename,
          CAST(NULL AS signed) AS size,
          dmsf_links.updated_at AS updated,
          CAST(NULL AS signed) AS major_version,
          CAST(NULL AS signed) AS minor_version,
          CAST(NULL AS signed) AS workflow,
          CAST(NULL AS signed) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          'url-link' AS type,
          dmsf_links.deleted AS deleted,
           2 AS sort ,NULL AS cf_1,NULL AS cf_2 FROM `dmsf_links` LEFT JOIN users ON dmsf_links.user_id = users.id WHERE `dmsf_links`.`target_type` = 'DmsfUrl' AND `dmsf_links`.`dmsf_folder_id` = 15 AND `dmsf_links`.`deleted` = 0) ) `dmsf_folders` ORDER BY sort, title ASC):
  F, [2021-05-16T02:00:24.000474 #856] FATAL -- :     25:   <% options[:offset] = dmsf_pages.offset %>
      26:   <% options[:limit] = dmsf_pages.per_page %>
      27: <% end %>
      28: <% query.dmsf_nodes(options).each do |node| %>
      29:   <% system = node.title =~ /^\./ %>
      30:   <% case node.type %>
      31:   <% when 'project'%>
  F, [2021-05-16T02:00:24.000505 #856] FATAL -- :
  F, [2021-05-16T02:00:24.000526 #856] FATAL -- : plugins/redmine_dmsf/app/models/dmsf_query.rb:171:in `dmsf_nodes'
  plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:28:in `_plugins_redmine_dmsf_app_views_dmsf__query_rows_erb___4149837601761511939_175720'
  plugins/redmine_dmsf/app/views/dmsf/query_rows.js.erb:2:in `_plugins_redmine_dmsf_app_views_dmsf_query_rows_js_erb__1492550778330054871_175700'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:67:in `block (2 levels) in expand_folder'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:66:in `expand_folder'
  lib/redmine/sudo_mode.rb:61:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'
```

**Comment by picman** [comment]
It must be somehow related to data in your database. If I test the SQL query above in my database, it works fine. Unfortunately the error is general and it's not easy to identify what is wrong. I think that the only way is to take the query and test it directly. Then step by step removing working parts of the query and identify the problem. E.g.:
```bash
 mysql -u redmine -p redmine < test.sql
```
Then reduce the query. E.g. you know that there are no sub-projects and no links => remove the related part from the query.
The error will be very probably related to files. So finally you could test just this query:
```sql
SELECT
          dmsf_files.id AS id,
          (SELECT value from custom_values WHERE custom_field_id = 1 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id) AS cf_1,(SELECT value from custom_values WHERE custom_field_id = 2 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id) AS cf_2 FROM `dmsf_files` INNER JOIN `dmsf_file_revisions` ON `dmsf_file_revisions`.`dmsf_file_id` = `dmsf_files`.`id` LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) AND `dmsf_files`.`dmsf_folder_id` = 15 AND `dmsf_files`.`deleted` = 0;
```

**Comment by picman** [comment]
I remember a similar error, that occurred if there were revisions of the same file with identical _created_at_ column.

**Comment by picman** [comment]
Or, if your database doesn't contain sensitive data, send me its dump, I will investigate it.

**Comment by nicupavel** [comment]
The sub-query still returns error:

```
 select dmsf_files.id as id,  (SELECT value from custom_values WHERE custom_field_id = 1 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id) AS cf_1,(SELECT value from custom_values WHERE custom_field_id = 2 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id) AS cf_2 FROM `dmsf_files` INNER JOIN `dmsf_file_revisions` ON `dmsf_file_revisions`.`dmsf_file_id` = `dmsf_files`.`id` LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) AND `dmsf_files`.`dmsf_folder_id` = 15 AND `dmsf_files`.`deleted` = 0;

ERROR 1242 (21000): Subquery returns more than 1 row
```


dmsf_* tables have no sensitive data so I added the dump from them. Maybe it helps. Thank you.
[dmsf_dump.zip](https://github.com/danmunn/redmine_dmsf/files/6495409/dmsf_dump.zip)

**Comment by picman** [comment]
If I import your tables and run the query, no erorr is present
```sql
mysql> select 
    -> dmsf_files.id as id  
    -> FROM `dmsf_files` INNER JOIN `dmsf_file_revisions` ON `dmsf_file_revisions`.`dmsf_file_id` = `dmsf_files`.`id` 
    -> LEFT JOIN users ON dmsf_file_revisions.user_id = users.id 
    -> WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) 
    -> AND `dmsf_files`.`dmsf_folder_id` = 15 
    -> AND `dmsf_files`.`deleted` = 0;
+----+
| id |
+----+
| 34 |
+----+
1 row in set (0,00 sec)
```
If I check the revisions, they look also Okay.
```sql
mysql> select r.id, r.created_at from dmsf_file_revisions r join dmsf_files f on f.id = r.dmsf_file_id
where f.dmsf_folder_id = 15;
+-----+---------------------+
| id  | created_at          |
+-----+---------------------+
|  61 | 2021-04-30 16:02:08 |
|  66 | 2021-05-05 17:36:08 |
|  82 | 2021-05-12 09:22:51 |
| 110 | 2021-05-12 09:29:36 |
| 111 | 2021-05-12 09:30:43 |
+-----+---------------------+
5 rows in set (0,00 sec)
```

Try these queries in your environment and post results.

**Comment by nicupavel** [comment]
Both work fine with same results as yours.

**Comment by picman** [comment]
So then the only possibility is that the error is in these custom fields related sub-queries. Please test them.

```sql
SELECT value from custom_values WHERE custom_field_id = 1 AND customized_type = 'DmsfFileRevision' AND customized_id = 111;
SELECT value from custom_values WHERE custom_field_id = 2 AND customized_type = 'DmsfFileRevision' AND customized_id = 111;
```

**Comment by picman** [comment]
Could you dump also _custom_fields_ and _custom_values_ tables?

**Comment by nicupavel** [comment]
```
mysql> SELECT value from custom_values WHERE custom_field_id = 1 AND customized_type = 'DmsfFileRevision' AND customized_id = 111;
+-------------------+
| value             |
+-------------------+
| MFG-Manufacturing |
| MAT-Materials     |
+-------------------+
2 rows in set (0.00 sec)

mysql> SELECT value from custom_values WHERE custom_field_id = 2 AND customized_type = 'DmsfFileRevision' AND customized_id = 111;
+-------+
| value |
+-------+
|       |
+-------+
1 row in set (0.00 sec)
```

**Comment by picman** [comment]
What is the settings of custom field 1? I mean type, values,...

**Comment by nicupavel** [comment]
[redmine_custom_fields_values.zip](https://github.com/danmunn/redmine_dmsf/files/6499544/redmine_custom_fields_values.zip)

**Comment by nicupavel** [comment]
```
mysql> select * from custom_fields where id = 1;
+----+-----------------------------+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------+-------------+------------+-----------+----------+------------+---------------+----------+---------+----------+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------+
| id | type                        | name              | field_format | possible_values                                                                                                                                                                                                               | regexp | min_length | max_length | is_required | is_for_all | is_filter | position | searchable | default_value | editable | visible | multiple | format_store                                                                                | description                                                            | dmsf_not_inheritable |
+----+-----------------------------+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------+-------------+------------+-----------+----------+------------+---------------+----------+---------+----------+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------+
|  1 | DmsfFileRevisionCustomField | Business Category | list         | ---
- GEN-General
- BIS-Business Systems
- BIO-Biology
- ENG-Engineering
- RND-Research and Development
- MFG-Manufacturing
- MAT-Materials
- QLT-Quality
- REG-Regulatory
- HRB-Human Resources
- MKT-Marketing
- SLS-Sales
 |        |       NULL |       NULL |           1 |          0 |         1 |        1 |          0 |               |        1 |       1 |        1 | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
url_pattern: ''
edit_tag_style: ''
 | Business Category that document applies to. Select multiple if needed. |                 NULL |
+----+-----------------------------+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------+-------------+------------+-----------+----------+------------+---------------+----------+---------+----------+---------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------+
1 row in set (0.01 sec)

mysql>
```

**Comment by picman** [comment]
The error is related to the custom field with **Multiple values** _On_. I will fix it.

**Comment by picman** [comment]
Fixed. Please test it with _devel-2.4.8_ branch.

**Comment by nicupavel** [comment]
Yes it works perfectly on devel-2.4.8. Thank you !
