### ISSUE TITLE
Multiple Values on custom field Tag cause internal error

### ISSUE THREAD

**Issue by hermannkm** [danmunn/redmine_dmsf#1269]
According to documentation I added a **custom field "Tag"** with "Multiple Values" checked. Worked when when selecting one value, but **crashes when selecting two or more**. Log file entry is lengthy, shortened looks like this:

```
Started POST "/dmsf/files/149/revision/create" for 178.115.58.27 at 2021-07-21 07:46:43 +0200
Processing by DmsfFilesController#create_revision as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"WKwZalwV/UUpEmu7071pNPjYtZg/Tjvh5qbQKAMZChQcwPj3eGuCrAd8kqf0kRR71cVKHsNP+sAcd3CWFIPspA==", "dmsf_file_revision"=>{"title"=>"Tablets im Bildungseinsatz Grundschule", "name"=>"Tablets im Bildungseinsatz Grundschule.pdf", "description"=>"", "custom_field_values"=>{"8"=>"", "10"=>["Prim", "SekI", ""]}, "comment"=>""}, "version"=>"0", "custom_version_major"=>"3", "custom_version_minor"=>"2", "commit"=>"Anlegen", "id"=>"149"}
  Current user: admin (id=1)
Redirected to https://redmine.klocker-mark.eu/projects/21/dmsf
Completed 302 Found in 84ms (ActiveRecord: 46.0ms)
Started GET "/projects/21/dmsf" for 178.115.58.27 at 2021-07-21 07:46:43 +0200
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"21"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 32ms (ActiveRecord: 14.4ms)

Query::StatementInvalid (Mysql2::Error: Subquery returns more than 1 row: SELECT COUNT(*) FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT DISTINCT
        dmsf_folders.id AS id,
        dmsf_folders.project_id AS project_id,
        CAST(NULL AS signed) AS revision_id,
        dmsf_folders.title AS title,
        NULL AS filename,
        CAST(NULL AS signed) AS size,
        dmsf_folders.updated_at AS updated,
        CAST(NULL AS signed) AS major_version,
        CAST(NULL AS signed) AS minor_version,
        CAST(NULL AS signed) AS workflow,
        CAST(NULL AS signed) AS workflow_id,
        users.firstname AS firstname,
        users.lastname AS lastname,
        users.id AS author,
        'folder' AS type,
        dmsf_folders.deleted AS deleted,
        [...]

plugins/redmine_dmsf/app/models/dmsf_query.rb:95:in `rescue in dmsf_count'
plugins/redmine_dmsf/app/models/dmsf_query.rb:92:in `dmsf_count'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:92:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:90:in `show'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

```

Environment:
  Redmine version                4.2.1.stable.21007
  Ruby version                   2.7.2-p137 (2020-10-01) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  additional_tags                1.0.2
  additionals                    3.0.3-master
  redmine_dmsf                   2.4.7

**Comment by picman** [comment]
Duplicates #1254.

**Comment by hermannkm** [comment]
Thank you! What a great plugin and what a fast response. Worked instantly.
