### ISSUE TITLE
Error when sorting on custom field

### ISSUE THREAD

**Issue by hermannkm** [danmunn/redmine_dmsf#1279]
Using 2.4.8 devel I tried to sort on custom field 8 (number) and got an error report.

```
Completed 500 Internal Server Error in 67ms (ActiveRecord: 21.0ms)

ActionView::Template::Error (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC,3)) DESC LIMIT 25 OFFSET 0' at line 115: SELECT  `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT `dmsf_folders`.* FROM ( (SELECT DISTINCT
        dmsf_folders.id AS id,
        dmsf_folders.project_id AS project_id,
        CAST(NULL AS signed) AS revision_id,
        dmsf_folders.title AS title,
        NULL AS filename,
        CAST(NULL AS signed) AS size,
        dmsf_folders.updated_at AS updated,
        CAST(NULL AS signed) AS major_version,
        CAST(NULL AS signed) AS minor_version,
        CAST(NULL AS signed) AS workflow,
        CAST(NULL AS signed) AS workflow_id,
        users.firstname AS firstname,
        users.lastname AS lastname,
        users.id AS author,
        'folder' AS type,
        dmsf_folders.deleted AS deleted,
        'DmsfFolder' AS customized_type,
        dmsf_folders.id AS customized_id,
        1 AS sort,(SELECT GROUP_CONCAT(value) FROM custom_values WHERE custom_field_id = 8 AND customized_type = 'DmsfFolder' AND customized_id = dmsf_folders.id GROUP BY custom_field_id) AS cf_8,(SELECT GROUP_CONCAT(value) FROM custom_values WHERE custom_field_id = 10 AND customized_type = 'DmsfFolder' AND customized_id = dmsf_folders.id GROUP BY custom_field_id) AS cf_10 FROM `dmsf_folders` INNER JOIN `projects` ON `projects`.`id` = `dmsf_folders`.`project_id` LEFT JOIN users ON dmsf_folders.user_id = users.id LEFT JOIN dmsf_folder_permissions ON dmsf_folders.id = dmsf_folder_permissions.dmsf_folder_id WHERE `dmsf_folders`.`deleted` = 0 AND (projects.status <> 9 AND EXISTS (SELECT 1 AS one FROM enabled_modules em WHERE em.project_id = projects.id AND em.name='dmsf')) AND `dmsf_folders`.`project_id` = 21 AND `dmsf_folders`.`dmsf_folder_id` IS NULL AND `dmsf_folders`.`deleted` = 0) UNION ALL (SELECT
        dmsf_links.id AS id,
        COALESCE(dmsf_folders.project_id, dmsf_links.project_id) AS project_id,
        dmsf_links.target_id AS revision_id,
        dmsf_links.name AS title,
        dmsf_folders.title AS filename,
        CAST(NULL AS signed) AS size,
        COALESCE(dmsf_folders.updated_at, dmsf_links.updated_at) AS updated,
        CAST(NULL AS signed) AS major_version,
        CAST(NULL AS signed) AS minor_version,
        CAST(NULL AS signed) AS workflow,
        CAST(NULL AS signed) AS workflow_id,
        users.firstname AS firstname,
        users.lastname AS lastname,
        users.id AS author,
        'folder-link' AS type,
        dmsf_links.deleted AS deleted,
        'DmsfFolder' as customized_type,
        dmsf_folders.id as customized_id,
        1 AS sort,(SELECT GROUP_CONCAT(value) FROM custom_values WHERE custom_field_id = 8 AND customized_type = 'DmsfFolder' AND customized_id = dmsf_folders.id GROUP BY custom_field_id) AS cf_8,(SELECT GROUP_CONCAT(value) FROM custom_values WHERE custom_field_id = 10 AND customized_type = 'DmsfFolder' AND customized_id = dmsf_folders.id GROUP BY custom_field_id) AS cf_10 FROM `dmsf_links` LEFT JOIN dmsf_folders ON dmsf_links.target_id = dmsf_folders.id LEFT JOIN users ON users.id = COALESCE(dmsf_folders.user_id, dmsf_links.user_id) WHERE `dmsf_links`.`target_type` = 'DmsfFolder' AND `dmsf_links`.`project_id` = 21 AND `dmsf_links`.`dmsf_folder_id` IS NULL AND `dmsf_links`.`deleted` = 0) ) `dmsf_folders`) UNION ALL (SELECT
      projects.id AS id,
      projects.id AS project_id,
      CAST(NULL AS signed) AS revision_id,
      projects.name AS title,
      projects.identifier AS filename,
      CAST(NULL AS signed) AS size,
      projects.updated_on AS updated,
      CAST(NULL AS signed) AS major_version,
      CAST(NULL AS signed) AS minor_version,
      CAST(NULL AS signed) AS workflow,
      CAST(NULL AS signed) AS workflow_id,
      '' AS firstname,
      '' AS lastname,
      CAST(NULL AS signed) AS author,
      'project' AS type,
      CAST(0 AS signed) AS deleted,
      0 AS sort,NULL AS cf_8,NULL AS cf_10,
      '' as customized_type,
      0 as customized_id FROM `projects` WHERE (projects.status <> 9) AND `projects`.`parent_id` = 21) ) `dmsf_folders`) UNION ALL (SELECT
        dmsf_files.id AS id,
        dmsf_files.project_id AS project_id,
        dmsf_file_revisions.id AS revision_id,
        dmsf_file_revisions.title AS title,
        dmsf_file_revisions.name AS filename,
        dmsf_file_revisions.size AS size,
        dmsf_file_revisions.updated_at AS updated,
        dmsf_file_revisions.major_version AS major_version,
        dmsf_file_revisions.minor_version AS minor_version,
        dmsf_file_revisions.workflow AS workflow,
        dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
        users.firstname AS firstname,
        users.lastname AS lastname,
        users.id AS author,
        'file' AS type,
        dmsf_files.deleted AS deleted,
        'DmsfFileRevision' as customized_type,
        dmsf_file_revisions.id as customized_id,
        2 AS sort,(SELECT GROUP_CONCAT(value) FROM custom_values WHERE custom_field_id = 8 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id GROUP BY custom_field_id) AS cf_8,(SELECT GROUP_CONCAT(value) FROM custom_values WHERE custom_field_id = 10 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id GROUP BY custom_field_id) AS cf_10 FROM `dmsf_files` INNER JOIN `dmsf_file_revisions` ON `dmsf_file_revisions`.`dmsf_file_id` = `dmsf_files`.`id` LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) AND `dmsf_files`.`project_id` = 21 AND `dmsf_files`.`dmsf_folder_id` IS NULL AND `dmsf_files`.`deleted` = 0) ) `dmsf_folders`) UNION ALL (SELECT
        dmsf_links.id AS id,
        dmsf_files.project_id AS project_id,
        dmsf_files.id AS revision_id,
        dmsf_links.name AS title,
        dmsf_file_revisions.name AS filename,
        dmsf_file_revisions.size AS size,
        dmsf_file_revisions.updated_at AS updated,
        dmsf_file_revisions.major_version AS major_version,
        dmsf_file_revisions.minor_version AS minor_version,
        dmsf_file_revisions.workflow AS workflow,
        dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
        users.firstname AS firstname,
        users.lastname AS lastname,
        users.id AS author,
        'file-link' AS type,
        dmsf_links.deleted AS deleted,
        'DmsfFileRevision' as customized_type,
        dmsf_file_revisions.id as customized_id,
        2 AS sort,(SELECT GROUP_CONCAT(value) FROM custom_values WHERE custom_field_id = 8 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id GROUP BY custom_field_id) AS cf_8,(SELECT GROUP_CONCAT(value) FROM custom_values WHERE custom_field_id = 10 AND customized_type = 'DmsfFileRevision' AND customized_id = dmsf_file_revisions.id GROUP BY custom_field_id) AS cf_10 FROM `dmsf_links` JOIN dmsf_files ON dmsf_files.id = dmsf_links.target_id JOIN dmsf_file_revisions ON dmsf_file_revisions.dmsf_file_id = dmsf_files.id LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) AND `dmsf_links`.`target_type` = 'DmsfFile' AND `dmsf_links`.`project_id` = 21 AND `dmsf_links`.`dmsf_folder_id` IS NULL AND `dmsf_links`.`deleted` = 0) ) `dmsf_folders`) UNION ALL (SELECT
        dmsf_links.id AS id,
        dmsf_links.project_id AS project_id,
        CAST(NULL AS signed) AS revision_id,
        dmsf_links.name AS title,
        dmsf_links.external_url AS filename,
        CAST(NULL AS signed) AS size,
        dmsf_links.updated_at AS updated,
        CAST(NULL AS signed) AS major_version,
        CAST(NULL AS signed) AS minor_version,
        CAST(NULL AS signed) AS workflow,
        CAST(NULL AS signed) AS workflow_id,
        users.firstname AS firstname,
        users.lastname AS lastname,
        users.id AS author,
        'url-link' AS type,
        dmsf_links.deleted AS deleted,
        '' as customized_type,
        0 as customized_id,
        2 AS sort,NULL AS cf_8,NULL AS cf_10 FROM `dmsf_links` LEFT JOIN users ON dmsf_links.user_id = users.id WHERE `dmsf_links`.`target_type` = 'DmsfUrl' AND `dmsf_links`.`project_id` = 21 AND `dmsf_links`.`dmsf_folder_id` IS NULL AND `dmsf_links`.`deleted` = 0) ) `dmsf_folders` ORDER BY sort, CAST(CASE cf_8.value WHEN '' THEN '0' ELSE cf_8.value END AS decimal(30  DESC,3)) DESC LIMIT 25 OFFSET 0):
    25:   <% options[:offset] = dmsf_pages.offset %>
    26:   <% options[:limit] = dmsf_pages.per_page %>
    27: <% end %>
    28: <% query.dmsf_nodes(options).each do |node| %>
    29:   <% system = node.title =~ /^\./ %>
    30:   <% case node.type %>
    31:   <% when 'project'%>

plugins/redmine_dmsf/app/models/dmsf_query.rb:185:in `dmsf_nodes'
plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:28:in `_plugins_redmine_dmsf_app_views_dmsf__query_rows_erb__1533448108140407898_160240'
plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb:49:in `block in _plugins_redmine_dmsf_app_views_dmsf__query_list_html_erb__4577796550297161736_160220'
plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb:26:in `_plugins_redmine_dmsf_app_views_dmsf__query_list_html_erb__4577796550297161736_160220'
plugins/redmine_dmsf/app/views/dmsf/_main.html.erb:86:in `_plugins_redmine_dmsf_app_views_dmsf__main_html_erb__1683818535565131983_160120'
plugins/redmine_dmsf/app/views/dmsf/show.html.erb:25:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb__3127131233135972937_160480'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:94:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:90:in `show'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :visible. Overwriting existing method Principal.visible.
Creating scope :visible. Overwriting existing method Principal.visible.
```

**Comment by picman** [comment]
Fixed.

**Comment by hermannkm** [comment]
Thank you. Confirmed, view is now working.
