### ISSUE TITLE
Mysql2::Error: Operand should contain 1 column(s)

### ISSUE THREAD

**Issue by openncomp** [danmunn/redmine_dmsf#1306]
Hello, thank you for the wonderful plugin and for supporting it!
___
There was a problem accessing DMS from the top line of the general menu.
Previously, when I clicked the link in the general menu, I got into the list of all the project directories available to me.
Now when I click on DMS in the general menu, I get the error "Internal error".
In the logs I see this entry:

```
Completed 500 Internal Server Error in 64ms (ActiveRecord: 58.1ms)
App 19980 output:   
App 19980 output: Query::StatementInvalid (Mysql2::Error: Operand should contain 1 column(s): SELECT COUNT(*) FROM ( (SELECT 
App 19980 output:         dmsf_folders.id AS id,
App 19980 output:         dmsf_folders.project_id AS project_id,
App 19980 output:         CAST(NULL AS signed) AS revision_id,
App 19980 output:         dmsf_folders.title AS title,
App 19980 output:         NULL AS filename,
App 19980 output:         CAST(NULL AS signed) AS size,
App 19980 output:         dmsf_folders.updated_at AS updated,
App 19980 output:         CAST(NULL AS signed) AS major_version,
App 19980 output:         CAST(NULL AS signed) AS minor_version,
App 19980 output:         CAST(NULL AS signed) AS workflow,
App 19980 output:         CAST(NULL AS signed) AS workflow_id,
App 19980 output:         users.firstname AS firstname,
App 19980 output:         users.lastname AS lastname,
App 19980 output:         users.id AS author,
App 19980 output:         'folder' AS type,
App 19980 output:         dmsf_folders.deleted AS deleted,
App 19980 output:         'DmsfFolder' AS customized_type,
App 19980 output:         dmsf_folders.id AS customized_id,
App 19980 output:         1 AS sort FROM `dmsf_folders` LEFT JOIN users ON dmsf_folders.user_id = users.id WHERE (1=0)) UNION ALL (SELECT 
App 19980 output:       projects.id AS id,
App 19980 output:       projects.id AS project_id,
App 19980 output:       CAST(NULL AS signed) AS revision_id,
App 19980 output:       projects.name AS title,
App 19980 output:       projects.identifier AS filename,
App 19980 output:       CAST(NULL AS signed) AS size,
App 19980 output:       projects.updated_on AS updated,
App 19980 output:       CAST(NULL AS signed) AS major_version,
App 19980 output:       CAST(NULL AS signed) AS minor_version,
App 19980 output:       CAST(NULL AS signed) AS workflow,
App 19980 output:       CAST(NULL AS signed) AS workflow_id,
App 19980 output:       '' AS firstname,
App 19980 output:       '' AS lastname,
App 19980 output:       CAST(NULL AS signed) AS author,
App 19980 output:       'project' AS type,
App 19980 output:       CAST(0 AS signed) AS deleted,
App 19980 output:       0 AS sort,
App 19980 output:       '' as customized_type,
App 19980 output:       0 as customized_id FROM `projects` WHERE (( projects.status <> 9 OR (projects.id IN (SELECT 
App 19980 output:       projects.id AS id,
App 19980 output:       projects.id AS project_id,
App 19980 output:       CAST(NULL AS signed) AS revision_id,
App 19980 output:       projects.name AS title,
App 19980 output:       projects.identifier AS filename,
App 19980 output:       CAST(NULL AS signed) AS size,
App 19980 output:       projects.updated_on AS updated,
App 19980 output:       CAST(NULL AS signed) AS major_version,
App 19980 output:       CAST(NULL AS signed) AS minor_version,
App 19980 output:       CAST(NULL AS signed) AS workflow,
App 19980 output:       CAST(NULL AS signed) AS workflow_id,
App 19980 output:       '' AS firstname,
App 19980 output:       '' AS lastname,
App 19980 output:       CAST(NULL AS signed) AS author,
App 19980 output:       'project' AS type,
App 19980 output:       CAST(0 AS signed) AS deleted,
App 19980 output:       0 AS sort,
App 19980 output:       '' as customized_type,
App 19980 output:       0 as customized_id, `projects`.`id` FROM `projects` INNER JOIN `issues` ON `issues`.`project_id` = `projects`.`id` WHERE (( (projects.status <> 9 AND EXISTS (SELECT 1 AS one FROM enabled_modules em WHERE em.project_id = projects.id AND em.name='issue_tracking')) OR ( (issues.id IN (SELECT `issues`.`id` FROM `issues` INNER JOIN `watchers` ON `watchers`.`watchable_id` = `issues`.`id` AND `watchers`.`watchable_type` = 'Issue' WHERE `watchers`.`user_id` IN (6, 7))) AND ( 1=1 )) ) ))) )) AND `projects`.`parent_id` IS NULL) ) `dmsf_folders`):
App 19980 output:   
```

But if I go to the project first, and select DMS there, then there are no errors and I see all the directories in this project.

I tried to completely remove DMSF:
- deleted all directories in all projects
- deleted all related directories from the Redmine server
- with the command
`rake redmine:plugins:migrate NAME=redmine_dmsf VERSION=0 RAILS_ENV=production`

After executing the command, I received a message:
```
Index name 'index_dmsf_files_on_project_id' on table 'dmsf_files' does not exist
/var/www/redmine/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:79:in `down'
/var/www/redmine/lib/redmine/plugin.rb:552:in `down'
/var/www/redmine/lib/redmine/plugin.rb:574:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:515:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:526:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'

Caused by:
ArgumentError: Index name 'index_dmsf_files_on_project_id' on table 'dmsf_files' does not exist
/var/www/redmine/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:79:in `down'
/var/www/redmine/lib/redmine/plugin.rb:552:in `down'
/var/www/redmine/lib/redmine/plugin.rb:574:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:515:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:526:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
```
But during the subsequent installation, there were no problems when executing:
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production && bundle exec rake db:migrate RAILS_ENV=production`

I get normal command output without error:
```
== 20170422104901 MigrateDocuments: migrating =================================
-- DmsfFile ID 2: project = nil
-- DmsfFile ID 4: project = nil
== 20170422104901 MigrateDocuments: migrated (0.0399s) ========================

== 20170526144701 DmsfAttachable: migrating ===================================
-- add_column(:projects, :dmsf_act_as_attachable, :integer, {:default=>1, :null=>false})
   -> 0.0587s
== 20170526144701 DmsfAttachable: migrated (0.0604s) ==========================

== 20171027124101 ChangeRevisionDigestLimitTo64: migrating ====================
-- change_column(:dmsf_file_revisions, :digest, :string, {:limit=>64})
   -> 0.0114s
== 20171027124101 ChangeRevisionDigestLimitTo64: migrated (0.0114s) ===========

== 20171110155901 AddIndexToDmsfFolder: migrating =============================
-- add_index(:dmsf_folders, :dmsf_folder_id)
   -> 0.1754s
== 20171110155901 AddIndexToDmsfFolder: migrated (0.1754s) ====================

== 20180216152501 RenameTitleFormat: migrating ================================
-- rename_column(:members, :title_format, :dmsf_title_format)
   -> 0.0339s
== 20180216152501 RenameTitleFormat: migrated (0.0340s) =======================

== 20180903132101 FastLinks: migrating ========================================
-- add_column(:members, :dmsf_fast_links, :boolean, {:default=>false, :null=>false})
   -> 0.0419s
== 20180903132101 FastLinks: migrated (0.0419s) ===============================

== 20192703123101 WorkflowStartedBy: migrating ================================
-- rename_column(:dmsf_file_revisions, :dmsf_workflow_assigned_by, :dmsf_workflow_assigned_by_user_id)
   -> 0.0756s
-- rename_column(:dmsf_file_revisions, :dmsf_workflow_started_by, :dmsf_workflow_started_by_user_id)
   -> 0.0673s
== 20192703123101 WorkflowStartedBy: migrated (0.1429s) =======================

== 20200218142414 AddIndexOnDmsfFileRevisionIdToAccess: migrating =============
-- add_index(:dmsf_file_revision_accesses, :dmsf_file_revision_id)
   -> 0.2589s
== 20200218142414 AddIndexOnDmsfFileRevisionIdToAccess: migrated (0.2590s) ====

== 20200423071301 AddIndexesOnDmsfFolderId: migrating =========================
-- add_index(:dmsf_files, :dmsf_folder_id)
   -> 0.2255s
-- add_index(:dmsf_links, :dmsf_folder_id)
   -> 0.1260s
== 20200423071301 AddIndexesOnDmsfFolderId: migrated (0.3516s) ================

== 20200813075501 ChangeIndexInDmsfLocks: migrating ===========================
-- remove_index(:dmsf_locks, :entity_id)
   -> 0.0753s
-- add_index(:dmsf_locks, [:entity_id, :entity_type])
   -> 0.1423s
== 20200813075501 ChangeIndexInDmsfLocks: migrated (0.2177s) ==================

== 20210115120901 AddOwnerToDmsfLock: migrating ===============================
-- add_column(:dmsf_locks, :owner, :string, {:null=>true})
   -> 0.0334s
== 20210115120901 AddOwnerToDmsfLock: migrated (0.0335s) ======================
```

But even after a complete reinstall, I get the described problem.
Maybe you can tell me what's going on?
___
My system:
```
Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.7
  additional_tags                1.0.2
  additionals                    3.0.3
  nxs_chat                       2.0
  redmica_ui_extension           0.0.1
  redmine_agile                  1.6.2
  redmine_base_deface            1.5.3
  redmine_checklists             3.1.19
  redmine_cms                    1.2.2
  redmine_contacts               4.3.4
  redmine_default_assignee       1.1.0
  redmine_dmsf                   2.4.10
  redmine_drawio                 1.1.4
  redmine_extended_watchers      4.2.2
  redmine_hide_estimated_hours   1.0.14
  redmine_impersonate            2.0.0
  redmine_incoming_emails        0.0.1
  redmine_issue_dynamic_edit     0.7.2
  redmine_login_attempts_limit   0.1.1
  redmine_mentions               0.0.1
  redmine_message_customize      0.1.0
  redmine_more_previews          2.0.7
  redmine_out_of_band_auth       1.0.0
  redmine_priorities_duedate_js  0.1.0
  redmine_questions              1.0.2
  redmine_shortcuts              0.5.1
  redmine_silencer               0.4.3
  redmine_theme_changer          0.4.0
  sidebar_hide                   0.0.8
  that_email_log                 0.0.4
  that_issue_reply_button        0.0.1
  that_resent_notification       0.0.1
  unread_issues                  2.2.4
  vault                          0.4.3

```
___
Thank you!

**Comment by kyvaith** [comment]
Same problem here
