### ISSUE TITLE
Using plugin with Redmine SVN trunk

### ISSUE THREAD

**Issue by deining** [danmunn/redmine_dmsf#1340]
I tried to install `redmine_dmsf` with Redmine SVN trunk and ran into trouble:

- `bundle install`

```
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 6.1.4.6)

  In Gemfile:
    rails (= 6.1.4.6)

    redmine_extensions (~> 0.3.9) was resolved to 0.3.11, which depends on
      rails (< 6.1, >= 4.2)
```

Im the plugin's `GEMFILE` I changed version of  `redmine_extensions` to latest version `0.4.3` and tried to migrate the plugin. This resulted in a failure:

```
C:\Redmine\redmine-from-trunk>bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant Redmine::Hook
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/redmine_extensions-0.4.3/lib/redmine_extensions/hooks.rb:2:in `<module:RedmineExtensions>'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/redmine_extensions-0.4.3/lib/redmine_extensions/hooks.rb:1:in `<top (required)>'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/redmine_extensions-0.4.3/lib/redmine_extensions/engine.rb:79:in `require_relative'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/redmine_extensions-0.4.3/lib/redmine_extensions/engine.rb:79:in `block in <class:Engine>'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `instance_exec'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `run'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:61:in `block in run_initializers'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:347:in `each'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:347:in `call'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
C:/Ruby/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:60:in `run_initializers'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.6/lib/rails/application.rb:391:in `initialize!'
C:/Redmine/redmine-entwicklung-trunk/config/environment.rb:16:in `<top (required)>'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.6/lib/rails/application.rb:367:in `require_environment!'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.4.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
C:/Ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
C:/Ruby/Ruby31-x64/bin/rake:33:in `load'
C:/Ruby/Ruby31-x64/bin/rake:33:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

That left me stranded, any help is appreciated here! Thanks in advance!

**Comment by picman** [comment]
So, the main problem was in Rails 6, that is required in the trunk now. I had to modify the source codes a lot  in order to be compatible with Rails 6. I've created a new branch `rails6`. Could you test this branch in your environment, please?

**Comment by deining** [comment]
> Could you test this branch in your environment, please?

I cloned the branch `rails6` into my `plugins` folder. Afterwards, I could successfully migrate the `redmine_dmsf` plugin. At a first glance, everything seems to be o.k.
Thanks a lot for your work, I really appreciate that!
