### ISSUE TITLE
Internal Error while opening settings

### ISSUE THREAD

**Issue by thejulian** [danmunn/redmine_dmsf#1350]
Internal Error when clicking Settings.

production.log

```
2022-05-02T12:46:34.831970906Z I, [2022-05-02T12:46:34.831619 #1]  INFO -- : Completed 500 Internal Server Error in 16ms (ActiveRecord: 2.5ms | Allocations: 11323)
2022-05-02T12:46:34.886013422Z F, [2022-05-02T12:46:34.883488 #1] FATAL -- :   
2022-05-02T12:46:34.886072701Z SystemStackError (stack level too deep):
2022-05-02T12:46:34.886081662Z   
2022-05-02T12:46:34.886086072Z plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'
2022-05-02T12:46:34.886092937Z plugins/redmine_products/lib/redmine_products/patches/notifiable_patch.rb:35:in `all_with_products'
2022-05-02T12:46:34.886101021Z plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'
2022-05-02T12:46:34.886110014Z plugins/redmine_products/lib/redmine_products/patches/notifiable_patch.rb:35:in `all_with_products'
2022-05-02T12:46:34.886120393Z plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'
2022-05-02T12:46:34.886125473Z plugins/redmine_products/lib/redmine_products/patches/notifiable_patch.rb:35:in `all_with_products'
2022-05-02T12:46:34.886129557Z plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'
2022-05-02T12:46:34.886133613Z plugins/redmine_products/lib/redmine_products/patches/notifiable_patch.rb:35:in `all_with_products'
2022-05-02T12:46:34.886137481Z plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'
2022-05-02T12:46:34.886141391Z plugins/redmine_products/lib/redmine_products/patches/notifiable_patch.rb:35:in `all_with_products'
REPEATS ITSELF THOUSENDS OF LINES
2022-05-02T12:46:34.946919215Z plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'
2022-05-02T12:46:34.946922970Z plugins/redmine_products/lib/redmine_products/patches/notifiable_patch.rb:35:in `all_with_products'
2022-05-02T12:46:34.946926600Z plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'
2022-05-02T12:46:34.946930454Z app/controllers/settings_controller.rb:37:in `edit'
2022-05-02T12:46:34.946934404Z app/controllers/settings_controller.rb:32:in `index'
2022-05-02T12:46:34.946938481Z lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

When removing DMSF Plugin the settings are shown as normal => localhost:3000/settings.
Using DMSF 3.0.0.
Seems a conflict with RedmineUP Products plugin. 
For testing purpose i'm using the redmine docker image "docker pull redmine:5.0.0".

```
Environment:
  Redmine version                5.0.0.stable
  Ruby version                   3.1.2-p20 (2022-04-12) [x86_64-linux]
  Rails version                  6.1.4.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Circle (includes JavaScript)
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.4
  redmine_checklists             3.1.21
  redmine_contacts               4.3.6
  redmine_contacts_helpdesk      4.1.13
  redmine_contacts_invoices      4.2.6
  redmine_dmsf                   3.0.0
  redmine_finance                2.1.8
  redmine_people                 1.6.2
  redmine_products               2.1.5
  redmine_project_controlling    0.0.1
  redmine_spent_time             4.1.0
```

**Comment by picman** [comment]
I think that the problem is on RedmineUp side this time. They still use `alias_method` for overriding Redmine's method instead of `prepend` and consequently come into a conflict with other plugins overriding the same methods. `prepend` has been here since Ruby 2.0 and it is generally recommended approach. I have no idea how easily solve this conflict

**Comment by picman** [comment]
As a hot-fix you can comment out the `all` function either in dmsf or in products plugin. However, I think that this problem should be solved  by RedmineUp.

_lib/redmine_dmsf/patches/notifiable_patch.rb_

```ruby
#def all
#    notifications = super
#    notifications << Redmine::Notifiable.new('dmsf_workflow_plural')
#    notifications << Redmine::Notifiable.new('dmsf_legacy_notifications')
#    notifications
#end
```

**Comment by picman** [comment]
A better workaround as the hot fix above was implemented in the scope of #1354. If you could test the _devel_ branch and provide me a feedback, it would be great.

**Comment by thejulian** [comment]
Hi,

I can confirm that settings are now working with devel-3.0.1.
BTW: devel-3.0.1 did not get the version bump yet, but devel-3.0.1 branch is installed and no error is shown opening settings.

```
Environment:
  Redmine version                5.0.0.stable
  Ruby version                   3.1.2-p20 (2022-04-12) [x86_64-linux]
  Rails version                  6.1.4.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Circle (includes JavaScript)
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.4
  redmine_checklists             3.1.21
  redmine_contacts               4.3.6
  redmine_contacts_helpdesk      4.1.13
  redmine_contacts_invoices      4.2.6
  redmine_dmsf                   3.0.0
  redmine_people                 1.6.2
  redmine_products               2.1.5
  redmine_spent_time             4.1.0
```

**Comment by picman** [comment]
Okay. Thank you. I will release this version soon.
