### ISSUE TITLE
Error while loading /settings

### ISSUE THREAD

**Issue by lajaunie** [danmunn/redmine_dmsf#1364]
hello,
i have just update DMSF to latest version (3.0.1) and i'm facing to this bug.
```
Started GET "/settings" for 10.xxx.yyy.zzz at 2022-06-07 13:23:28 +0200
Processing by SettingsController#index as HTML
  Current user: ZZZZZZ (id=XX)
Completed 500 Internal Server Error in 22ms (ActiveRecord: 7.3ms)
  
SystemStackError (stack level too deep):
  
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:41:in `all'
plugins/redmine_questions/lib/redmine_questions/patches/notifiable_patch.rb:36:in `all_with_questions'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:41:in `all'
plugins/redmine_questions/lib/redmine_questions/patches/notifiable_patch.rb:36:in `all_with_questions'
...
11800 lines
...
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:41:in `all'
plugins/redmine_questions/lib/redmine_questions/patches/notifiable_patch.rb:36:in `all_with_questions'
```
It seem to have some negative interaction with plugin Redmine Q&A plugin (PRO version)

My Redmine Informations:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
```
Environment:
  Redmine version                4.2.5.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.6.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  redmine_aca_macros             0.0.3
  redmine_agile                  1.6.4
  redmine_callout_macro          1.0.0
  redmine_checklists             3.1.21
  redmine_dmsf                   3.0.1
  redmine_drawio                 1.4.0
  redmine_gitlab_hook            4.0.0
  redmine_image_clipboard_paste  3.3.0
  redmine_knowledgebase          3.3.1
  redmine_mermaid_macro          1.0.0
  redmine_questions              1.0.3
  redmine_reporter               2.0.2
  redmine_scmacros               0.0.3
  redmine_theme_changer          0.4.0
  redmineup_tags                 2.0.12
```

Regards.

**Comment by picman** [comment]
Fixed.

**Comment by lajaunie** [comment]
hello,
thank you for your outstanding time of reaction.

I have try your patch and this correction introduce a new failure:
```
Completed 200 OK in 1311ms (Views: 108.9ms | ActiveRecord: 19.1ms)
Started GET "/settings" for 10.xxx.yyy.zzz at 2022-06-07 14:29:20 +0200
Processing by SettingsController#index as HTML
  Current user: zzzzzz (id=3)
Completed 500 Internal Server Error in 24ms (ActiveRecord: 4.5ms)
  
SystemStackError (stack level too deep):
  
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:41:in `all'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:41:in `all'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:41:in `all'
...
10000+ line
...
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:41:in `all'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:41:in `all'

```

regards

**Comment by picman** [comment]
That's strange. Have you restarted the application? The correction should cause that the `all` method from _plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb_ will never be called. However, in your environment, the patch is applied despite the fact that _redmine_questions_ plugin is installed.
```ruby
# Apply the patch
if Redmine::Plugin.installed?(:easy_extensions)
  RedmineExtensions::PatchManager.register_patch_to_be_first 'Redmine::Notifiable',
    'RedmineDmsf::Patches::NotifiablePatch', prepend: true, first: true
elsif !(Redmine::Plugin.installed?(:redmine_contacts) || Redmine::Plugin.installed?(:redmine_questions))
  Redmine::Notifiable.prepend RedmineDmsf::Patches::NotifiablePatch
end
```

**Comment by lajaunie** [comment]
Yes, i have restarted Nginx and there are no errors in nginx logs.
For information, the plugin redmine_questions was installed before this update and it had no interactions.
I do not help much because i'm not ruby coder.
Is there any tests i can run to help you ?

**Comment by picman** [comment]
Try it now.

**Comment by picman** [comment]
And if you delete the file _plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb_?

**Comment by picman** [comment]
Isn't in the log a bit more information? Especially from where is the missing file called?

**Comment by picman** [comment]
Could I ask yo for one more test?

**Comment by lajaunie** [comment]
hello,
yes with pleasure

**Comment by picman** [comment]
Does it work?

**Comment by picman** [comment]
Great!
