### ISSUE TITLE
Install failes - Uninstall failes

### ISSUE THREAD

**Issue by teatower** [danmunn/redmine_dmsf#1367]
`bundle exec rake db:migrate` --> successfull
`RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf` --> fails witih
> /var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
> Caused by:
> ActiveRecord::StatementInvalid: Mysql2::Error: Duplicate column name 'external_url'

`rake redmine:plugins:migrate NAME=redmine_dmsf VERSION=0 RAILS_ENV=production` --> fails witih

> == 20141015132701 RemoveFolderFromRevision: reverting =========================
-- add_column(:dmsf_file_revisions, :dmsf_folder_id, :integer, {:null=>true})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
Mysql2::Error: Duplicate column name 'dmsf_folder_id'

Now I am stuck in between the worlds and do not know what to do?
Restore installation from backup?

Thank you for your time and efforts. I won't got with this installation without redmine_dmsf !

**Comment by picman** [comment]
I'd manually remove _dmsf_folder_id_ column and call the rake command again. In case of next errors I'd proceed with similar approach. BTW, from which version to which version of DMSF do you migrate?
```sql
alter table dmsf_file_revision drop column dmsf_folder_id;
```

**Comment by picman** [comment]
The migrations are run one after another for each version. It doesn't mater whether you upgrade 4.2.3->5.0.1 or 4.2.3->4.2.6->5.0.1. The migration and rollbacks are regularly tested. I think, you do something wrong. The code `add_column :dmsf_file_revisions, :dmsf_folder_id, :integer, null: true` is called in `RemoveFolderFromRevision::down`. It means it's called only in case of `rake redmine:plugins:migrate NAME=redmine_dmsf VERSION=0 RAILS_ENV=production` that is call when we want to uninstall the plugin.

You should do the upgrade as follows:

1. Update Redmine's source codes.
2. Update your plugins' source codes.
3. Migrate the application
3.1 `bundle install`
3.2 `bundle exec rake generate_secret_token`
3.3 `bundle update`
3.4 `bundle exec rake db:migrate RAILS_ENV=production `
3.5 `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`
3.6 `bundle exec rake tmp:cache:clear RAILS_ENV=production`
4. Restart the application.

If you check _db/20141015132701_remove_folder_from_revision.rb_, the method `up` contains just `remove_column`.

**Comment by teatower** [comment]
Karel, again THANK YOU.
I have done everything from scratch, strictly following your list above, and I succeded.
Some plugins do not have adpoted versions für redmine 5.x, so they raise fatal errors, resulting in not bringing up any webpage. Removing them one-by-one solved the problem.

But, and I thought converting this to a searate ticket, a new problem associated with dmsf turned up:
The system runs perfectly well, but trying to access the config-pages of dmsf results in an 'internal error'.
Log shows:
```
[2022-06-14T11:59:01.822187 #785323] FATAL -- : [99583]
[99583] ActionView::Template::Error (missing interpolation argument :value in "LibreOffice's command line binary '%{value}' not available" ({:count=>nil} given)):
[99583]     85:   <%= text_field_tag 'settings[office_bin]', @settings['office_bin'], size: 10 %>
[99583]     86:   <% unless RedmineDmsf::Preview.office_available? %>
[99583]     87:     <span class="icon icon-warning">
[99583]     88:       <small><%= l(:note_dmsf_office_bin_not_available, @settings['office_bin']) %></small>
[99583]     89:     </span>
[99583]     90:   <% end %>
[99583]     91:   <em class="info">
[99583]
[99583] lib/redmine/i18n.rb:38:in 'l'
[99583] plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb:88
[99583] app/views/settings/plugin.html.erb:6
[99583] app/views/settings/plugin.html.erb:4
[99583] lib/redmine/sudo_mode.rb:61:in 'sudo_mode'
 
```
What to do know?
Thank's and kind regards!

**Comment by teatower** [comment]
Great and Thank you again!

**Comment by teatower** [comment]
Hi,
thank you very much for the new version. Installation worked perfectly well in one go. Great.
Configuration page is now editable, but when I want to access the acutal dmsf tool within a project I get

I, [2022-06-19T16:44:18.152874 #1126257]  INFO -- : [daf2673b] Started GET "/projects/test1/settings/dmsf" for 10.6.2.82 at 2022-06-19 16:44:18 +0200
I, [2022-06-19T16:44:18.153525 #1126257]  INFO -- : [daf2673b] Processing by ProjectsController#settings as HTML
I, [2022-06-19T16:44:18.153566 #1126257]  INFO -- : [daf2673b]   Parameters: {"id"=>"test1", "tab"=>"dmsf"}
I, [2022-06-19T16:44:18.156671 #1126257]  INFO -- : [daf2673b]   Current user: xy1 (id=69)
I, [2022-06-19T16:44:18.224684 #1126257]  INFO -- : [daf2673b]   Rendered projects/settings.html.erb within layouts/base (Duration: 62.3ms | Allocations: 37632)
I, [2022-06-19T16:44:18.249680 #1126257]  INFO -- : [daf2673b]   Rendered layout layouts/base.html.erb (Duration: 87.4ms | Allocations: 56088)
I, [2022-06-19T16:44:18.249954 #1126257]  INFO -- : [daf2673b] Completed 200 OK in 96ms (Views: 76.7ms | ActiveRecord: 13.2ms | Allocations: 59229)
I, [2022-06-19T16:46:26.026022 #1126257]  INFO -- : [d17173dc] Started GET "/projects/test1/dmsf" for 10.6.2.82 at 2022-06-19 16:46:26 +0200
I, [2022-06-19T16:46:26.027084 #1126257]  INFO -- : [d17173dc] Processing by DmsfController#show as HTML
I, [2022-06-19T16:46:26.027131 #1126257]  INFO -- : [d17173dc]   Parameters: {"id"=>"test1"}
I, [2022-06-19T16:46:26.036410 #1126257]  INFO -- : [d17173dc]   Current user: xy1 (id=69)
I, [2022-06-19T16:46:26.047723 #1126257]  INFO -- : [d17173dc] **Completed 500 Internal Server Error in 21ms (ActiveRecord: 7.9ms | Allocations: 5269)
F, [2022-06-19T16:46:26.048123 #1126257] FATAL -- : [d17173dc]
[d17173dc] Query::StatementInvalid (Mysql2::Error: Illegal mix of collations for operation 'UNION'):
[d17173dc]**
[d17173dc] plugins/redmine_dmsf/app/models/dmsf_query.rb:101:in 'rescue in dmsf_count'
[d17173dc] plugins/redmine_dmsf/app/models/dmsf_query.rb:98:in 'dmsf_count'
[d17173dc] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:94:in 'block (2 levels) in show'
[d17173dc] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:92:in 'show'
[d17173dc] lib/redmine/sudo_mode.rb:61:in 'sudo_mode'

sorry for bothering again :=

Cheers, teatower

**Comment by picman** [comment]
Duplicates #1276.
Check colation of tables in your database in the following tables: dmsf_folders, dmsf_files, dmsf_links, dmsf_file_revisons and dmsf_project. e.g:
```sql
show create table dmsf_folders;
...
DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
...
```
This value must be equal for all tables;

**Comment by teatower** [comment]
**Thank you very much** and shame on me that I addressed the same problem twice. 
Wonder why could it happen again in a fresh redmine installation?

Anyway, I did what you suggested and now I have it up and running. Great!
One last thing ... ;-)
Clicking on DMS in the top menu bar of redmine throws up an similar error and I can not find out in which tables I have to make changes, 

> I, [2022-06-21T02]  INFO -- : [d5421cdd] Started GET "/dmsf" for 10.6.2.182 at 2022-06-21 08:16:25 +0200
> I, [2022-06-21T02]  INFO -- : [d5421cdd] Processing by DmsfController#index as HTML
> I, [2022-06-21T02]  INFO -- : [d5421cdd]   Current user: xyz (id=69)
> I, [2022-06-21T02]  INFO -- : [d5421cdd] Completed 500 Internal Server Error in 65ms (ActiveRecord: 32.3ms | Allocations: 18310)
> F, [2022-06-21T02] FATAL -- : [d5421cdd]
> [d5421cdd] Query::StatementInvalid (Mysql2::Error: Illegal mix of collations for operation 'UNION'):
> [d5421cdd] plugins/redmine_dmsf/app/models/dmsf_query.rb:101:in 'rescue in dmsf_count'
> [d5421cdd] plugins/redmine_dmsf/app/models/dmsf_query.rb:98:in 'dmsf_count'
> [d5421cdd] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:94:in 'block (2 levels) in show'
> [d5421cdd] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:92:in 'show'
> [d5421cdd] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:74:in 'index'
> [d5421cdd] lib/redmine/sudo_mode.rb:61:in 'sudo_mode'
> 

Most other (radomly inspected) tables from the redmine core do not have colations at all.

Many thanks! teatower

**Comment by picman** [comment]
How have you created the database? Have you followed the installation instruction from redmine.org?
```sql
CREATE DATABASE redmine CHARACTER SET utf8mb4;
```

Take a look here:

https://github.com/danmunn/redmine_dmsf/issues/1116#issuecomment-625777482

**Comment by teatower** [comment]
Seems that finally everything works well.
Converted all tables in database using the script provided by @ahorek at
https://github.com/danmunn/redmine_dmsf/issues/1116#issuecomment-625777482

Thank's a lot to @picman and @ahorek ! :1st_place_medal:
