### ISSUE TITLE
Custom queries and Trash bin

### ISSUE THREAD

**Issue by hibit-2709** [danmunn/redmine_dmsf#1380]
We look at the list of files in the DMS module.
After enabling some Custom query for custom field, and then selecting _Trash bin_, Redmine generates _Internal error_.

**Comment by picman** [comment]
Please provide more details (which custom query, which custom fields, plugin's version) and the corresponding part of _production.log_.

**Comment by hibit-2709** [comment]
DMSF version 2.4.11, Redmine 4.2.3.stable
Custom fileds -> DMS -> xxx type Text with Text formating enabled.
We placed in this cf number of issue in format '#00000'.
We looked at files without defined issue with Custom query: cf xxx Starts with #

Related log:
Started GET "/projects/s003082/dmsf/trash" for 127.0.0.1 at 2022-07-11 08:41:39 +0200
Processing by DmsfController#trash as HTML
  Parameters: {"id"=>"s003082"}
  Current user: admin_xxx (id=1)
Completed 500 Internal Server Error in 28ms (ActiveRecord: 13.5ms)
  
NoMethodError (undefined method `[]' for nil:NilClass):
  
app/models/query.rb:1126:in `sql_for_custom_field'
plugins/redmine_dmsf/app/models/dmsf_query.rb:132:in `block in statement'
plugins/redmine_dmsf/app/models/dmsf_query.rb:118:in `each_key'
plugins/redmine_dmsf/app/models/dmsf_query.rb:118:in `statement'
plugins/redmine_dmsf/app/models/dmsf_query.rb:301:in `dmsf_folders_scope'
plugins/redmine_dmsf/app/models/dmsf_query.rb:90:in `base_scope'
plugins/redmine_dmsf/app/models/dmsf_query.rb:98:in `dmsf_count'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:125:in `block (2 levels) in trash'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:123:in `trash'

**Comment by picman** [comment]
Fixed. Thank you for reporting that.
