### ISSUE TITLE
Open 'watched' folder throw internal error

### ISSUE THREAD

**Issue by inpos** [danmunn/redmine_dmsf#1399]
Hi!
Trying to open 'watched' folder raises internal error.
```
App 413435 stdout:   
App 413435 stdout: ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
App 413435 stdout:     10: 
App 413435 stdout:     11: <h3><%= l(:"label_#{watched_klass_name}_watchers") %> (<%= watched.watcher_users.size %>)</h3>
App 413435 stdout:     12: 
App 413435 stdout:     13: <%= watchers_list(watched) %>
App 413435 stdout:   
App 413435 stdout: plugins/redmine_dmsf/app/models/dmsf_folder.rb:102:in `visible?'
App 413435 stdout: app/helpers/watchers_helper.rb:55:in `block in watchers_list'
App 413435 stdout: app/helpers/watchers_helper.rb:51:in `collect'
App 413435 stdout: app/helpers/watchers_helper.rb:51:in `watchers_list'
App 413435 stdout: app/views/watchers/_watchers.html.erb:13:in `_app_views_watchers__watchers_html_erb__2344757294435805686_279760'
App 413435 stdout: plugins/redmine_dmsf/app/views/dmsf/_main.html.erb:101:in `block in _plugins_redmine_dmsf_app_views_dmsf__main_html_erb__965795372059027211_276160'
App 413435 stdout: plugins/redmine_dmsf/app/views/dmsf/_main.html.erb:94:in `_plugins_redmine_dmsf_app_views_dmsf__main_html_erb__965795372059027211_276160'
App 413435 stdout: plugins/redmine_dmsf/app/views/dmsf/show.html.erb:25:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb__4141225572855874988_276140'
App 413435 stdout: plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:96:in `block (2 levels) in show'
App 413435 stdout: plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:92:in `show'
App 413435 stdout: lib/redmine/sudo_mode.rb:61:in `sudo_mode'
App 413435 stdout: plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
```

[Here](https://user-images.githubusercontent.com/9678149/187487431-ed1e7848-fc67-4e01-ad19-53930b1f339b.mp4) is screencast

**Comment by picman** [comment]
Fixed.

**Comment by inpos** [comment]
Confirm. Thanks
