### ISSUE TITLE
Rake aborted on upgrade from Redmine 3.3 to Redmine 4.2 

### ISSUE THREAD

**Issue by mtolava** [danmunn/redmine_dmsf#1403]
I just upgrading my Redmine version and I have some plugin install too, like redmine_agile and redhopper.
I make the same test with ruby 2.6.6 and ruby 2.7.2 and I have the same problem
When I run migrations 
`RAILS_ENV=production rake redmine:plugins:migrate`

I receive this message on my console
```
rake aborted!
Psych::DisallowedClass: Tried to load unspecified class: ActionController::Parameters
/home/user/Development/i4development/releases/redmine-4.2/app/models/setting.rb:108:in `value'
/home/user/Development/i4development/releases/redmine-4.2/app/models/setting.rb:122:in `[]'
/home/user/Development/i4development/releases/redmine-4.2/app/models/setting.rb:309:in `plugin_redmine_dmsf'
/home/user/Development/i4development/shared/plugins/redmine_dmsf/after_init.rb:46:in `dmsf_init'
/home/user/Development/i4development/shared/plugins/redmine_dmsf/after_init.rb:125:in `<top (required)>'
/home/user/Development/i4development/releases/redmine-4.2/plugins/redmine_dmsf/init.rb:66:in `require_relative'
/home/user/Development/i4development/releases/redmine-4.2/plugins/redmine_dmsf/init.rb:66:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
/home/user/Development/i4development/releases/redmine-4.2/lib/redmine/plugin.rb:187:in `block in load'
/home/user/Development/i4development/releases/redmine-4.2/lib/redmine/plugin.rb:178:in `each'
/home/user/Development/i4development/releases/redmine-4.2/lib/redmine/plugin.rb:178:in `load'
/home/user/Development/i4development/releases/redmine-4.2/config/initializers/30-redmine.rb:20:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:285:in `load'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:285:in `block in load'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:285:in `load'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:170:in `instrument'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/engine.rb:662:in `load_config_initializer'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/engine.rb:619:in `each'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `instance_exec'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `run'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/initializable.rb:50:in `each'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/initializable.rb:60:in `run_initializers'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/application.rb:361:in `initialize!'
/home/user/Development/i4development/releases/redmine-4.2/config/environment.rb:16:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/application.rb:337:in `require'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/application.rb:337:in `require_environment!'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/railties-5.2.8.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/bin/ruby_executable_hooks:22:in `eval'
/home/user/.rvm/gems/ruby-2.7.2@i4development-4.2/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

_Another comment_
I prove with master, 3.0.6 branches, following some specifications on documentation but anyway.. it fails
I didn't found any idea how to resolve it, can anybody help me?

**Comment by picman** [comment]
See https://www.redmineup.com/pages/help/troubleshooting/psych-disallowed-class-fix. I would add the suggested configuration into _config/additional_environment.rb_.
