### ISSUE TITLE
Error on "New step or New Approver"

### ISSUE THREAD

**Issue by B5JohnSheridan** [danmunn/redmine_dmsf#1407]
Greetings,

thanks for this very cool plugin! Unfortunately, I ran across a problem where I cannot see the solution...

I use a fresh install of Redmine 5.0.2 with redmine_dmsf 3.0.6 and are not able to add any steps or approvers. I can create Approval workflows, but nothing happens when I click on "New step or New Approver". The error.log shows however:

```
Started GET "/dmsf_workflows/4/new_step" for 192.168.0.1 at 2022-10-21 21:27:14 +0000
Processing by DmsfWorkflowsController#new_step as JS
  Parameters: {"id"=>"4"}
  Current user: jon.doe (id=10)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/new_step.js.erb (Duration: 6.3ms | Allocations: 1885)
Completed 500 Internal Server Error in 18ms (ActiveRecord: 4.8ms | Allocations: 5099)

ActionView::Template::Error (PG::GroupingError: ERROR:  column "dmsf_workflow_steps.operator" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ..."step" ORDER BY "dmsf_workflow_steps"."step" ASC, "dmsf_work...
                                                             ^
):
    34:
    35:   <fieldset class="box">
    36:     <legend><%= l(:label_dmsf_workflow_step) %></legend>
    37:     <%= select_tag 'step', dmsf_workflow_steps_options_for_select(@steps),
    38:                    id: 'selected_step', onchange: "$('#dmsf_step_name').toggle(this.value == 0);", style: 'max-width: 40%' %>
    39:     <span id="dmsf_step_name">&nbsp;
    40:       <%= label_tag 'name', l(:field_name) %>

plugins/redmine_dmsf/app/helpers/dmsf_workflows_helper.rb:54:in `dmsf_workflow_steps_options_for_select'
plugins/redmine_dmsf/app/views/dmsf_workflows/_new_step_modal.html.erb:37
app/helpers/application_helper.rb:1483:in `labelled_form_for'
plugins/redmine_dmsf/app/views/dmsf_workflows/_new_step_modal.html.erb:25
plugins/redmine_dmsf/app/views/dmsf_workflows/new_step.js.erb:22
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
```

As everything else with the DMS and Redmine seems to work, I ran out of ideas what could be the fault on my side. Thanks for your help!

**Comment by picman** [comment]
Fixed. Either roll back to v3.0.5 or wait for v3.0.7 relase.
