### ISSUE TITLE
Internal error while opening Settings page

### ISSUE THREAD

**Issue by shreyarajwade** [danmunn/redmine_dmsf#1424]
I am getting an Internal error while opening the Settings page. I am working on redmine v5.0.4. I had previously used the hotfix you had provided for older versions of redmine for this error - https://github.com/danmunn/redmine_dmsf/issues/1350. But even after applying the hotfix in `lib/redmine_dmsf/patches/notifiable_patch.rb` as directed, the error still occurs.

production.log
```
Completed 500 Internal Server Error in 153ms (ActiveRecord: 2.7ms | Allocations: 12744)
F, [2023-01-25T22:49:40.739652 #16484] FATAL -- : [fd49b4d2-cf1f-4fe3-a834-fe4ee128e4e7]   
[fd49b4d2-cf1f-4fe3-a834-fe4ee128e4e7] SystemStackError (stack level too deep):
[fd49b4d2-cf1f-4fe3-a834-fe4ee128e4e7]   
[fd49b4d2-cf1f-4fe3-a834-fe4ee128e4e7] plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
[fd49b4d2-cf1f-4fe3-a834-fe4ee128e4e7] plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
[fd49b4d2-cf1f-4fe3-a834-fe4ee128e4e7] plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
.
.
.
.
.
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
[19ed403b-7af3-4470-9781-305ff068d698] 
plugins/redmine_resources/lib/redmine_resources/patches/notifiable_patch.rb:37:in `all_with_resources'
[19ed403b-7af3-4470-9781-305ff068d698] app/controllers/settings_controller.rb:37:in `edit'
[19ed403b-7af3-4470-9781-305ff068d698] app/controllers/settings_controller.rb:32:in `index'
[19ed403b-7af3-4470-9781-305ff068d698] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

Here's additional information about the environment for reference:
```
Environment:
  Redmine version                5.0.4.stable
  Ruby version                   3.0.5-p211 (2022-11-24) [x86_64-linux]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Zenmine-200
SCM:
  Subversion                     1.14.2
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  periodictask                   4.1.0
  redmine_agile                  1.6.4
  redmine_checklists             3.1.22
  redmine_cms                    1.2.4
  redmine_dmsf                   3.0.7
  redmine_mentions               0.0.1
  redmine_people                 1.6.2
  redmine_resources              1.0.8
  redmine_wktime                 4.6
```

**Comment by picman** [comment]
Could you test the *devel* branch?

**Comment by shreyarajwade** [comment]
I tested the devel branch but it did not fix the settings page error. So, based on the error log provided above in [this](https://github.com/danmunn/redmine_dmsf/issues/1424) issue, I made changes in **one additional file**, **along with your hotfix** in [#1350](https://github.com/danmunn/redmine_dmsf/issues/1350). These changes fixed the settings page Internal error for me. 

Following are the changes that I made in file - 

lib/redmine_dmsf/patches/notifiable_ru_patch.rb

commented the alias_methods `:all, :all_with_resources_dmsf` and
the function - `all_with_resources_dmsf`
since the error log above gives error about `all_with_resources_dmsf` method

```
      def self.included(base)
        base.extend ClassMethods
        base.class_eval do
          unloadable
          class << self
            alias_method :all_without_resources_dmsf, :all
            # alias_method :all, :all_with_resources_dmsf
          end
        end
      end

      module ClassMethods

        # def all_with_resources_dmsf
        #   notifications = all_without_resources_dmsf
        #   notifications << Redmine::Notifiable.new('dmsf_workflow_plural')
        #   notifications << Redmine::Notifiable.new('dmsf_legacy_notifications')
        #   notifications
        # end

      end
```

**Comment by picman** [comment]
Could you test the _devel_ branch again without your fix and post what is in the _production.log_, please?

**Comment by picman** [comment]
According to your first log it seems that the conflict is width _redmine_resource_ plugin. So, downloaded it and test it with the _devel_ branch and it worked. Maybe, there is a conflict with another of your plugins too. We would see it from your log.

**Comment by picman** [comment]
No feedback -> closing.

**Comment by picman** [comment]
Redmine finance added among obsolete plugins. Fixed. You can test the _devel_ branch.
