### ISSUE TITLE
FrozenError on rake migrate

### ISSUE THREAD

**Issue by vali-um** [danmunn/redmine_dmsf#1427]
Unfortunately we are not able to run migrations for redmine_dmsf after upgrading to redmine 5.0.4 from 4.0.7 and redmine_dmsf to 3.0.8/3.0.9 from 2.4.1.

Redmine runs on a Debian/bullseye System with redmine installed from bullseye-backports (recently upgraded from buster).

Thanks for your help.

### Environment (the plugin needs to be removed in order to be able to run bin/about):
```
Environment:
  Redmine version                5.0.4.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
```

### Stack trace:
```
$ rake redmine:plugins:migrate NAME=redmine_dmsf --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
FrozenError: can't modify frozen Array: ["/usr/share/redmine/app/controllers", "/usr/share/redmine/app/helpers", "/usr/share/redmine/app/models", "/usr/share/redmine/app/validators"]
/usr/share/redmine/plugins/redmine_dmsf/after_init.rb:26:in `<top (required)>'
/usr/share/redmine/plugins/redmine_dmsf/init.rb:67:in `require_relative'
/usr/share/redmine/plugins/redmine_dmsf/init.rb:67:in `<top (required)>'
/usr/share/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/usr/share/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/usr/share/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/usr/share/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
/usr/share/rubygems-integration/all/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/usr/share/rubygems-integration/all/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/rubygems-integration/all/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
/usr/share/rubygems-integration/all/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
/usr/share/rubygems-integration/all/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/rubygems-integration/all/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
/usr/share/redmine/config/environment.rb:16:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/zeitwerk/kernel.rb:34:in `require'
/usr/lib/ruby/vendor_ruby/zeitwerk/kernel.rb:34:in `require'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/usr/share/rubygems-integration/all/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
/usr/share/rubygems-integration/all/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by picman** [comment]
Unfortunately, from the error output is not clear where could be the problem. An upgrade from 2.4.1 is quite a big step. the version is three years old. I'd personally go the way of upgrading DMSF step by step, e.g.: 2.4.1 -> 2.4.11 -> 3.0.0 -> 3.0.9. Maybe, this way we will identify the problem in a particular version.

**Comment by vali-um** [comment]
Thank you for that recommendation but unfortunately we can't downgrade redmine (now at 5.0.4) and therefore we can't use a dmsf version under 3.0.0.

We are working on the issue and trying to figure out if there is anything wrong with our database or if there are some incompatible gem versions in the debian packages we use (installed from bullseye-backports) compared to installing them with bundler from rubygems.org.

We would appreciate it if you've got any suggestions on how to get more meaningful error message to help us find the root cause of this.

**Comment by vali-um** [comment]
It turned out to be an error on our side. after_init.rb was not replaced with the new version on the system for some reason.

Sorry to bother you and thanks for your help.
