### ISSUE TITLE
Error when opening Setting page 

### ISSUE THREAD

**Issue by mtolava** [danmunn/redmine_dmsf#1439]
I check the latest close issues and saw there is recurrent problem, I resolve this using the version v3.0.1. 
My configuration is:
Environment:
  Redmine version 5.0.5.stable.22130
  Ruby version       3.1.0-p0 (2021-12-25) [x86_64-linux]
  Rails version       6.1.7.2
  Environment        production
  Database adapter               Mysql2
Redmine plugins:
  redmine_agile                  1.6.5
  redmine_checklists             3.1.22
  redmine_dmsf                   3.0.1
  redmineup_tags                 2.0.13

I test the version v3.0.11, v3.0.8 and master and it fail with the same action.

```
Started GET "/settings" for 186.12.224.107 at 2023-03-20 16:21:14 -0300
INFO -- : [ca5819ab-bf1a-44ca-b51e-37a523dc6b93] Processing by SettingsController#index as HTML
INFO -- : [ca5819ab-bf1a-44ca-b51e-37a523dc6b93]   Current user: mtolava (id=5)
INFO -- : [ca5819ab-bf1a-44ca-b51e-37a523dc6b93] Completed 500 Internal Server Error in 19ms (ActiveRecord: 3.1ms | Allocations: 11196)
F, [2023-03-20T16:21:14.643780 #273450] FATAL -- : [ca5819ab-bf1a-44ca-b51e-37a523dc6b93]   
[ca5819ab-bf1a-44ca-b51e-37a523dc6b93] SystemStackError (stack level too deep):
[ca5819ab-bf1a-44ca-b51e-37a523dc6b93]   
[ca5819ab-bf1a-44ca-b51e-37a523dc6b93] plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
.
.
.
```

**Comment by picman** [comment]
I cannot reproduce it. It works fine in all your installed plugins in my environment. Cannot you see in the log what is causing the loop. Which function calls which?

**Comment by mtolava** [comment]
Testing with version v3.0.2 and v3.0.3 works, but when I testt v3.0.4 it fails
Copying the log:

```
INFO -- : [ba2cf83d-b779-445f-8d17-97fc0351bd07] Started GET "/settings" for 200.XXX.139.238 at 2023-03-22 09:14:25 -0300
I, [2023-03-22T09:14:25.992151 #337812]  INFO -- : [ba2cf83d-b779-445f-8d17-97fc0351bd07] Processing by SettingsController#index as HTML
I, [2023-03-22T09:14:26.001630 #337812]  INFO -- : [ba2cf83d-b779-445f-8d17-97fc0351bd07]   Current user: mtolava (id=5)
I, [2023-03-22T09:14:26.013732 #337812]  INFO -- : [ba2cf83d-b779-445f-8d17-97fc0351bd07] Completed 500 Internal Server Error in 21ms (ActiveRecord: 1.8ms | Allocations: 11427)
F, [2023-03-22T09:14:26.059654 #337812] FATAL -- : [ba2cf83d-b779-445f-8d17-97fc0351bd07]   
[ba2cf83d-b779-445f-8d17-97fc0351bd07] SystemStackError (stack level too deep):
.
.
.

[ba2cf83d-b779-445f-8d17-97fc0351bd07] plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_ru_patch.rb:43:in `all_with_resources_dmsf'
[9c981f5f-0713-43fc-9796-0673ba100fca] app/controllers/settings_controller.rb:37:in `edit'
[9c981f5f-0713-43fc-9796-0673ba100fca] app/controllers/settings_controller.rb:32:in `index'
[9c981f5f-0713-43fc-9796-0673ba100fca] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
[9c981f5f-0713-43fc-9796-0673ba100fca] plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
```

**Comment by mtolava** [comment]
Thank you very much for your help, I attentive to what can help

**Comment by picman** [comment]
I see the problem now. In the current version of _redmine_checklist_ plugin, they override _Notifiable_ class not any more. So, update your devel branch an try it now.
