### ISSUE TITLE
bug: Allow access only to xxx group , access Internal error 500

### ISSUE THREAD

**Issue by ritech** [danmunn/redmine_dmsf#1499]
When I give a specific user group access to the newly created folder through the administrator, I log in as a user of the specific user group and access this folder, and an Internal error is prompted.

**Comment by ritech** [comment]
my redmine version 5.1.1

**Comment by ritech** [comment]
i check databases dmsf_folders;  dmsf_folder_id all null ,what happen?
 3 |         16 |           NULL | 123123             |             |            0 |       1 | 2023-12-24 09:06:02 | 2023-12-24 09:08:18 |       1 |                  1 |      0 |
|  4 |         13 |           NULL | 1111111            |             |            0 |       5 | 2023-12-24 09:07:54 | 2023-12-24 09:27:24 |       1 |                  5 |      0 |
|  5 |         13 |           NULL | 1111111            |             |            0 |       5 | 2023-12-24 09:31:51 | 2023-12-24 09:36:58 |       1 |                  5 |      0 |
|  6 |         13 |           NULL | 123                |             |            0 |       7 | 2023-12-24 09:37:13 | 2023-12-24 09:38:59 |       1 |                  1 |      0 |
|  7 |         13 |           NULL | 1111111223         |             |            0 |       5 | 2023-12-24 09:39:37 | 2023-12-24 09:42:00 |       1 |                  1 |      0 |
|  8 |         13 |           NULL | 1111111122         |             |            0 |       5 | 2023-12-24 09:42:34 | 2023-12-24 09:47:30 |       1 |                  5 |      0 |
|  9 |         13 |           NULL | 12312322111        |             |

**Comment by ritech** [comment]
i have update gem bundle to new version , log changed
I, [2023-12-24T19:17:59.267828 #1105]  INFO -- : [54bfb65c-88c4-4129-b53d-8815d7d7e20a]   Current user: admin (id=1)
D, [2023-12-24T19:17:59.269966 #1105] DEBUG -- : [54bfb65c-88c4-4129-b53d-8815d7d7e20a]   Project Load (0.6ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'test' LIMIT 1
D, [2023-12-24T19:17:59.272690 #1105] DEBUG -- : [54bfb65c-88c4-4129-b53d-8815d7d7e20a]   EnabledModule Pluck (0.6ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 1
D, [2023-12-24T19:17:59.275975 #1105] DEBUG -- : [54bfb65c-88c4-4129-b53d-8815d7d7e20a]   DmsfFolder Load (0.6ms)  SELECT `dmsf_folders`.* FROM `dmsf_folders` WHERE `dmsf_folders`.`id` = 1 LIMIT 1
D, [2023-12-24T19:17:59.278109 #1105] DEBUG -- : [54bfb65c-88c4-4129-b53d-8815d7d7e20a]   Project Load (0.6ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
D, [2023-12-24T19:17:59.281897 #1105] DEBUG -- : [54bfb65c-88c4-4129-b53d-8815d7d7e20a]   DmsfFolderPermission Delete All (0.5ms)  DELETE FROM `dmsf_folder_permissions` WHERE `dmsf_folder_permissions`.`dmsf_folder_id` = 1
I, [2023-12-24T19:17:59.287388 #1105]  INFO -- : [54bfb65c-88c4-4129-b53d-8815d7d7e20a] Completed 500 Internal Server Error in 30ms (ActiveRecord: 5.3ms | Allocations: 4423)
F, [2023-12-24T19:17:59.290395 #1105] FATAL -- : [54bfb65c-88c4-4129-b53d-8815d7d7e20a]
[54bfb65c-88c4-4129-b53d-8815d7d7e20a] ActiveRecord::DangerousAttributeError (object_id is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.):
[54bfb65c-88c4-4129-b53d-8815d7d7e20a]
[54bfb65c-88c4-4129-b53d-8815d7d7e20a] plugins/redmine_dmsf/app/models/dmsf_folder.rb:500:in `block in update_from_params'
[54bfb65c-88c4-4129-b53d-8815d7d7e20a] plugins/redmine_dmsf/app/models/dmsf_folder.rb:499:in `each'
[54bfb65c-88c4-4129-b53d-8815d7d7e20a] plugins/redmine_dmsf/app/models/dmsf_folder.rb:499:in `update_from_params'
[54bfb65c-88c4-4129-b53d-8815d7d7e20a] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:263:in `save'
[54bfb65c-88c4-4129-b53d-8815d7d7e20a] lib/redmine/sudo_mode.rb:78:in `sudo_mode'

**Comment by ritech** [comment]
127c127,128
<       return true if role_ids.intersect?(role_permission_ids)
---
>
>       return true if (role_ids & role_permission_ids).blank?
133c134,135
<       principal_ids.intersect?(user_group_ids)
---
>
>       (principal_ids & user_group_ids).blank?

**Comment by ritech** [comment]
fix
