### ISSUE TITLE
Non-admin user: NoMethodError for intersect if running on Ruby 2.7.6

### ISSUE THREAD

**Issue by JanCejka** [danmunn/redmine_dmsf#1500]
* Admin creates folder and gives rights for selected roles
* Users in those roles get 500 exception and cannot access DMS for that project
* If `intersect?` is replaced with `intersection` on L127 and L133 of `dmsf_folder.rb`, all works as expected

Versions:
* Ruby: 2.7.6p219 (part of turnkey-redmine-17.1-bullseye-amd64)
* Redmine: 5.0.0
* dmsf: 3.1.3

Exception:
```
I, [2024-01-06T14:31:19.810439 #1049437]  INFO -- : [18c09918-fbba-49f6-b89b-e77049764b0b] Completed 500 Internal Server Error in 37ms (ActiveRecord: 13.9ms | Allocations: 16817)
F, [2024-01-06T14:31:19.810789 #1049437] FATAL -- : [18c09918-fbba-49f6-b89b-e77049764b0b]
[18c09918-fbba-49f6-b89b-e77049764b0b] NoMethodError (undefined method `intersect?' for [3, 4, 5]:Array
Did you mean?  intersection):
[18c09918-fbba-49f6-b89b-e77049764b0b]
[18c09918-fbba-49f6-b89b-e77049764b0b] plugins/redmine_dmsf/app/models/dmsf_folder.rb:127:in `permissions?'
[18c09918-fbba-49f6-b89b-e77049764b0b] plugins/redmine_dmsf/app/models/dmsf_query.rb:216:in `block in dmsf_nodes'
[18c09918-fbba-49f6-b89b-e77049764b0b] plugins/redmine_dmsf/app/models/dmsf_query.rb:209:in `delete_if'
[18c09918-fbba-49f6-b89b-e77049764b0b] plugins/redmine_dmsf/app/models/dmsf_query.rb:209:in `dmsf_nodes'
[18c09918-fbba-49f6-b89b-e77049764b0b] plugins/redmine_dmsf/app/models/dmsf_query.rb:102:in `dmsf_count'
[18c09918-fbba-49f6-b89b-e77049764b0b] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:94:in `block (2 levels) in show'
[18c09918-fbba-49f6-b89b-e77049764b0b] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:92:in `show'
[18c09918-fbba-49f6-b89b-e77049764b0b] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by picman** [comment]
Hm, you are right. `intersect?` method has been added in Ruby 3.1. However, we should replace it with `intersection.any?` to achieve the same behaviour, I think.

**Comment by btofnc** [comment]
Thanks, I have resolved this issue.
