### ISSUE TITLE
Normal user could not access DMSF page  but administrator could

### ISSUE THREAD

**Issue by btofnc** [danmunn/redmine_dmsf#1507]
Hi there,

On my redmine web, normal user could not access dmsf page, but administrator could.  I checked the log file, it shows as follows:

```
I, [2024-02-15T10:55:24.476151 #121251]  INFO -- : [793f3161-15df-4f9b-8cfc-13234fae37ca] Started GET "/projects/line_intel/dmsf" for 172.20.0.166 at 2024-02-15 10:55:24 +0800
I, [2024-02-15T10:55:24.476848 #121251]  INFO -- : [793f3161-15df-4f9b-8cfc-13234fae37ca] Processing by DmsfController#show as HTML
I, [2024-02-15T10:55:24.476896 #121251]  INFO -- : [793f3161-15df-4f9b-8cfc-13234fae37ca]   Parameters: {"id"=>"line_intel"}
I, [2024-02-15T10:55:24.480998 #121251]  INFO -- : [793f3161-15df-4f9b-8cfc-13234fae37ca]   Current user: admin (id=1)
I, [2024-02-15T10:55:24.679793 #121251]  INFO -- : [793f3161-15df-4f9b-8cfc-13234fae37ca]   Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (Duration: 134.1ms | Allocations: 63487)
I, [2024-02-15T10:55:24.681681 #121251]  INFO -- : [793f3161-15df-4f9b-8cfc-13234fae37ca]   Rendered inline template (Duration: 0.4ms | Allocations: 194)
I, [2024-02-15T10:55:24.718344 #121251]  INFO -- : [793f3161-15df-4f9b-8cfc-13234fae37ca]   Rendered layout layouts/base.html.erb (Duration: 172.6ms | Allocations: 77124)
I, [2024-02-15T10:55:24.719355 #121251]  INFO -- : [793f3161-15df-4f9b-8cfc-13234fae37ca] Completed 200 OK in 242ms (Views: 149.2ms | ActiveRecord: 47.0ms | Allocations: 98131)
I, [2024-02-15T10:55:29.955127 #121251]  INFO -- : [ce3ab42b-44a0-4926-9444-dae26f964150] Started GET "/projects/line_intel/dmsf" for 172.20.0.166 at 2024-02-15 10:55:29 +0800
I, [2024-02-15T10:55:29.955824 #121251]  INFO -- : [ce3ab42b-44a0-4926-9444-dae26f964150] Processing by DmsfController#show as HTML
I, [2024-02-15T10:55:29.956173 #121251]  INFO -- : [ce3ab42b-44a0-4926-9444-dae26f964150]   Parameters: {"id"=>"line_intel"}
I, [2024-02-15T10:55:29.960164 #121251]  INFO -- : [ce3ab42b-44a0-4926-9444-dae26f964150]   Current user: eddiepeng (id=5)
I, [2024-02-15T10:55:30.088516 #121251]  INFO -- : [ce3ab42b-44a0-4926-9444-dae26f964150] Completed 500 Internal Server Error in 132ms (ActiveRecord: 38.6ms | Allocations: 46371)
F, [2024-02-15T10:55:30.089121 #121251] FATAL -- : [ce3ab42b-44a0-4926-9444-dae26f964150]   
[ce3ab42b-44a0-4926-9444-dae26f964150] NoMethodError (undefined method `intersect?' for [5]:Array
Did you mean?  intersection):
[ce3ab42b-44a0-4926-9444-dae26f964150]   
[ce3ab42b-44a0-4926-9444-dae26f964150] plugins/redmine_dmsf/app/models/dmsf_folder.rb:127:in `permissions?'
[ce3ab42b-44a0-4926-9444-dae26f964150] plugins/redmine_dmsf/app/models/dmsf_query.rb:216:in `block in dmsf_nodes'
[ce3ab42b-44a0-4926-9444-dae26f964150] plugins/redmine_dmsf/app/models/dmsf_query.rb:209:in `delete_if'
[ce3ab42b-44a0-4926-9444-dae26f964150] plugins/redmine_dmsf/app/models/dmsf_query.rb:209:in `dmsf_nodes'
[ce3ab42b-44a0-4926-9444-dae26f964150] plugins/redmine_dmsf/app/models/dmsf_query.rb:102:in `dmsf_count'
[ce3ab42b-44a0-4926-9444-dae26f964150] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:94:in `block (2 levels) in show'
[ce3ab42b-44a0-4926-9444-dae26f964150] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:92:in `show'
[ce3ab42b-44a0-4926-9444-dae26f964150] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

does any body know what's wrong with my setting?

**Comment by picman** [comment]
Duplicates #1500.
