### ISSUE TITLE
SystemStackError when Redmine Products plugin installed

### ISSUE THREAD

**Issue by RomanIOPSYS** [danmunn/redmine_dmsf#1537]
When Redmine Products (`redmine_products`) and Redmine CRM (`redmine_contacts`) plugins are installed, opening administrative settings fails with `SystemStackError`:

```
I, [2024-07-18T20:22:39.380403 #1]  INFO -- : Started GET "/settings" for 172.17.0.1 at 2024-07-18 20:22:39 +0000
I, [2024-07-18T20:22:39.381060 #1]  INFO -- : Processing by SettingsController#index as HTML
I, [2024-07-18T20:22:39.384106 #1]  INFO -- :   Current user: admin (id=1)
I, [2024-07-18T20:22:39.396807 #1]  INFO -- : Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.4ms | Allocations: 11130)
F, [2024-07-18T20:22:39.532960 #1] FATAL -- :
SystemStackError (stack level too deep):

plugins/redmine_products/lib/redmine_products/patches/notifiable_patch.rb:35:in `all_with_products'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:37:in `all'
<snip>
plugins/redmine_products/lib/redmine_products/patches/notifiable_patch.rb:35:in `all_with_products'
plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:37:in `all'
app/controllers/settings_controller.rb:37:in `edit'
app/controllers/settings_controller.rb:32:in `index'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

## Steps to reproduce

* Download `redmine_crm-4_4_1-light.zip` and `redmine_products-2_2_3-light.zip` from https://www.redmineup.com/

    SHA256 sums:

    ```
    d1fd6b6927c30c03991cf3598a2a0860485f290d0d1bcc66c49805174d1586ef *redmine_crm-4_4_1-light.zip
    af6d80bf15373b0656cd661d6135e4034ab5d4bedd543774bda60235001f5022 *redmine_products-2_2_3-light.zip
    ```

* Save this `Dockerfile`:

    ```dockerfile
    FROM redmine:5.1.3 AS initial

    RUN apt-get update && \
        apt-get -y install build-essential unzip

    USER redmine

    ADD https://github.com/danmunn/redmine_dmsf.git#06020d5806730276d811347a3e222e745903e852 /usr/src/redmine/plugins/redmine_dmsf/

    COPY redmine_crm-4_4_1-light.zip /usr/src/redmine/plugins/
    RUN (cd plugins/ && unzip redmine_crm-4_4_1-light.zip && rm redmine_crm-4_4_1-light.zip)

    COPY redmine_products-2_2_3-light.zip /usr/src/redmine/plugins/
    RUN (cd plugins/ && unzip redmine_products-2_2_3-light.zip && rm redmine_products-2_2_3-light.zip)

    RUN bundle install


    FROM redmine:5.1.3

    ENV REDMINE_PLUGINS_MIGRATE=1
    COPY --from=initial /usr/local/bundle/ /usr/local/bundle/
    COPY --from=initial /usr/src/redmine/plugins/ /usr/src/redmine/plugins/
    ```

* Build the container image:

    ```console
    $ docker build -t redmine-5.1.3-bug .
    ```

* Start the container:

    ```console
    $ docker run --rm -ti -p 3000:3000 redmine-5.1.3-bug
    ```

    Wait until the startup is finished, it will output something similar to this when done:

    ```
    * Puma version: 6.4.2 (ruby 3.2.4-p170) ("The Eagle of Durango")
    *  Min threads: 0
    *  Max threads: 5
    *  Environment: production
    *          PID: 1
    * Listening on http://0.0.0.0:3000
    Use Ctrl-C to stop
    ```

* Open http://127.0.0.1:3000/login in the web browser. Log in as `admin`:`admin`. Change the default password as requested.

* Go to http://127.0.0.1:3000/settings to reproduce the "Internal error" message. Observe `SystemStackError` in the container log.

## Git bisect log

```
git bisect start
# good: [53ba6c1a0769176672db997088261d0fcfbb14fe] v3.1.3 released
git bisect good 53ba6c1a0769176672db997088261d0fcfbb14fe
# bad: [4e3c1d885330de61909263af6791384b833d3238] v3.1.4 released
git bisect bad 4e3c1d885330de61909263af6791384b833d3238
# good: [b0ae0f5c881cb05efd68cd7ecdff0a0ab3f05e2d] Merge pull request #1511 from xmera-circle/bug-fix/ActiveRecord-ValueTooLong
git bisect good b0ae0f5c881cb05efd68cd7ecdff0a0ab3f05e2d
# bad: [0c95a291541b345fb8c58d0e4969ed09a3b9a2de] Digest can't be null
git bisect bad 0c95a291541b345fb8c58d0e4969ed09a3b9a2de
# good: [a95001aa4850f21be2c385c56fe40bcbf5e41f3b] Uncaught SyntaxError: Redecclaration of let modal in Approval Workflow Log #1510
git bisect good a95001aa4850f21be2c385c56fe40bcbf5e41f3b
# bad: [62c3a937a77ee871f229c8f06ad90afcb9100de4] Adminstration-settings cannot open after dmsf installed #1506
git bisect bad 62c3a937a77ee871f229c8f06ad90afcb9100de4
# bad: [648bed260cdfa01baf992053915396bb2e2fbbb4] Adminstration-settings cannot open after dmsf installed #1506
git bisect bad 648bed260cdfa01baf992053915396bb2e2fbbb4
# first bad commit: [648bed260cdfa01baf992053915396bb2e2fbbb4] Adminstration-settings cannot open after dmsf installed #1506
```

## Environment

```
Environment:
  Redmine version                5.1.3.stable
  Ruby version                   3.2.4-p170 (2024-04-23) [x86_64-linux]
  Rails version                  6.1.7.8
  Environment                    production
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.14.2
  Mercurial                      6.3.2
  Bazaar                         3.3.2
  Git                            2.39.2
  Filesystem                     
Redmine plugins:
  redmine_contacts               4.4.1
  redmine_dmsf                   3.1.9
  redmine_products               2.2.3
```

## Other notes

Does not reproduce if only `redmine_contacts` is installed.

Related to #1506

**Comment by RomanIOPSYS** [comment]
Judging by the commit that introduced the regression, the solution may be to add `redmine_products` as an obsolete plugin. I'll make a PR shortly.

**Comment by picman** [comment]
Fixed. Thank you!

**Comment by picman** [comment]
No, I haven't. I've just given it a try and it's a mystery for me. Both plugins seem to be equal. Though, only redmine_products causes trouble.
