### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by UserVladimir37** [danmunn/redmine_dmsf#1555]
After moving from Redmine version 4.1.1.stable (redmine_dmsf 2.4.2) to Redmine version 5.1.3.stable (redmine_dmsf 3.2.1). When you select "DMS" in the menu, a server error is displayed. the log contains the following information:

![DMS](https://github.com/user-attachments/assets/5d1d1488-df90-484d-8b64-f97005fa75dc)

```
W, [2024-10-08T20:07:52.800703 #14049]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2024-10-08T20:07:52.851800 #14049]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2024-10-08T20:07:53.000316 #14049]  WARN -- : Creating scope :visible. Overwriting existing method AgileQuery.visible.
W, [2024-10-08T20:07:53.224566 #14049]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
I, [2024-10-08T20:07:54.524358 #14090]  INFO -- : [47489bd3-12eb-46b3-8d7d-028ec42cddf3] Started GET "/admin" for 10.0.0.102 at 2024-10-08 20:07:54 +0300
I, [2024-10-08T20:07:54.527693 #14090]  INFO -- : [47489bd3-12eb-46b3-8d7d-028ec42cddf3] Processing by AdminController#index as HTML
I, [2024-10-08T20:07:54.613805 #14090]  INFO -- : [47489bd3-12eb-46b3-8d7d-028ec42cddf3]   Current user: admin (id=1)
I, [2024-10-08T20:07:54.634344 #14090]  INFO -- : [47489bd3-12eb-46b3-8d7d-028ec42cddf3]   Rendered admin/index.html.erb within layouts/admin (Duration: 9.2ms | Allocations: 7527)
I, [2024-10-08T20:07:54.686160 #14090]  INFO -- : [47489bd3-12eb-46b3-8d7d-028ec42cddf3]   Rendered layouts/base.html.erb (Duration: 50.6ms | Allocations: 28172)
I, [2024-10-08T20:07:54.686234 #14090]  INFO -- : [47489bd3-12eb-46b3-8d7d-028ec42cddf3]   Rendered layout layouts/admin.html.erb (Duration: 61.2ms | Allocations: 36792)
I, [2024-10-08T20:07:54.686613 #14090]  INFO -- : [47489bd3-12eb-46b3-8d7d-028ec42cddf3] Completed 200 OK in 159ms (Views: 55.7ms | ActiveRecord: 45.9ms | Allocations: 71279)
I, [2024-10-08T20:07:58.247155 #14090]  INFO -- : [1087d785-b051-448d-89fb-52adc81e5280] Started GET "/dmsf" for 10.0.0.102 at 2024-10-08 20:07:58 +0300
I, [2024-10-08T20:07:58.248391 #14090]  INFO -- : [1087d785-b051-448d-89fb-52adc81e5280] Processing by DmsfController#index as HTML
I, [2024-10-08T20:07:58.255002 #14090]  INFO -- : [1087d785-b051-448d-89fb-52adc81e5280]   Current user: admin (id=1)
I, [2024-10-08T20:07:58.313384 #14090]  INFO -- : [1087d785-b051-448d-89fb-52adc81e5280] Completed 500 Internal Server Error in 65ms (ActiveRecord: 17.4ms | Allocations: 25963)
F, [2024-10-08T20:07:58.314095 #14090] FATAL -- : [1087d785-b051-448d-89fb-52adc81e5280]
[1087d785-b051-448d-89fb-52adc81e5280] Query::StatementInvalid (Mysql2::Error: Illegal mix of collations for operation 'UNION'):
[1087d785-b051-448d-89fb-52adc81e5280]
[1087d785-b051-448d-89fb-52adc81e5280] plugins/redmine_dmsf/app/models/dmsf_query.rb:104:in `rescue in dmsf_count'
[1087d785-b051-448d-89fb-52adc81e5280] plugins/redmine_dmsf/app/models/dmsf_query.rb:99:in `dmsf_count'
[1087d785-b051-448d-89fb-52adc81e5280] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:94:in `block (2 levels) in show'
[1087d785-b051-448d-89fb-52adc81e5280] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:92:in `show'
[1087d785-b051-448d-89fb-52adc81e5280] plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:74:in `index'
[1087d785-b051-448d-89fb-52adc81e5280] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by picman** [comment]
`Mysql2::Error: Illegal mix of collations for operation 'UNION'`
You will have to fix it in your database. Tables dmsf_folders, dmsf_links, dmsf_files and projects must have the same collation. You can check it as follows:
```sql
select table_name, table_collation from information_schema.tables where table_schema = 'redmine';
```

**Comment by UserVladimir37** [comment]
mysql> select table_name, table_collation from information_schema.tables where table_schema = 'bitnami_redmine';

```
+-----------------------------------------+--------------------+
| TABLE_NAME                              | TABLE_COLLATION    |
+-----------------------------------------+--------------------+
| agile_colors                            | utf8mb4_0900_ai_ci |
| agile_data                              | utf8mb4_0900_ai_ci |
| agile_sprints                           | utf8mb4_0900_ai_ci |
| api_log_for_plugins                     | utf8mb3_general_ci |
| ar_internal_metadata                    | utf8mb4_0900_ai_ci |
| attachment_versions                     | utf8mb3_general_ci |
| attachments                             | utf8mb3_unicode_ci |
| auth_sources                            | utf8mb3_unicode_ci |
| boards                                  | utf8mb3_unicode_ci |
| changes                                 | utf8mb3_unicode_ci |
| changeset_parents                       | utf8mb3_unicode_ci |
| changesets                              | utf8mb3_unicode_ci |
| changesets_issues                       | utf8mb3_unicode_ci |
| checklist_template_categories           | utf8mb4_0900_ai_ci |
| checklist_templates                     | utf8mb4_0900_ai_ci |
| checklists                              | utf8mb4_0900_ai_ci |
| comments                                | utf8mb3_unicode_ci |
| custom_field_enumerations               | utf8mb3_general_ci |
| custom_field_mappings                   | utf8mb3_general_ci |
| custom_fields                           | utf8mb3_unicode_ci |
| custom_fields_projects                  | utf8mb3_unicode_ci |
| custom_fields_roles                     | utf8mb3_general_ci |
| custom_fields_trackers                  | utf8mb3_unicode_ci |
| custom_values                           | utf8mb3_unicode_ci |
| dmsf_file_revision_accesses             | utf8mb3_general_ci |
| dmsf_file_revisions                     | utf8mb3_general_ci |
| dmsf_files                              | utf8mb3_general_ci |
| dmsf_folder_permissions                 | utf8mb3_general_ci |
| dmsf_folders                            | utf8mb3_general_ci |
| dmsf_links                              | utf8mb3_general_ci |
| dmsf_locks                              | utf8mb3_general_ci |
| dmsf_public_urls                        | utf8mb3_general_ci |
| dmsf_workflow_step_actions              | utf8mb3_general_ci |
| dmsf_workflow_step_assignments          | utf8mb3_general_ci |
| dmsf_workflow_steps                     | utf8mb3_general_ci |
| dmsf_workflows                          | utf8mb3_general_ci |
| documents                               | utf8mb3_unicode_ci |
| easy_attendance_activities              | utf8mb3_general_ci |
| easy_attendance_user_arrival_notifies   | utf8mb3_general_ci |
| easy_attendances                        | utf8mb3_general_ci |
| easy_custom_field_ratings               | utf8mb3_general_ci |
| easy_external_authentications           | utf8mb3_general_ci |
| easy_external_synchronisations          | utf8mb3_general_ci |
| easy_gantt_themes                       | utf8mb3_general_ci |
| easy_global_ratings                     | utf8mb3_general_ci |
| easy_issue_timers                       | utf8mb3_general_ci |
| easy_page_available_modules             | utf8mb3_general_ci |
| easy_page_available_zones               | utf8mb3_general_ci |
| easy_page_modules                       | utf8mb3_general_ci |
| easy_page_template_modules              | utf8mb3_general_ci |
| easy_page_template_tabs                 | utf8mb3_general_ci |
| easy_page_templates                     | utf8mb3_general_ci |
| easy_page_user_tabs                     | utf8mb3_general_ci |
| easy_page_zone_modules                  | utf8mb3_general_ci |
| easy_page_zones                         | utf8mb3_general_ci |
| easy_pages                              | utf8mb3_general_ci |
| easy_permissions                        | utf8mb3_general_ci |
| easy_project_relations                  | utf8mb3_general_ci |
| easy_publishing_modules                 | utf8mb3_general_ci |
| easy_publishing_settings                | utf8mb3_general_ci |
| easy_queries                            | utf8mb3_general_ci |
| easy_queries_roles                      | utf8mb3_general_ci |
| easy_rake_task_info_details             | utf8mb3_general_ci |
| easy_rake_task_infos                    | utf8mb3_general_ci |
| easy_rake_tasks                         | utf8mb3_general_ci |
| easy_resource_availabilities            | utf8mb3_general_ci |
| easy_scheduler_tasks                    | utf8mb3_general_ci |
| easy_settings                           | utf8mb3_general_ci |
| easy_sliding_panels_locations           | utf8mb3_general_ci |
| easy_sync_mappings                      | utf8mb3_general_ci |
| easy_sync_relations                     | utf8mb3_general_ci |
| easy_textile_migrators                  | utf8mb3_general_ci |
| easy_translations                       | utf8mb3_general_ci |
| easy_user_allocation_working_plan_items | utf8mb3_general_ci |
| easy_user_allocations                   | utf8mb3_general_ci |
| easy_user_read_entities                 | utf8mb3_general_ci |
| easy_user_time_calendar_exceptions      | utf8mb3_general_ci |
| easy_user_time_calendar_holidays        | utf8mb3_general_ci |
| easy_user_time_calendars                | utf8mb3_general_ci |
| easy_version_relations                  | utf8mb3_general_ci |
| email_addresses                         | utf8mb3_general_ci |
| enabled_modules                         | utf8mb3_unicode_ci |
| enumerations                            | utf8mb3_unicode_ci |
| eq_pinned_queries                       | utf8mb3_general_ci |
| eq_queries_hide_in_projects             | utf8mb3_general_ci |
| eq_queries_show_in_projects             | utf8mb3_general_ci |
| favorite_projects                       | utf8mb3_general_ci |
| global_roles                            | utf8mb3_general_ci |
| groups_users                            | utf8mb3_unicode_ci |
| hudson_build_artifacts                  | utf8mb3_unicode_ci |
| hudson_build_changesets                 | utf8mb3_unicode_ci |
| hudson_build_test_results               | utf8mb3_unicode_ci |
| hudson_builds                           | utf8mb3_unicode_ci |
| hudson_health_reports                   | utf8mb3_unicode_ci |
| hudson_job_settings                     | utf8mb3_unicode_ci |
| hudson_jobs                             | utf8mb3_unicode_ci |
| hudson_settings                         | utf8mb3_unicode_ci |
| hudson_settings_health_reports          | utf8mb3_unicode_ci |
| import_items                            | utf8mb3_general_ci |
| imports                                 | utf8mb3_general_ci |
| issue_categories                        | utf8mb3_unicode_ci |
| issue_reads                             | utf8mb3_general_ci |
| issue_relations                         | utf8mb3_unicode_ci |
| issue_statuses                          | utf8mb3_unicode_ci |
| issues                                  | utf8mb3_unicode_ci |
| journal_details                         | utf8mb3_unicode_ci |
| journals                                | utf8mb3_unicode_ci |
| maillog_address_fields                  | utf8mb3_general_ci |
| maillog_addresses                       | utf8mb3_general_ci |
| maillogs                                | utf8mb3_general_ci |
| member_roles                            | utf8mb3_unicode_ci |
| members                                 | utf8mb3_unicode_ci |
| messages                                | utf8mb3_unicode_ci |
| news                                    | utf8mb3_unicode_ci |
| projectqueries                          | utf8mb3_general_ci |
| projects                                | utf8mb3_unicode_ci |
| projects_activities                     | utf8mb3_general_ci |
| projects_activity_roles                 | utf8mb3_general_ci |
| projects_trackers                       | utf8mb3_unicode_ci |
| queries                                 | utf8mb3_unicode_ci |
| queries_roles                           | utf8mb3_general_ci |
| query_categories                        | utf8mb3_general_ci |
| repositories                            | utf8mb3_unicode_ci |
| rich_rich_files                         | utf8mb3_general_ci |
| roles                                   | utf8mb3_unicode_ci |
| roles_managed_roles                     | utf8mb3_general_ci |
| schema_easy_data_migrations             | utf8mb3_general_ci |
| schema_migrations                       | utf8mb3_unicode_ci |
| settings                                | utf8mb3_unicode_ci |
| taggings                                | utf8mb3_general_ci |
| tags                                    | utf8mb3_general_ci |
| theme_changer_user_settings             | utf8mb3_general_ci |
| time_entries                            | utf8mb3_unicode_ci |
| tokens                                  | utf8mb3_unicode_ci |
| trackers                                | utf8mb3_unicode_ci |
| user_preferences                        | utf8mb3_unicode_ci |
| userqueries                             | utf8mb3_general_ci |
| users                                   | utf8mb3_unicode_ci |
| versions                                | utf8mb3_unicode_ci |
| watchers                                | utf8mb3_unicode_ci |
| wiki_content_versions                   | utf8mb3_unicode_ci |
| wiki_contents                           | utf8mb3_unicode_ci |
| wiki_extensions_comments                | utf8mb3_unicode_ci |
| wiki_extensions_counts                  | utf8mb3_unicode_ci |
| wiki_extensions_menus                   | utf8mb3_unicode_ci |
| wiki_extensions_settings                | utf8mb3_unicode_ci |
| wiki_extensions_tag_relations           | utf8mb3_unicode_ci |
| wiki_extensions_tags                    | utf8mb3_unicode_ci |
| wiki_extensions_votes                   | utf8mb3_unicode_ci |
| wiki_pages                              | utf8mb3_unicode_ci |
| wiki_redirects                          | utf8mb3_unicode_ci |
| wikis                                   | utf8mb3_unicode_ci |
| workflows                               | utf8mb3_unicode_ci |
+-----------------------------------------+--------------------+
153 rows in set (0.00 sec)
```

**Comment by UserVladimir37** [comment]
Is it necessary to do this with such commands?

```
alter table dmsf_folders modify table_collation varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb3_unicode_ci default null;
alter table dmsf_links modify table_collation varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb3_unicode_ci default null;
alter table dmsf_files modify table_collation varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb3_unicode_ci default null;
```
Is it safe?

**Comment by picman** [comment]
Try it on a testing database! In my Redmine instances I have all tables with the same charset and collation.

**Comment by UserVladimir37** [comment]
Unfortunately, it came in the form that we have. And the task is to migrate to a new OS and the latest version of Redmine

**Comment by picman** [comment]
I think that you can easily copy the database and test the collation change.

**Comment by picman** [comment]
See #1420.

**Comment by UserVladimir37** [comment]
> See #1420.
This is exactly what we needed. Thank you very much. Thank you for your work.
