### ISSUE TITLE
Install Syntax Error

### ISSUE THREAD

**Issue by brackovic** [danmunn/redmine_dmsf#1562]
HI, I have an error by Installing DMSF in Redmine 5.0.3. - Bitnami for Windows
Install command: 
-bundle install
-bundle exec rake redmine:plugins NAME=redmine_dmsf RAILS_ENV=production
Error is: 
C:\Bitnami\redmine-5.0.3-0\apps\redmine\htdocs\plugins>bundle exec rake redmine:plugins NAME=redmine_dmsf RAILS_ENV=production
(in C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs)
rake aborted!
SyntaxError: C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/lib/dav4rack/xml_response.rb:55: syntax error, unexpected ..., expecting ')'
...   def render_lockdiscovery(...)
...                            ^~~
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/lib/dav4rack/xml_response.rb:56: syntax error, unexpected ..., expecting ')'
...D_LOCKDISCOVERY, activelock(...)))
...                            ^~~
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/lib/dav4rack/controller.rb:7:in `<top (required)>'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/lib/dav4rack.rb:32:in `<top (required)>'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/lib/redmine_dmsf.rb:58:in `<top (required)>'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/after_init.rb:23:in `<top (required)>'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/init.rb:70:in `require_relative'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/init.rb:70:in `<top (required)>'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:31:in `load'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:31:in `run_initializer'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:108:in `each'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:108:in `block in load'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
C:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:73:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
As i can see in xml_response.rb there is code:
def render_lockdiscovery(...)
      render_xml ox_element(D_PROP, ox_element(D_LOCKDISCOVERY, activelock(...)))
    end
I tryed to delete dots in bracket, it will install DMSF but than Thin Server wont start.

Can anyone help pls....
Thanks in advance

**Comment by picman** [comment]
The problem is your Ruby 2.6. Three dots a s a function argument were added in Ruby 2.7. I don't see which version of DMSF plugin you are going to install but at least Redmine 5.1 is required.
