### ISSUE TITLE
undefined method `custom_fields_tabs' for module `CustomFieldsHelper'

### ISSUE THREAD

**Issue by intrixius** [danmunn/redmine_dmsf#226]
My environment:

```
Environment:
  Redmine version                2.5.0.devel
  Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.17
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.8.2.1
  Filesystem                     
Redmine plugins:
  due_date_reminder              0.4
  redmine_graphs                 0.1.0
  redmine_meetings               0.2.4
  redmine_mylyn_connector        2.8.2.stable
```

When trying to install DMSF 1.4.7 with `rake redmine:plugins:migrate RAILS_ENV="production"` I get the following error:

```
rake aborted!
undefined method `custom_fields_tabs' for module `CustomFieldsHelper'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'
/home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/custom_fields_helper.rb:26:in `block in included'
/home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/custom_fields_helper.rb:25:in `class_eval'
/home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/custom_fields_helper.rb:25:in `included'
/home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/custom_fields_helper.rb:44:in `include'
/home/redmine/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/custom_fields_helper.rb:44:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:440:in `_run__3174994342465356456__prepare__614345777533020795__callbacks'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/actionpack-3.2.17/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/actionpack-3.2.17/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/application.rb:136:in `initialize!'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
/home/redmine/redmine/plugins/redmine_dmsf/lib/tasks/dmsf_alert_approvals.rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in `load'
/home/redmine/redmine/lib/tasks/redmine.rake:178:in `block in <top (required)>'
/home/redmine/redmine/lib/tasks/redmine.rake:178:in `each'
/home/redmine/redmine/lib/tasks/redmine.rake:178:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/engine.rb:425:in `block in load_tasks'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/engine.rb:425:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/engine.rb:425:in `load_tasks'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/application.rb:145:in `load_tasks'
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/redmine/redmine/Rakefile:7:in `<top (required)>'
```

**Comment by senthilavn** [comment]
I can confirm the issue still exist.. Redmin 3.0.0, Ruby 2.2.0p0.

**Comment by centromere** [comment]
This issue still exists on Redmine 3.0.0, ruby 2.0.0p481.

**Comment by picman** [comment]
Neither 1.4.9 not 1.5.1 are compatible with Redmine 3.x or Ruby  2.x. Your next comments to this issue are needless. Try to provide a patch that solve it.
