### ISSUE TITLE
Debian - i18n broken

### ISSUE THREAD

**Issue by akriegisch** [danmunn/redmine_dmsf#354]
similar to what was discussed in #288 I get the following error with redmine_dmsf enabled on Debian/Wheezy with Redmine from backports:
```
  Rendered admin/plugins.html.erb within layouts/admin (64.9ms)
Completed 500 Internal Server Error in 149.0ms

ActionView::Template::Error (can not load translations from /usr/lib/ruby/vendor_ruby/../locales/en.yml: #<TypeError: no implicit conversion from nil to integer>):
    1: <%= title l(:label_plugins) %>
    2:
    3: <% if @plugins.any? %>
    4: <table class="list plugins">
  lib/redmine/i18n.rb:153:in `init_translations'
  lib/redmine/i18n.rb:167:in `lookup'
  lib/redmine/i18n.rb:27:in `l'
  app/views/admin/plugins.html.erb:1:in `_app_views_admin_plugins_html_erb__1842134549454110237_58120100'
 ```

after some logging statements in various parts of the source I found that with redmine_dmsf, the path '/usr/lib/ruby/vendor_ruby/../locales/en.yml' gets added to the path of valid translations.
Normal paths:
```
["/usr/lib/ruby/vendor_ruby/active_support/locale/en.yml", 
 "/usr/lib/ruby/vendor_ruby/active_model/locale/en.yml",
 "/usr/lib/ruby/vendor_ruby/active_record/locale/en.yml",
 "/usr/lib/ruby/vendor_ruby/action_view/locale/en.yml",
 "/usr/share/redmine/config/locales/en.yml"]
```
with redmine_dmsf in the plugins folder:
```
["/usr/lib/ruby/vendor_ruby/active_support/locale/en.yml",
 "/usr/lib/ruby/vendor_ruby/active_model/locale/en.yml",
 "/usr/lib/ruby/vendor_ruby/active_record/locale/en.yml",
 "/usr/lib/ruby/vendor_ruby/action_view/locale/en.yml",
 "/usr/lib/ruby/vendor_ruby/../locales/en.yml",
 "/usr/share/redmine/config/locales/en.yml",
 "/usr/share/redmine/plugins/redmine_dmsf/config/locales/en.yml"]
```

The error comes from trying to open the non-existent file "/usr/lib/ruby/vendor_ruby/../locales/en.yml" ; The following patch in Redmine avoids the issue by first checking for the existance of the file:
```
--- /usr/share/redmine/lib/redmine/i18n.rb.orig 2014-03-29 17:56:41.000000000 +0100
+++ /usr/share/redmine/lib/redmine/i18n.rb      2015-02-20 20:12:41.381991935 +0100
@@ -148,7 +147,8 @@

         def init_translations(locale)
           locale = locale.to_s
-          paths = ::I18n.load_path.select {|path| File.basename(path, '.*') == locale}
+          paths = ::I18n.load_path.select {|path| File.basename(path, '.*') == locale && File.exists?(path)}
           load_translations(paths)
           translations[locale] ||= {}
         end
```

I'd be interested in understanding how this happens in the first place as several other plugins work just fine. I hope you can help... ;)
Thanks!

**Comment by akriegisch** [comment]
The issue was caused by installing simple_enum the wrong way: it missed its locale file and looked it up in the wrong path. Sorry for the noise!
