### ISSUE TITLE
incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

### ISSUE THREAD

**Issue by Pilli** [danmunn/redmine_dmsf#361]
Hi.
I've a problem with full text search, when I search words with *special* characters like **código** and documents contains this word I get this error:

```
Started GET "/projects/menestra/search?utf8=%E2%9C%93&q=c%C3%B3digo" for 192.168.2.78 at 2015-02-27 09:37:04 +0100
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>"código", "id"=>"menestra"}
  Current user: pilli (id=3)
  Rendered search/index.html.erb within layouts/base (12.2ms)
Completed 500 Internal Server Error in 123.9ms

ActionView::Template::Error (incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)):
    32:           <%= content_tag('span', h(e.project), :class => 'project') unless @project == e.project %>
    33:           <%= link_to(highlight_tokens(e.event_title.truncate(255), @tokens), e.event_url) %>
    34:         </dt>
    35:         <dd><span class="description"><%= highlight_tokens(e.event_description, @tokens) %></span>
    36:         <span class="author"><%= format_time(e.event_datetime) %></span></dd>
    37:       <% end %>
    38:     </dl>
  app/helpers/search_helper.rb:26:in `split'
  app/helpers/search_helper.rb:26:in `highlight_tokens'
  app/views/search/index.html.erb:35:in `block in _app_views_search_index_html_erb___2702400376814127342_76895580'
  app/views/search/index.html.erb:30:in `each'
  app/views/search/index.html.erb:30:in `_app_views_search_index_html_erb___2702400376814127342_76895580'
```
If I uncheck  DMSF files and Dmsf folders boxs I don't get the error.
How can I fix it?

Thanks and best regards.

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
