### ISSUE TITLE
xapian indexer failing

### ISSUE THREAD

**Issue by zlacelle** [danmunn/redmine_dmsf#386]
2 part question/issue:

1)

I'm attempting to get in-document search working with Xapian.  I've followed the README instructions, but get to this point and fail:

```
# ruby redmine_dmsf/extra/xapian_indexer.rb -f
Mon Apr 27 10:22:13 2015: - Trying to load Redmine environment <</usr/share/redmine/config/environment.rb>>...
Mon Apr 27 10:22:25 2015: - Redmine environment [RAILS_ENV=production] correctly loaded ...
Mon Apr 27 10:22:25 2015: - ERROR! /var/tmp/dmsf-index/english does not exist, creating ...
Mon Apr 27 10:22:25 2015: - Indexing files under /usr/share/redmine/files/dmsf with omindex stemming in english ...
redmine_dmsf/extra/xapian_indexer.rb:473:in `system_or_raise': "/usr/bin/omindex -s english --db /var/tmp/dmsf-index/english /usr/share/redmine/files/dmsf --url / > /dev/null" failed (RuntimeError)
	from redmine_dmsf/extra/xapian_indexer.rb:540:in `block in <main>'
	from redmine_dmsf/extra/xapian_indexer.rb:525:in `each'
	from redmine_dmsf/extra/xapian_indexer.rb:525:in `<main>'
```

My configuration is as follows: 

```
################################################################################################
# BEGIN Configuration parameters
# Configure the following parameters (most of them can be configured through the command line):
################################################################################################

# Redmine installation directory
$redmine_root = "/usr/share/redmine"

# DMSF document location $redmine_root/$dmsf_root
$dmsf_root = 'files/dmsf'

# scriptindex binary path 
$scriptindex  = "/usr/bin/scriptindex"

# omindex binary path
$omindex      = "/usr/bin/omindex"

# Directory containing xapian databases for omindex (Attachments indexing)
$dbrootpath   = "/var/tmp/dmsf-index"

# Verbose output, values of 0 no verbose, greater than 0 verbose output
$verbose      = 1

# Define stemmed languages to index attachments Ej [ 'english', 'italian', 'spanish' ]
# Repository database will be always indexed in english
# Available languages are danish dutch english finnish french german german2 hungarian italian kraaij_pohlmann lovins norwegian porter portuguese romanian russian spanish swedish turkish:  
$stem_langs	= ['english']

#Project identifiers that will be indexed Ej [ 'prj_id1', 'prj_id2' ]
#$projects	= [ 'prj_id1', 'prj_id2' ]
$projects	= [ 'p_proj1', 'p_proj2']

# Temporary directory for indexing, it can be tmpfs
$tempdir	= "/tmp"

# Binaries for text conversion
$pdftotext	= "/usr/bin/pdftotext -enc UTF-8"
$antiword	= "/usr/bin/antiword"
$catdoc		= "/usr/bin/catdoc"
$xls2csv	= "/usr/bin/xls2csv"
$catppt		= "/usr/bin/catppt"
$unzip		= "/usr/bin/unzip -o"
$unrtf		= "/usr/bin/unrtf -t text 2>/dev/null"


################################################################################################
# END Configuration parameters
################################################################################################
```

2)

In the config, there's a field for "projects."  I want it to index every project every time, and not have to manually add them to this config file each time a new project is created.  What exactly goes in this list, and is there a way to just say "all projects"?

**Comment by picman** [comment]
1) Manually create the folder _/var/tmp/dmsf-index/english_. It reports creating but does obviously nothing.
2) Just comment out _$projects_ line. According to the source code it is taken into account only in case of repository indexing.
