### ISSUE TITLE
Redmine 3 Search screen error with Xapian

### ISSUE THREAD

**Issue by dlip** [danmunn/redmine_dmsf#392]
I am using the devel-1.5.2 branch at 176b478.

I have a clean redmine 3 install and have uploaded 1 text file to dmsf. I get an error on the search page only when I search for some text that is contained in this text file. Any other search is ok. I have run the cron job and the xapian db indexes seem correct.

```
[Bunch of SQL queries]

  Project Load (0.8ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
   (0.8ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 1
Completed 500 Internal Server Error in 38ms (ActiveRecord: 14.8ms)

NoMethodError (undefined method `empty?' for nil:NilClass):
  lib/redmine/search.rb:127:in `block in load_result_ids'
  lib/redmine/search.rb:125:in `each'
  lib/redmine/search.rb:125:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  app/controllers/search_controller.rb:65:in `index'
```

**Comment by picman** [comment]
1. Xapian extension correctly installed?
2. Can you provide a little bigger chunk of the log?

**Comment by dlip** [comment]
1. Yes the bundle install has no errors
2. Here is more of the log, but it doesn't have any more trace history, i set `config.log_level = :debug` in the environment config which should be the most verbose?

```
Started GET "/search?utf8=%E2%9C%93&q=here&all_words=&all_words=1&titles_only=&issues=1&news=1&documents=1&changesets=1&wiki_pages=1&messages=1&projects=1&dmsf_files=1&dmsf_folders=1&attach
ments=0&options=0&commit=Submit" for 127.0.0.1 at 2015-05-29 19:45:58 +0000
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>"here", "all_words"=>"1", "titles_only"=>"", "issues"=>"1", "news"=>"1", "documents"=>"1", "changesets"=>"1", "wiki_pages"=>"1", "messages"=>"1", "projects"
=>"1", "dmsf_files"=>"1", "dmsf_folders"=>"1", "attachments"=>"0", "options"=>"0", "commit"=>"Submit"}
  Setting Load (0.7ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'session_lifetime'  ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.9ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'session_timeout'  ORDER BY `settings`.`id` DESC LIMIT 1
   (0.7ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
  User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1
  Current user: admin (id=1)
  Setting Load (0.8ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'force_default_language_for_loggedin'  ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (1.2ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'force_default_language_for_anonymous'  ORDER BY `settings`.`id` DESC LIMIT 1
   (0.9ms)  SELECT DISTINCT `issues`.`created_on`, `issues`.`id` FROM `issues` INNER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` WHERE (projects.status <> 9 AND projects.id I
N (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking')) AND (((subject LIKE '%here%') OR (issues.description LIKE '%here%')))  ORDER BY `issues`.`created_on` DESC,
`issues`.`id` DESC
  CustomField Load (0.7ms)  SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'IssueCustomField' AND `custom_fields`.`searchable` = 1
   (0.9ms)  SELECT DISTINCT `issues`.`created_on`, `issues`.`id` FROM `issues` INNER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` INNER JOIN `journals` ON `journals`.`journali
zed_id` = `issues`.`id` AND `journals`.`journalized_type` = 'Issue' WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_trackin
g')) AND (journals.private_notes = 0 OR (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking'))) AND (((journals.notes LIKE '
%here%')))  ORDER BY `issues`.`created_on` DESC, `issues`.`id` DESC
   (0.9ms)  SELECT DISTINCT `news`.`created_on`, `news`.`id` FROM `news` INNER JOIN `projects` ON `projects`.`id` = `news`.`project_id` WHERE (projects.status <> 9 AND projects.id IN (SELEC
T em.project_id FROM enabled_modules em WHERE em.name='news')) AND (((title LIKE '%here%') OR (summary LIKE '%here%') OR (news.description LIKE '%here%')))  ORDER BY `news`.`created_on` DES
C, `news`.`id` DESC
   (1.1ms)  SELECT DISTINCT `documents`.`created_on`, `documents`.`id` FROM `documents` INNER JOIN `projects` ON `projects`.`id` = `documents`.`project_id` WHERE (projects.status <> 9 AND p
rojects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='documents')) AND (((title LIKE '%here%') OR (documents.description LIKE '%here%')))  ORDER BY `documents`.`created
_on` DESC, `documents`.`id` DESC
  CustomField Load (0.6ms)  SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'DocumentCustomField' AND `custom_fields`.`searchable` = 1
   (0.7ms)  SELECT DISTINCT `changesets`.`committed_on`, `changesets`.`id` FROM `changesets` INNER JOIN `repositories` ON `repositories`.`id` = `changesets`.`repository_id` INNER JOIN `proj
ects` ON `projects`.`id` = `repositories`.`project_id` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='repository')) AND (((comme
nts LIKE '%here%')))  ORDER BY `changesets`.`committed_on` DESC, `changesets`.`id` DESC
   (1.2ms)  SELECT DISTINCT `wiki_pages`.`created_on`, `wiki_pages`.`id` FROM `wiki_pages` INNER JOIN `wiki_contents` ON `wiki_contents`.`page_id` = `wiki_pages`.`id` INNER JOIN `wikis` ON
`wikis`.`id` = `wiki_pages`.`wiki_id` INNER JOIN `projects` ON `projects`.`id` = `wikis`.`project_id` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modul
es em WHERE em.name='wiki')) AND (((title LIKE '%here%') OR (wiki_contents.text LIKE '%here%')))  ORDER BY `wiki_pages`.`created_on` DESC, `wiki_pages`.`id` DESC
   (1.0ms)  SELECT DISTINCT `messages`.`created_on`, `messages`.`id` FROM `messages` INNER JOIN `boards` ON `boards`.`id` = `messages`.`board_id` INNER JOIN `projects` ON `projects`.`id` =
`boards`.`project_id` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='boards')) AND (((subject LIKE '%here%') OR (content LIKE '%
here%')))  ORDER BY `messages`.`created_on` DESC, `messages`.`id` DESC
   (0.7ms)  SELECT DISTINCT `projects`.`created_on`, `projects`.`id` FROM `projects` WHERE (projects.status <> 9) AND (((name LIKE '%here%') OR (identifier LIKE '%here%') OR (description LI
KE '%here%')))  ORDER BY `projects`.`created_on` DESC, `projects`.`id` DESC
  CustomField Load (0.7ms)  SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'ProjectCustomField' AND `custom_fields`.`searchable` = 1
  Setting Load (0.8ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'plugin_redmine_dmsf'  ORDER BY `settings`.`id` DESC LIMIT 1
  DmsfFile Load (0.8ms)  SELECT DISTINCT `dmsf_files`.* FROM `dmsf_files` INNER JOIN `projects` ON `projects`.`id` = `dmsf_files`.`project_id` INNER JOIN `dmsf_file_revisions` ON `dmsf_file
_revisions`.`dmsf_file_id` = `dmsf_files`.`id` WHERE `dmsf_files`.`deleted` = 0 AND (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='dms
f')) AND (((LOWER(dmsf_files.name) LIKE '%here%') OR (LOWER(dmsf_file_revisions.title) LIKE '%here%') OR (LOWER(dmsf_file_revisions.description) LIKE '%here%') OR (LOWER(dmsf_file_revisions
.comment) LIKE '%here%')))
  DmsfFile Load (0.5ms)  SELECT  `dmsf_files`.* FROM `dmsf_files` WHERE `dmsf_files`.`deleted` = 0 AND `dmsf_files`.`id` = 1  ORDER BY `dmsf_files`.`id` ASC LIMIT 1
  Project Load (0.7ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
   (0.7ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 1
Completed 500 Internal Server Error in 281ms (ActiveRecord: 36.5ms)

NoMethodError (undefined method `empty?' for nil:NilClass):
  lib/redmine/search.rb:127:in `block in load_result_ids'
  lib/redmine/search.rb:125:in `each'
  lib/redmine/search.rb:125:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  app/controllers/search_controller.rb:65:in `index'
```

Here is the files created by dmsf
```
root@ae7b8c02e99a:/home/redmine/redmine/files# find
.
./dmsf
./dmsf/p_dane
./dmsf/p_dane/150529193419_1_test.txt
./dmsf_index
./dmsf_index/english
./dmsf_index/english/termlist.baseA
./dmsf_index/english/postlist.baseB
./dmsf_index/english/record.DB
./dmsf_index/english/position.baseA
./dmsf_index/english/termlist.baseB
./dmsf_index/english/position.DB
./dmsf_index/english/postlist.DB
./dmsf_index/english/flintlock
./dmsf_index/english/postlist.baseA
./dmsf_index/english/termlist.DB
./dmsf_index/english/position.baseB
./dmsf_index/english/record.baseA
./dmsf_index/english/iamchert
./dmsf_index/english/record.baseB
root@ae7b8c02e99a:/home/redmine/redmine/files# ls -la
total 16
drwxr-xr-x 4 redmine redmine 4096 May 29 19:37 .
drwxr-xr-x 5 redmine redmine 4096 May 29 11:57 ..
drwxr-xr-x 3 redmine redmine 4096 May 29 19:34 dmsf
drwxr-xr-x 3 redmine redmine 4096 May 29 19:37 dmsf_index
```

**Comment by dlip** [comment]
It's started working now, im not sure if fixing the permissions on the files dir was delayed, but after i started editing and reverted some changes in the dmsf plugin and refreshed it was ok.
