### ISSUE TITLE
"Couldn't find all Projects with 'id'" on webdav access when having admin rights

### ISSUE THREAD

**Issue by willuhn** [danmunn/redmine_dmsf#405]
Redmine 3.0.4:
Ruby: 2.2.2

When the user has admin rights, the attempt to access ${redmineUrl}/dmsf/webdav results in the following stacktrace:

```
F, [2015-07-14T13:05:53.128607 #17452] FATAL -- : 
ActiveRecord::RecordNotFound (Couldn't find all Projects with 'id': (all, {:order=>"lft"}) [WHERE (projects.status <> 9)] (found 0 results, but was looking for 2)):
  activerecord (4.2.3) lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
  activerecord (4.2.3) lib/active_record/relation/finder_methods.rb:467:in `find_some'
  activerecord (4.2.3) lib/active_record/relation/finder_methods.rb:426:in `find_with_ids'
  activerecord (4.2.3) lib/active_record/relation/finder_methods.rb:71:in `find'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/index_resource.rb:33:in `children'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/base_resource.rb:66:in `html_display'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/index_resource.rb:79:in `get'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/resource_proxy.rb:101:in `get'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  dav4rack (0.3.0) lib/dav4rack/controller.rb:78:in `get'
  dav4rack (0.3.0) lib/dav4rack/handler.rb:30:in `call'
```
Because I couldn't figure out, how to query all projects, my temporary solution was to comment out the special admin behaviour in plugins/redmine_dmsf/lib/redmine_dmsf/webdav/index_resource.rb

```
# if User.current.admin?
#   @Projects = Project.visible.find(:all, :order => 'lft')
# elsif User.current.logged? ....
    User.current.membersh...
# end
```

**Comment by picman** [comment]
Fixed. Thank you for the bug report.

**Comment by willuhn** [comment]
Patch works like a charm. Thanks for your ultra quick fix!
