### ISSUE TITLE
Got 500 error when change directory name.

### ISSUE THREAD

**Issue by mekery** [danmunn/redmine_dmsf#430]
Problem: When trying to save change directory name, I encountered a 500 error. Log looks like:

```
App 24344 stderr: ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
App 24344 stderr:   activemodel (4.2.3) lib/active_model/forbidden_attributes_protection.rb:21:in `sanitize_for_mass_assignment'
App 24344 stderr:   protected_attributes (1.1.3) lib/active_model/mass_assignment_security.rb:354:in `sanitize_for_mass_assignment'
App 24344 stderr:   activerecord (4.2.3) lib/active_record/attribute_assignment.rb:33:in `assign_attributes'
App 24344 stderr:   plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:310:in `save'

```

Solution: Add params.permit! to related method at the first line.

```ruby
# plugins/redmine_dmsf/app/controllers/dmsf_controller.rb
  def save
    params.permit!
    ...
```

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
