### ISSUE TITLE
http/500 when accessing DMSF in a specific project

### ISSUE THREAD

**Issue by tjaeger** [danmunn/redmine_dmsf#433]
In one specific Project, since today, i get an http/500 when accessing DMSF.
Logfiles doesnt look too meaningful to me, maybe someone else with a clue ?

Looking into the respective /files/dmsf/p_prj1/
i dont see any Document was added  since 6 weeks or so, so its likely not a broken Doc/Name
Also in this specific project, there are not many Docs either (like 3 with 2 REV each).

```
Completed 302 Found in 10.8ms (ActiveRecord: 0.7ms)
Started GET "/projects/prj1/dmsf" for 192.168.168.66 at 2015-08-07 10:44:49 +0200
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"prj1"}
  Current user: tjaeger (id=14)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (6.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (22.5ms)
Completed 500 Internal Server Error in 39.4ms

ActionView::Template::Error (undefined method `name' for "DmsfFile":ActiveModel::Name):
    30:     dmsf_folder_path(:id => project, :folder_id => subfolder),
    31:     :class => 'icon icon-folder') %>
    32:   <% if link %>
    33:     <div class="filename" title="<%= l(:label_target_folder)%>"><%= link.path %></div>
    34:   <% else %>
    35:     <div class="filename" title="<%= l(:title_items)%>">[<%= subfolder.items %>]</div>
    36:   <% end %>
  plugins/redmine_dmsf/app/models/dmsf_link.rb:98:in `path'
  plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb:33:in `_plugins_redmine_dmsf_app_views_dmsf__dir_html_erb___2249109457892315677_31369560'
  actionpack (3.2.22) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.22) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.22) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.22) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
  actionpack (3.2.22) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
  actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[ . . . . . . ]
```

**Comment by tjaeger** [comment]
If i search for a Document and click the Link to it (-> eg: https://192.168.194.63/dmsf/files/116) i get to the Document/Rev without error.

**Comment by tjaeger** [comment]
Installed and it seemed to solved the issues:
/plugins/redmine_dmsf$ git show
commit 82d489a10d196a2a843da45338aebed80a991070
Merge: 2cd63f9 b8521f2
Author: Karel Picman <karel.picman@kontron.com>
Date:   Tue Aug 4 08:28:38 2015 +0200
