### ISSUE TITLE
Converting Documents to DMSF is not working

### ISSUE THREAD

**Issue by soncu** [danmunn/redmine_dmsf#471]
Hi sir,
I just raked : 
```
/usr/share/redmine$ sudo rake redmine:dmsf_convert_documents project=myproj RAILS_ENV="production"
```
but it gives nothing. No error, no success and no visible difference in DMSF tab.
(I have a file named **test** under Documents)

**Comment by rfigura** [comment]
Hello,

it seems that I have the same error with a version freshly cloned from your git repository. The rake command does not provide any output, nor does it copy any files to the files/dmfs folder (even if files and documents are associated with the corresponding project).

Not sure if this is related, but I also get an error on when trying to upload a file through DMS:

```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.
```

The log file doesn't tell me anything new, however, I have to admit that I am not used to read redmine logs...

```
Started POST "/projects/test/dmsf/upload/files" for 192.168.184.141 at 2015-11-18 10:45:33 +0000
Processing by DmsfUploadController#upload_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"GINQTzSM9PXg8aSGIYOc7CQmJ3Ok7Hwxeb33LpEuUAdC60mAlZ28gP7wCxJn4rE0u6n1LNZsbCJ9rrOWDMV2VQ==", "attachments"=>{"dummy"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x00000003ef05f8 @tempfile=#<Tempfile:/tmp/RackMultipart20151118-6677-dfhfr.txt>, @original_filename="Test.txt", @content_type="text/plain", @headers="Content-Disposition: form-data; name=\"attachments[dummy][file]\"; filename=\"Test.txt\"\r\nContent-Type: text/plain\r\n">}}, "commit"=>"Upload", "id"=>"test"}
  Current user: admin (id=1)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (1.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb within layouts/base (7.3ms)
Completed 500 Internal Server Error in 19ms (ActiveRecord: 0.7ms)

ActionView::Template::Error (undefined method `locked' for nil:NilClass):
    33: <%= form_tag({:action => 'commit_files', :id => @project, :folder_id => @folder},
    34:   :method=>:post) do %>
    35:   <% @uploads.each do |upload| %>
    36:     <% if upload.locked %>
    37:       <%= render(:partial => 'upload_file_locked', :locals => {:upload => upload, :i => i}) %>
    38:     <% else %>
    39:       <%= render(:partial => 'upload_file', :locals => {:upload => upload, :i => i}) %>
  plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb:36:in `block (2 levels) in _plugins_redmine_dmsf_app_views_dmsf_upload_upload_files_html_erb__3940271947139534559_34141600'
  plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb:35:in `each'
  plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb:35:in `block in _plugins_redmine_dmsf_app_views_dmsf_upload_upload_files_html_erb__3940271947139534559_34141600'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.1) lib/action_view/helpers/form_tag_helper.rb:70:in `form_tag'
  plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb:33:in `_plugins_redmine_dmsf_app_views_dmsf_upload_upload_files_html_erb__3940271947139534559_34141600'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.0.16) lib/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
  passenger (5.0.16) lib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
  passenger (5.0.16) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.0.16) lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
  passenger (5.0.16) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

I would be happy to provide further information regarding this problem, but I do not know where to start...

Thank you for any help!

**Comment by picman** [comment]
Yes, it is definitely somehow related. First of all try to fix the problem with uploading documents. From the log I see that you're using the old way of uploading. Why?

![upload](https://cloud.githubusercontent.com/assets/779003/11363411/0775eca0-929a-11e5-94bb-e63e9555a803.png)

**Comment by picman** [comment]
It's maybe related to #472.

**Comment by soncu** [comment]
What is the latest status of this problem?

**Comment by picman** [comment]
Fixed. Please try with 1.5.6.

**Comment by rfigura** [comment]
Hello,

thank you very much for your fast reply!
I am very sorry, but it seems that the problem is caused by some local configuration of my Firefox (FF). As you can see in the Screenshot attached, not all buttons are displayed in FF (all plugins disabled), however, it works perfectly fine using another machine.

Again, I am sorry if I caused any trouble.

Cheers,
Richard

Screenshot (Windows: FF top, IE bottom)
![dmsf_ff_ie](https://cloud.githubusercontent.com/assets/15669763/11393094/05231bfc-935e-11e5-9ba2-1c70297c7bc4.PNG)

**Comment by picman** [comment]
I guess that you have Javascript disabled in FF. Please check in about:config page.

**Comment by rfigura** [comment]
unfortunately, this doesn't seem to be the reason... FF says "javascript.enabled;true", also quickly checking the result of whatismybrowser.com tells me that Javascript is active (not sure if this a good reference though)

**Comment by soncu** [comment]
How can I apply version `1.5.6` since my version is `1.5.3` and currently I have lots of DMSF documents.
Best Regards.

**Comment by picman** [comment]
```bash
cd plugins/redmine_dmsf
git fetch
git checkout devel-1.5.6
git pull origin devel-1.5.6
bundle install
chown -R www-data:www-data *
cd ../..
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
service apache2 restart
```

**Comment by soncu** [comment]
Thank you, I made it working.
But DMSF module should be disabled from project settings even DMSF has file/folders.
`"?/\:<>` characters not permitted during conversion.
if any error ocurs during conversion, The document as well as subsequent documents are kept under Document module otherwise it deactivates document module.

Best Regards.
