### ISSUE TITLE
Can't install redmine_dmsf on Redmine 3.2.1

### ISSUE THREAD

**Issue by sergey-kratov** [danmunn/redmine_dmsf#537]
I'm trying to install redmine_dmsf 1.5.6 on Redmine 3.2.1 (which is installed on Ubuntu 16.04).
I use instruction from this page "https://github.com/danmunn/redmine_dmsf".

But then I do "bundle exec rake redmine:plugins:migrate RAILS_ENV="production", I get:

rake aborted!
NameError: uninitialized constant ActionDispatch::XmlParamsParser
Did you mean?  ActionDispatch::ParamsParser
/usr/share/redmine/config/application.rb:55:in `<class:Application>'
/usr/share/redmine/config/application.rb:8:in `<module:RedmineApp>'
/usr/share/redmine/config/application.rb:7:in `<top (required)>'
/usr/share/redmine/Rakefile:4:in `require'
/usr/share/redmine/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

Can you help me with this problem? What should I do to solve it?

**Comment by sergey-kratov** [comment]
I updated my Redmine to version 3.3.0 and added missing gems to the Gemfile of that module. That was enough to allow the module to install and properly work.
