### ISSUE TITLE
Internal Server Error when search results present moved files

### ISSUE THREAD

**Issue by zeenlym** [danmunn/redmine_dmsf#669]
Hi,

I have DMSF activated on a projet "PROJECT" with 3 files : 
 - A.doc
 - B.doc
 - C.doc
If a search for "B" there is no problem.

Then if I do these steps:
 1. Create "dir" directory
 2. Move "B.doc" to "dir" directory
 3. "B.doc" has two revisions (the last tells it was moved)

Then the search for "B" return an 500 Internal Error.

My configuration is : 
````
Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux-gnu]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.8.1
  Filesystem                     
  Xitolite                       2.8.1
Redmine plugins:
  event_notifications            3.2.1
  pdf_export                     0.1
  redmine_agile                  1.4.0
  redmine_bbb                    0.2.0
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.3
  redmine_ckeditor               1.1.3
  redmine_create_wiki_page       0.1
  redmine_dashboard              2.7.0
  redmine_dmsf                   1.5.5
  redmine_git_hosting            1.2.0
  redmine_my_page                0.1.9
  redmine_work_time              0.3.2
  redmine_workflow_enhancements  0.5.0
  redmine_xapian                 1.6.6
````

Here are the logs : 
```
Started GET "/search?page=2&q=pdap&utf8=%E2%9C%93" for 213.190.88.94 at 2017-02-15 15:00:40 +0100
Processing by SearchController#index as HTML
  Parameters: {"page"=>"1", "q"=>"B", "utf8"=>"✓"}
  Current user: #####
  Rendered plugins/redmine_xapian/app/views/search/index.html.erb within layouts/base (10.2ms)
Completed 500 Internal Server Error in 20ms (ActiveRecord: 3.7ms)

ActionView::Template::Error (undefined method `+' for nil:NilClass):
    79:         <% # Plugin change end %>
    80:         </dt>
    81:         <dd><span class="description">
    82:           <%= highlight_tokens(e.event_description, @tokens) %>
    83:         </span>
    84:         <span class="author"><%= format_time(e.event_datetime) %></span></dd>
    85:       <% end %>
  plugins/redmine_dmsf/app/models/dmsf_file.rb:75:in `block in <class:DmsfFile>'
  lib/plugins/acts_as_event/lib/acts_as_event.rb:62:in `call'
  lib/plugins/acts_as_event/lib/acts_as_event.rb:62:in `event_description'
  plugins/redmine_xapian/app/views/search/index.html.erb:82:in `block in _plugins_redmine_xapian_app_views_search_index_html_erb___2163550262506309012_103087560'
  plugins/redmine_xapian/app/views/search/index.html.erb:68:in `each'
  plugins/redmine_xapian/app/views/search/index.html.erb:68:in `_plugins_redmine_xapian_app_views_search_index_html_erb___2163550262506309012_103087560'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
```

**Comment by picman** [comment]
It has been already fixed. Please upgrade to v1.5.8.
