### ISSUE TITLE
Webdav: PROPFIND on a locked folder causes internal server error

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#673]
```
NoMethodError (undefined method `dmsf_folder' for #<DmsfLock:0x007fd9dab5c258>):
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/dmsf_resource.rb:682:in `lockdiscovery'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/dmsf_resource.rb:638:in `get_property'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/resource_proxy.rb:161:in `get_property'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:230:in `block (5 levels) in create_propfind_response'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:224:in `block (4 levels) in create_propfind_response'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:220:in `block (3 levels) in create_propfind_response'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:219:in `new'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:219:in `block (2 levels) in create_propfind_response'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:202:in `each'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:202:in `block in create_propfind_response'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:201:in `create_propfind_response'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:140:in `propfind'
```

**Comment by picman** [comment]
Fixed.
