### ISSUE TITLE
Error migrate plugin v1.5.9

### ISSUE THREAD

**Issue by brestows** [danmunn/redmine_dmsf#692]
Update Redmine to 3.3 and the plugin v1.5.9. But get error, when I run:
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

Error:
```
Migrating redmine_dmsf (DMSF)...
== 20160217133001 StatusDeleted: migrating ====================================
-- change_column(:dmsf_folders, :deleted, "integer USING CAST(deleted AS integer)", {:null=>false, :default=>0})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE integer USING CAST(deleted AS integer)
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:33:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE integer USING CAST(deleted AS integer)
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:33:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:33:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate

```

**Comment by picman** [comment]
Could you do me a favor?

Please modify the _up_ function in _plugin/sredmine_dmsf/db/migrate/20160217133001_status_deleted.rb_ as follows and test the migration?

```ruby
def self.up
  #change_column :dmsf_folders, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFolder::STATUS_ACTIVE
  #change_column :dmsf_files, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFile::STATUS_ACTIVE
  #change_column :dmsf_file_revisions, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFileRevision::STATUS_ACTIVE
  #change_column :dmsf_links, :deleted, cast_integer(:deleted), :null => false, :default => DmsfLink::STATUS_ACTIVE
  change_column :dmsf_folders, :deleted, cast_integer(:deleted), :null => false, :default => NULL
  change_column :dmsf_folders, :deleted, integer, :default => DmsfFolder::STATUS_ACTIVE
  change_column :dmsf_files, :deleted, cast_integer(:deleted), :null => false, :default => NULL
  change_column :dmsf_files, :deleted, integer, :default => DmsfFile::STATUS_ACTIVE
  change_column :dmsf_file_revisions, :deleted, cast_integer(:deleted), :null => false, :default => NULL
  change_column :dmsf_file_revisions, :deleted, integer, :default => DmsfFileRevision::STATUS_ACTIVE
  change_column :dmsf_links, :deleted, cast_integer(:deleted), :null => false, :default => NULL
  change_column :dmsf_links, :deleted, integer, :default => DmsfLink::STATUS_ACTIVE
end
```

**Comment by brestows** [comment]
Now, I get error:

```
Migrating redmine_dmsf (DMSF)...
== 20160217133001 StatusDeleted: migrating ====================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant StatusDeleted::NULL
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:36:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
NameError: uninitialized constant StatusDeleted::NULL
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:36:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate

```

**Comment by picman** [comment]
Oops, **nil** should have been there! Once more please.

```ruby
def self.up
  #change_column :dmsf_folders, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFolder::STATUS_ACTIVE
  #change_column :dmsf_files, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFile::STATUS_ACTIVE
  #change_column :dmsf_file_revisions, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFileRevision::STATUS_ACTIVE
  #change_column :dmsf_links, :deleted, cast_integer(:deleted), :null => false, :default => DmsfLink::STATUS_ACTIVE
  change_column :dmsf_folders, :deleted, cast_integer(:deleted), :null => false, :default => nil
  change_column :dmsf_folders, :deleted, integer, :default => DmsfFolder::STATUS_ACTIVE
  change_column :dmsf_files, :deleted, cast_integer(:deleted), :null => false, :default => nil
  change_column :dmsf_files, :deleted, integer, :default => DmsfFile::STATUS_ACTIVE
  change_column :dmsf_file_revisions, :deleted, cast_integer(:deleted), :null => false, :default => nil
  change_column :dmsf_file_revisions, :deleted, integer, :default => DmsfFileRevision::STATUS_ACTIVE
  change_column :dmsf_links, :deleted, cast_integer(:deleted), :null => false, :default => nil
  change_column :dmsf_links, :deleted, integer, :default => DmsfLink::STATUS_ACTIVE
end
```

**Comment by brestows** [comment]
`
Migrating redmine_dmsf (DMSF)...
== 20160217133001 StatusDeleted: migrating ====================================
-- change_column(:dmsf_folders, :deleted, "integer USING CAST(deleted AS integer)", {:null=>false, :default=>nil})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE integer USING CAST(deleted AS integer)
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:36:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE integer USING CAST(deleted AS integer)
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:36:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:36:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate

`

**Comment by picman** [comment]
And this (please replce the whole class)?: 

```ruby
class StatusDeleted < ActiveRecord::Migration
  def self.cast_integer(colname)
    adapter_name = ActiveRecord::Base.connection.adapter_name.downcase
    case adapter_name
    when /postgresql/
      'INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END'
    else
      'integer'
    end
  end
  def self.up
    change_column :dmsf_folders, :deleted, cast_integer(:deleted), :null => false, :default => nil
    change_column :dmsf_folders, :deleted, integer, :default => DmsfFolder::STATUS_ACTIVE
    change_column :dmsf_files, :deleted, cast_integer(:deleted), :null => false, :default => nil
    change_column :dmsf_files, :deleted, integer, :default => DmsfFile::STATUS_ACTIVE
    change_column :dmsf_file_revisions, :deleted, cast_integer(:deleted), :null => false, :default => nil
    change_column :dmsf_file_revisions, :deleted, integer, :default => DmsfFileRevision::STATUS_ACTIVE
    change_column :dmsf_links, :deleted, cast_integer(:deleted), :null => false, :default => nil
    change_column :dmsf_links, :deleted, integer, :default => DmsfLink::STATUS_ACTIVE
  end
end
```

**Comment by brestows** [comment]
Sorry, maybe I'm doing something wrong, but I'm getting another error
```
Migrating redmine_dmsf (DMSF)...
== 20160217133001 StatusDeleted: migrating ====================================
-- change_column(:dmsf_folders, :deleted, "INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END", {:null=>false, :default=>nil})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:31:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:31:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:31:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate

```

**Comment by picman** [comment]
I'm sorry that you have to test it so many times. If I weren't lazy to install Postgress....

Please try this:

```ruby
class StatusDeleted < ActiveRecord::Migration
  def self.cast_integer(colname)
    adapter_name = ActiveRecord::Base.connection.adapter_name.downcase
    case adapter_name
    when /postgresql/
      'INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END'
    else
      'integer'
    end
  end
  def self.up
    change_column :dmsf_folders, :deleted, cast_integer(:deleted), :null => false
    change_column :dmsf_folders, :deleted, integer, :default => DmsfFolder::STATUS_ACTIVE
    change_column :dmsf_files, :deleted, cast_integer(:deleted), :null => false
    change_column :dmsf_files, :deleted, integer, :default => DmsfFile::STATUS_ACTIVE
    change_column :dmsf_file_revisions, :deleted, cast_integer(:deleted), :null => false
    change_column :dmsf_file_revisions, :deleted, integer, :default => DmsfFileRevision::STATUS_ACTIVE
    change_column :dmsf_links, :deleted, cast_integer(:deleted), :null => false
    change_column :dmsf_links, :deleted, integer, :default => DmsfLink::STATUS_ACTIVE
  end
end
```

**Comment by brestows** [comment]
Test is not difficult :) The main thing to fix: 

```
Migrating redmine_dmsf (DMSF)...
== 20160217133001 StatusDeleted: migrating ====================================
-- change_column(:dmsf_folders, :deleted, "INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END", {:null=>false})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:32:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:32:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
PG::DatatypeMismatch: ERROR:  default for column "deleted" cannot be cast automatically to type integer
/var/www/sysadm-redmine/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:32:in `up'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/sysadm-redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/sysadm-redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate

```

**Comment by picman** [comment]
```ruby
class StatusDeleted < ActiveRecord::Migration
  def self.cast_integer(colname)
    adapter_name = ActiveRecord::Base.connection.adapter_name.downcase
    case adapter_name
    when /postgresql/
      'INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END'
    else
      'integer'
    end
  end
  def self.up
    execute 'ALTER TABLE dmsf_folders ALTER deleted DROP DEFAULT;'
    change_column :dmsf_folders, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFolder::STATUS_ACTIVE
    execute 'ALTER TABLE dmsf_files ALTER deleted DROP DEFAULT;'
    change_column :dmsf_files, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFile::STATUS_ACTIVE
    execute 'ALTER TABLE dmsf_file_revisions ALTER deleted DROP DEFAULT;'
    change_column :dmsf_file_revisions, :deleted, cast_integer(:deleted), :null => false, :default => DmsfFileRevision::STATUS_ACTIVE
    execute 'ALTER TABLE dmsf_links ALTER deleted DROP DEFAULT;'
    change_column :dmsf_links, :deleted, cast_integer(:deleted), :null => false, :default => DmsfLink::STATUS_ACTIVE
  end
end
```

**Comment by brestows** [comment]
Excellent! Now it works!

**Comment by picman** [comment]
Or even safer:

```ruby
class StatusDeleted < ActiveRecord::Migration
  def self.cast_integer(colname)
    adapter_name = ActiveRecord::Base.connection.adapter_name.downcase
    case adapter_name
    when /postgresql/
      'INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END'
    else
      'integer'
    end
  end
  def self.up
    execute 'ALTER TABLE dmsf_folders ALTER deleted DROP DEFAULT;'
    change_column :dmsf_folders, :deleted, cast_integer(:deleted), :null => false
    execute "ALTER TABLE dmsf_folders ALTER deleted SET DEFAULT #{DmsfFolder::STATUS_ACTIVE}"
    execute 'ALTER TABLE dmsf_files ALTER deleted DROP DEFAULT;'
    change_column :dmsf_files, :deleted, cast_integer(:deleted), :null => false
    execute "ALTER TABLE dmsf_files ALTER deleted SET DEFAULT #{DmsfFolder::STATUS_ACTIVE}"
    execute 'ALTER TABLE dmsf_file_revisions ALTER deleted DROP DEFAULT;'
    change_column :dmsf_file_revisions, :deleted, cast_integer(:deleted), :null => false
    execute "ALTER TABLE dmsf_file_revisions ALTER deleted SET DEFAULT #{DmsfFolder::STATUS_ACTIVE}"
    execute 'ALTER TABLE dmsf_links ALTER deleted DROP DEFAULT;'
    change_column :dmsf_links, :deleted, cast_integer(:deleted), :null => false
    execute "ALTER TABLE dmsf_links ALTER deleted SET DEFAULT #{DmsfFolder::STATUS_ACTIVE}"
  end
end
```

**Comment by picman** [comment]
Great! Thanks for your cooperation.

**Comment by picman** [comment]
Now it doesn't work in SQLite :-(

**Comment by picman** [comment]
Fixed.
