### ISSUE TITLE
Error migrating 1.5.9 - Using ActiveRecord

### ISSUE THREAD

**Issue by bartroff** [danmunn/redmine_dmsf#707]
Hi all,

Currently installing dmsf (master branch) on a fresh installation of Redmine 3.3.2. I am using Linux Redhat as frontend and MS SQL 2008 as backend via. ActiveRecord.

When running `bundle exec rake redmine:plugins:migrate RAILS_ENV="production" ` I get the following error:

```
# bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
/usr/local/rvm/gems/ruby-2.3.3/gems/tiny_tds-1.3.0/lib/tiny_tds/client.rb:53: warning: TinyTds: :use_utf16 option not supported in this version of FreeTDS.

svn: warning: cannot set LC_CTYPE locale
svn: warning: environment variable LC_CTYPE is UTF-8
svn: warning: please check that your locale name is correct
Migrating clipboard_image_paste (Clipboard image paste)...
Migrating redmine_ckeditor (Redmine CKEditor plugin)...
Migrating redmine_dmsf (DMSF)...
== 20160222140401 ApprovalWorkflowStdFields: migrating ========================
-- add_column(:dmsf_workflows, :updated_on, :timestamp)
   -> 0.0038s
   -> -1 rows
-- add_column(:dmsf_workflows, :created_on, :datetime)
   -> 0.0021s
   -> -1 rows
-- add_column(:dmsf_workflows, :author_id, :integer)
   -> 0.0012s
   -> -1 rows
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

TinyTds::Error: An expression of non-boolean type specified in a context where a condition is expected, near 'limit'.: EXEC sp_executesql N'UPDATE [dmsf_workflows] SET created_on = updated_on, author_id = (select id from users where admin limit 1); SELECT @@ROWCOUNT AS AffectedRows'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `handle_to_names_and_values_dblib'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:412:in `handle_to_names_and_values'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:385:in `_raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:380:in `block in raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:380:in `raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:363:in `do_exec_query'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:22:in `exec_query'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:82:in `exec_update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:40:in `exec_update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation.rb:326:in `update_all'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/querying.rb:8:in `update_all'
/var/www/redmine_prod/plugins/redmine_dmsf/db/migrate/20160222140401_approval_workflow_std_fields.rb:30:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:558:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:598:in `exec_migration'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:578:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:577:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:752:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:1038:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/transactions.rb:208:in `transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:1038:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:953:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:949:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:949:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:807:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:785:in `migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/redmine_prod/lib/redmine/plugin.rb:453:in `migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:466:in `each'
/var/www/redmine_prod/lib/redmine/plugin.rb:466:in `migrate'
/var/www/redmine_prod/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
ActiveRecord::StatementInvalid: TinyTds::Error: An expression of non-boolean type specified in a context where a condition is expected, near 'limit'.: EXEC sp_executesql N'UPDATE [dmsf_workflows] SET created_on = updated_on, author_id = (select id from users where admin limit 1); SELECT @@ROWCOUNT AS AffectedRows'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `handle_to_names_and_values_dblib'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:412:in `handle_to_names_and_values'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:385:in `_raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:380:in `block in raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:380:in `raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:363:in `do_exec_query'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:22:in `exec_query'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:82:in `exec_update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:40:in `exec_update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation.rb:326:in `update_all'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/querying.rb:8:in `update_all'
/var/www/redmine_prod/plugins/redmine_dmsf/db/migrate/20160222140401_approval_workflow_std_fields.rb:30:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:558:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:598:in `exec_migration'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:578:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:577:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:752:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:1038:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/transactions.rb:208:in `transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:1038:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:953:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:949:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:949:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:807:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:785:in `migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/redmine_prod/lib/redmine/plugin.rb:453:in `migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:466:in `each'
/var/www/redmine_prod/lib/redmine/plugin.rb:466:in `migrate'
/var/www/redmine_prod/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
TinyTds::Error: An expression of non-boolean type specified in a context where a condition is expected, near 'limit'.
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `handle_to_names_and_values_dblib'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:412:in `handle_to_names_and_values'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:385:in `_raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:380:in `block in raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:380:in `raw_select'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:363:in `do_exec_query'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:22:in `exec_query'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:82:in `exec_update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:40:in `exec_update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation.rb:326:in `update_all'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/querying.rb:8:in `update_all'
/var/www/redmine_prod/plugins/redmine_dmsf/db/migrate/20160222140401_approval_workflow_std_fields.rb:30:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:558:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:598:in `exec_migration'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:578:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:577:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:752:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:1038:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/transactions.rb:208:in `transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:1038:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:953:in `block in migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:949:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:949:in `migrate'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:807:in `up'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/migration.rb:785:in `migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/redmine_prod/lib/redmine/plugin.rb:453:in `migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/redmine_prod/lib/redmine/plugin.rb:466:in `each'
/var/www/redmine_prod/lib/redmine/plugin.rb:466:in `migrate'
/var/www/redmine_prod/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

Tried to look for others with same problem without luck. Any help appreciated.

Regards - Allan

**Comment by picman** [comment]
Could you please try to modify db/migration/20160222140401_approval_workflow_std_fields.rb as follows and then re-run the migration?

``` ruby
class ApprovalWorkflowStdFields < ActiveRecord::Migration
  def self.up
    add_column :dmsf_workflows, :updated_on, :timestamp
    add_column :dmsf_workflows, :created_on, :datetime
    add_column :dmsf_workflows, :author_id, :integer
    DmsfWorkflow.reset_column_information
    # Set updated_on
    DmsfWorkflow.all.each(&:touch)
    # Set created_on and author_id
--    DmsfWorkflow.update_all 'created_on = updated_on, author_id = (select id from users where admin limit 1)'
++    admin = User.active.where(admin: true).first
++    DmsfWorkflow.update_all "created_on = updated_on, author_id = #{admin.id}" if admin
  end

  def self.down
    remove_column :dmsf_workflows, :updated_on
    remove_column :dmsf_workflows, :created_on
    remove_column :dmsf_workflows, :author_id
  end
end
```

**Comment by bartroff** [comment]
Excellent, works! Thank you for the fast support.

**Comment by picman** [comment]
Thank you for testing it.
