### ISSUE TITLE
Getting 500 Internal Server Error - undefined method `sanitize_forbidden_attributes'

### ISSUE THREAD

**Issue by bartroff** [danmunn/redmine_dmsf#709]
Hi all,

Recently installed 1.5.9 on Redmine 3.3.2 using MSSQL 2008 db via. activerecord.

The plugin installs just fine and migration runs perfectly as well. The plugin can be configured just fine from WebUI, however when I try to access the DMSF tab on my projects, I get the following error in the browser:

```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
..
```

In production.log i get the following:

```
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (61.5ms)
Completed 500 Internal Server Error in 186ms

ActionView::Template::Error (undefined method `sanitize_forbidden_attributes' for #<DmsfFolder:0x007f6592ced750>
Did you mean?  sanitize_for_mass_assignment):
    92:         <%= submit_tag(l(:button_delete), :title => l(:title_delete_checked), :name => 'delete_entries') if @file_delete_allowed %>
    93:     <% end %>
    94:   </div>
    95:   <% values = @folder ? @folder.custom_field_values : @parent ? @parent.custom_field_values : DmsfFolder.new(:project => @project).custom_field_values %>
    96:   <% unless values.empty? %>
    97:     <div id="dmsf_tag" class="dmsf_controls" style="float: right">
    98:       <%= custom_field_tag_with_label(
  plugins/redmine_dmsf/app/views/dmsf/show.html.erb:95:in `block in _plugins_redmine_dmsf_app_views_dmsf_show_html_erb__2674787115672493992_70037115427160'
  plugins/redmine_dmsf/app/views/dmsf/show.html.erb:85:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb__2674787115672493992_70037115427160'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:58:in `block (2 levels) in show'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:56:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

I checked permissions on directories etc. and could not find anything so far.

Any help appreciated.

Thanks - Allan

**Comment by picman** [comment]
First of all I must say that MS SQL 2008 has been a very bad choice. Why do you use 11 old database and not an up to date MySQL, MariaDB, PostgreSQL,...?

**Comment by picman** [comment]
Could you modify the code in _plugins/redmine_dmsf/app/views/dmsf/show.html.erb_ as follows and to test it. If it helps, I will modify the source code.

```ruby
95 -- <% values = @folder ? @folder.custom_field_values : DmsfFolder.new(:project => @project).custom_field_values %>
95 ++ <% values = @folder ? @folder.custom_field_values : DmsfFolder.new.custom_field_values %>
```

**Comment by bartroff** [comment]
While I agree completely, this was unfortunately the circumstances I was given. Personally I would prefer MySQL. On the other hand, If I run into unsolvable problems I fully understand.

Anyway, I tested your suggestion and get this error now.

```
Completed 500 Internal Server Error in 108ms

ActionView::Template::Error (undefined method `sanitize_forbidden_attributes' for #<DmsfFolder:0x000000052ce188>
Did you mean?  sanitize_for_mass_assignment):
    92:         <%= submit_tag(l(:button_delete), :title => l(:title_delete_checked), :name => 'delete_entries') if @file_delete_allowed %>
    93:     <% end %>
    94:   </div>
    95:   <% values = @folder ? @folder.custom_field_values : DmsfFolder.new.custom_field_values %>
    96:   <% unless values.empty? %>
    97:     <div id="dmsf_tag" class="dmsf_controls" style="float: right">
    98:       <%= custom_field_tag_with_label(
  plugins/redmine_dmsf/app/views/dmsf/show.html.erb:95:in `block in _plugins_redmine_dmsf_app_views_dmsf_show_html_erb___544961540559935988_49403760'
  plugins/redmine_dmsf/app/views/dmsf/show.html.erb:85:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb___544961540559935988_49403760'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:58:in `block (2 levels) in show'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:56:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

Thank you for your help so far

**Comment by picman** [comment]
Hm, strange. The problem doesn't seem to be related to the database at all but with Rails. What version of Rails do you use? Rails 4.2 is required and it should contain the _sanitize_forbidden_attributes method_.

https://apidock.com/rails/v4.1.8/ActiveModel/ForbiddenAttributesProtection/sanitize_forbidden_attributes

**Comment by bartroff** [comment]
I believe you are right - running an old rails version. Will look into that and revert

**Comment by picman** [comment]
Okay. Closed.
