### ISSUE TITLE
Internal error 500 when uploading document via Edit issue

### ISSUE THREAD

**Issue by RealEnder** [danmunn/redmine_dmsf#728]
The errorlog contents:
```
App 21761 stderr: Started PATCH "/issues/1755" for 10.240.XXX.XXX at 2017-05-29 11:04:06 +0300
App 21761 stderr: Processing by IssuesController#update as HTML
App 21761 stderr:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"JGIIQbXXX", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "project_id"=>"12", "tracker_id"=>"2", "subject"=>"Добавяне на нова функционалност №1", "description"=>"", "status_id"=>"1", "priority_id"=>"4", "assigned_to_id"=>"", "category_id"=>"", "parent_issue_id"=>"", "start_date"=>"2014-03-05", "due_date"=>"2014-03-13", "estimated_hours"=>"5.0", "done_ratio"=>"20", "notes"=>"", "private_notes"=>"0", "lock_version"=>"1"}, "was_default_status"=>"1", "dmsf_attachments"=>{"dummy"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x007f29adf818e8 @tempfile=#<Tempfile:/tmp/RackMultipart20170529-21779-emtr5k.cer>, @original_filename="cert.cer", @content_type="application/pkix-cert", @headers="Content-Disposition: form-data; name=\"dmsf_attachments[dummy][file]\"; filename=\"cert.cer\"\r\nContent-Type: application/pkix-cert\r\n">}}, "last_journal_id"=>"255", "commit"=>"Submit", "issue_position"=>"1", "issue_count"=>"1", "id"=>"1755"}
App 21761 stderr:   Current user: alex (id=6)
App 21761 stderr: An attachment not found by its token: 
App 21761 stderr: Completed 500 Internal Server Error in 50ms (ActiveRecord: 8.1ms)
App 21761 stderr: 
App 21761 stderr: NoMethodError (undefined method `disk_filename' for nil:NilClass):
App 21761 stderr:   plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:59:in `block in controller_issues_after_save'
App 21761 stderr:   plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:57:in `each_value'
App 21761 stderr:   plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:57:in `controller_issues_after_save'
App 21761 stderr:   plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:44:in `controller_issues_edit_after_save'
App 21761 stderr:   lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
App 21761 stderr:   lib/redmine/hook.rb:61:in `each'
App 21761 stderr:   lib/redmine/hook.rb:61:in `block in call_hook'
App 21761 stderr:   lib/redmine/hook.rb:58:in `tap'
App 21761 stderr:   lib/redmine/hook.rb:58:in `call_hook'
App 21761 stderr:   lib/redmine/hook.rb:91:in `call_hook'
App 21761 stderr:   app/controllers/issues_controller.rb:523:in `block in save_issue_with_child_records'
App 21761 stderr:   app/controllers/issues_controller.rb:510:in `save_issue_with_child_records'
App 21761 stderr:   app/controllers/issues_controller.rb:179:in `update'
App 21761 stderr:   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Redmine version: 3.3.2.stable
Ruby version: 2.2.4-p230
DMSF version: 1.5.9

**Comment by RealEnder** [comment]
[This](https://www.redmine.org/boards/2/topics/52676) question might be linked to the issue. If user does not have upload access to Documents, he shouldn't see "Documents" upload section when editing issue.
The above log is with administrative account.

**Comment by picman** [comment]
I'm afraid that this new feature is still buggy. I recommend switching it of in the plugin option (Act as attachable).
Anyway, thank you for your feedback, I will reflect that in 1.6.0/

**Comment by RealEnder** [comment]
Thanks for the points!
I don't see Act as attachable option in DMSF settings, maybe haven't done upgrade process in right way? Other 1.5.9 options are here (like Memcached server address and No versioning files patterns for example)

**Comment by picman** [comment]
Pull the master branch:

![image](https://cloud.githubusercontent.com/assets/779003/26547670/76ae98cc-4470-11e7-834f-7b27aa72922d.png)
