### ISSUE TITLE
Uninstalling redmine_dmsf fails when using PostgreSQL as the database

### ISSUE THREAD

**Issue by gnn** [danmunn/redmine_dmsf#771]
When trying to uninstall `redmine_dmsf`, the down migration step fails with the following error:

```.linenos
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedObject: ERROR:  type "unsigned" does not exist
LINE 1: SELECT dmsf_files.id, cast(dmsf_folders.title as unsigned) F...
                                                         ^
: SELECT dmsf_files.id, cast(dmsf_folders.title as unsigned) FROM "dmsf_files" INNER JOIN "dmsf_folders" ON "dmsf_folders"."id" = "dmsf_files"."dmsf_folder_id" WHERE "dmsf_folders"."system" = $1
REDMINE_ROOT/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:72:in `down'
REDMINE_ROOT/lib/redmine/plugin.rb:481:in `migrate_plugin'
REDMINE_ROOT/lib/redmine/plugin.rb:453:in `migrate'
REDMINE_ROOT/lib/redmine/plugin.rb:464:in `migrate'
REDMINE_ROOT/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  type "unsigned" does not exist
LINE 1: SELECT dmsf_files.id, cast(dmsf_folders.title as unsigned) F...
                                                         ^
: SELECT dmsf_files.id, cast(dmsf_folders.title as unsigned) FROM "dmsf_files" INNER JOIN "dmsf_folders" ON "dmsf_folders"."id" = "dmsf_files"."dmsf_folder_id" WHERE "dmsf_folders"."system" = $1
REDMINE_ROOT/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:72:in `down'
REDMINE_ROOT/lib/redmine/plugin.rb:481:in `migrate_plugin'
REDMINE_ROOT/lib/redmine/plugin.rb:453:in `migrate'
REDMINE_ROOT/lib/redmine/plugin.rb:464:in `migrate'
REDMINE_ROOT/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
PG::UndefinedObject: ERROR:  type "unsigned" does not exist
LINE 1: SELECT dmsf_files.id, cast(dmsf_folders.title as unsigned) F...
                                                         ^
REDMINE_ROOT/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:72:in `down'
REDMINE_ROOT/lib/redmine/plugin.rb:481:in `migrate_plugin'
REDMINE_ROOT/lib/redmine/plugin.rb:453:in `migrate'
REDMINE_ROOT/lib/redmine/plugin.rb:464:in `migrate'
REDMINE_ROOT/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
Migrating redmine_dmsf (DMSF)...
== 20170421101901 DmsfFileContainerRollback: reverting ========================
```

After a bit of searching, it seems that the culprit is PostgreSQL not having an `unsigned` type.

| Package | Version |
|---------------- | -------------: |
| PostgreSQL | 9.5 |
| Redmine      | 3.4.2 |
| redmine_dmsf | v1.6.0 |

**Comment by gnn** [comment]
FWIW, I fixed it simply by changing `unsigned` to `int`. If you don't need the whole `unsigned` range and don't think you will run into conversion issues, that should be OK.
Doing so uncovers another bug (actually two) in a follow up migration where default values are of the wrong type and a `CASE` statement wasn't used syntactically correct. I'll report those bugs in a new issue. And since I fixed these too: pull requests inbound.
