### ISSUE TITLE
SQL error on Document workflow approve

### ISSUE THREAD

**Issue by danaivehr** [danmunn/redmine_dmsf#777]
Redmine 3.4
DMSF 1.6
PostgreSQL 9.6.2

Steps to reproduce:
* Create simple one-step workflow
* Assign workflow to a document and go throw approval

Actual result:

On the last step Internal server error is catched.

Logs:

```
ActionView::Template::Error (PG::DatatypeMismatch: ERROR:  argument of WHERE must be type boolean, not type integer
LINE 1: ...ctions"."dmsf_workflow_step_assignment_id" WHERE (dmsf_workf...
                                                             ^
: SELECT  "dmsf_workflow_step_actions".* FROM "dmsf_workflow_step_actions" INNER JOIN "dmsf_workflow_step_assignments" ON "dmsf_workflow_step_assignments"."id" = "dmsf_workflow_step_actions"."dmsf_workflow_step_assignment_id" WHERE (dmsf_workflow_step_assignments.dmsf_file_revision_id)  ORDER BY dmsf_workflow_step_actions.id DESC LIMIT 1):
    67:           :project_id => project.id,
    68:           :id => wf.id,
    69:           :dmsf_file_revision_id => file.last_revision.id),
    70:         :title => file.last_revision.workflow_tooltip,
    71:         :remote => true) %>
    72:     <% else %>
    73:       <%= file.last_revision.workflow_str(false) %>
  plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:338:in `workflow_tooltip'
  plugins/redmine_dmsf/app/views/dmsf/_file.html.erb:70:in `_plugins_redmine_dmsf_app_views_dmsf__file_html_erb__1182187383483309037_69865503632740'
  plugins/redmine_dmsf/app/views/dmsf/_dmsf_rows.erb:56:in `block in _plugins_redmine_dmsf_app_views_dmsf__dmsf_rows_erb__754068664561884144_69865508469700'
  plugins/redmine_dmsf/app/views/dmsf/_dmsf_rows.erb:2:in `each'
  plugins/redmine_dmsf/app/views/dmsf/_dmsf_rows.erb:2:in `_plugins_redmine_dmsf_app_views_dmsf__dmsf_rows_erb__754068664561884144_69865508469700'
  plugins/redmine_dmsf/app/views/dmsf/_tree_view.erb:67:in `_plugins_redmine_dmsf_app_views_dmsf__tree_view_erb___188343844955355417_69865505565680'
  plugins/redmine_dmsf/app/views/dmsf/show.html.erb:115:in `block in _plugins_redmine_dmsf_app_views_dmsf_show_html_erb___779551273849928599_69865513358920'
  plugins/redmine_dmsf/app/views/dmsf/show.html.erb:86:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb___779551273849928599_69865513358920'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:66:in `block (2 levels) in show'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:64:in `show'

```

Seems to be something wrong in plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:338
statement:
```
action = DmsfWorkflowStepAction.joins(:dmsf_workflow_step_assignment).where(
            ['dmsf_workflow_step_assignments.dmsf_file_revision_id', self.id]).order('dmsf_workflow_step_actions.id').last
```

All went smooth when i changed it to `'dmsf_workflow_step_assignments.dmsf_file_revision_id = ?'`, but not really sure that was correct.

**Comment by picman** [comment]
Fixed. Thank you for the bug report!
