### ISSUE TITLE
Install fails with new Redmine installation and SQLite

### ISSUE THREAD

**Issue by mcondarelli** [danmunn/redmine_dmsf#780]
Trying to install from git I get the following error, what am I doing wrong?

```
[root@localhost redmine]# bundle exec rake redmine:plugins:migrate RAILS_ENV="production" --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
Migrating redmine_dmsf (DMSF)...
== 7 Dmsf144: migrating =======================================================
-- add_column(:dmsf_file_locks, :entity_type, :integer, {:null=>true})
   -> 0.0007s
-- add_column(:dmsf_file_locks, :lock_type_cd, :integer, {:null=>true})
   -> 0.0003s
-- add_column(:dmsf_file_locks, :lock_scope_cd, :integer, {:null=>true})
   -> 0.0002s
-- add_column(:dmsf_file_locks, :uuid, :string, {:null=>true, :limit=>36})
   -> 0.0003s
-- add_column(:dmsf_file_locks, :expires_at, :datetime, {:null=>true})
   -> 0.0003s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: misuse of aliased aggregate id: SELECT MAX(id) id FROM "dmsf_file_locks" GROUP BY "dmsf_file_locks"."dmsf_file_id"  ORDER BY MAX(id) DESC
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:284:in `block in exec_query'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.2.5/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:281:in `exec_query'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/querying.rb:39:in `find_by_sql'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:639:in `exec_queries'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:515:in `load'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:243:in `to_a'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/opt/redmine-3.4/plugins/redmine_dmsf/db/migrate/07_dmsf_1_4_4.rb:52:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.4/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:467:in `block in migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:466:in `each'
/opt/redmine-3.4/lib/redmine/plugin.rb:466:in `migrate'
/opt/redmine-3.4/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `call'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.2.5/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'
ActiveRecord::StatementInvalid: SQLite3::SQLException: misuse of aliased aggregate id: SELECT MAX(id) id FROM "dmsf_file_locks" GROUP BY "dmsf_file_locks"."dmsf_file_id"  ORDER BY MAX(id) DESC
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:284:in `block in exec_query'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.2.5/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:281:in `exec_query'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/querying.rb:39:in `find_by_sql'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:639:in `exec_queries'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:515:in `load'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:243:in `to_a'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/opt/redmine-3.4/plugins/redmine_dmsf/db/migrate/07_dmsf_1_4_4.rb:52:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.4/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:467:in `block in migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:466:in `each'
/opt/redmine-3.4/lib/redmine/plugin.rb:466:in `migrate'
/opt/redmine-3.4/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `call'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.2.5/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'
SQLite3::SQLException: misuse of aliased aggregate id
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/usr/local/rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:284:in `block in exec_query'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.2.5/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:281:in `exec_query'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/querying.rb:39:in `find_by_sql'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:639:in `exec_queries'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:515:in `load'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation.rb:243:in `to_a'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/opt/redmine-3.4/plugins/redmine_dmsf/db/migrate/07_dmsf_1_4_4.rb:52:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.4/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:467:in `block in migrate'
/opt/redmine-3.4/lib/redmine/plugin.rb:466:in `each'
/opt/redmine-3.4/lib/redmine/plugin.rb:466:in `migrate'
/opt/redmine-3.4/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `call'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/usr/local/rvm/gems/ruby-2.2.5/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.2.5/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
```

**Comment by picman** [comment]
Could you modify the line 51 in db/migrate/07_dmsf_1_4_4.rb as follows and re-run the migration?

```ruby
  49  DmsfFileLock.select('MAX(id) id').
  50     order('MAX(id) DESC').
--51      group('dmsf_file_id').
++51      group('dmsf_file_id, id').
  52      each do |lock|
  53      lock.reload 
  54      if (lock.locked)
  55        do_not_delete << lock.id
  56      end
57    end
```

**Comment by mcondarelli** [comment]
Apparently the following patch (divined from previous commits) cures the problem:
```
diff --git a/db/migrate/07_dmsf_1_4_4.rb b/db/migrate/07_dmsf_1_4_4.rb
index 6fc07ba..b03453c 100644
--- a/db/migrate/07_dmsf_1_4_4.rb
+++ b/db/migrate/07_dmsf_1_4_4.rb
@@ -46,9 +46,9 @@ class Dmsf144 < ActiveRecord::Migration
     #               data into it, which should enable us to run checks we need, not as
     #               efficient, however compatible across the board.
     DmsfFileLock.reset_column_information
-    DmsfFileLock.select('MAX(id) id').
-      order('MAX(id) DESC').
-      group('dmsf_file_id').
+    DmsfFileLock.select('MAX(dmsf_file_locks.id) id').
+      order('MAX(dmsf_file_locks.id) DESC').
+      group('dmsf_file_locks.dmsf_file_id').
       each do |lock|
       lock.reload 
       if (lock.locked)
````
I cannot rerun migration because I already solved (somehow) the problem.

I'm not sure this is the "Right Way" to do it, though.

**Comment by picman** [comment]
I think the problem was in a missing `id` column in `GROUP BY` as all non aggregated columns used in `SELECT` must be present in `GROUP BY`.
Fixed.
Thank you for the bug report.
