### ISSUE TITLE
Centos7 (non-RVM) installation fails

### ISSUE THREAD

**Issue by mcondarelli** [danmunn/redmine_dmsf#781]
I tried a (almost) complete Redmine reinstall using standard Centos7 packages (first try was using RVM, which, obviously has more up-to-date gersions of almost everything).

General installation seems OK, but installing DMSF I get the following error, probably due to some version incompatibility.

Can You help?

```
[mcondarelli@localhost plugins]$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
(in /opt/redmine-3.4.2)
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'redmine_extensions'.
Gem Load Error is: undefined method `require_dependency' for main:Object
Backtrace for gem load error is:
/home/mcondarelli/.gem/ruby/gems/redmine_extensions-0.1.07/lib/redmine_extensions/redmine_patches/patches.rb:3:in `block in <top (required)>'
/home/mcondarelli/.gem/ruby/gems/redmine_extensions-0.1.07/lib/redmine_extensions/redmine_patches/patches.rb:2:in `each'
/home/mcondarelli/.gem/ruby/gems/redmine_extensions-0.1.07/lib/redmine_extensions/redmine_patches/patches.rb:2:in `<top (required)>'
/home/mcondarelli/.gem/ruby/gems/redmine_extensions-0.1.07/lib/redmine_extensions/engine.rb:2:in `require'
/home/mcondarelli/.gem/ruby/gems/redmine_extensions-0.1.07/lib/redmine_extensions/engine.rb:2:in `<top (required)>'
/home/mcondarelli/.gem/ruby/gems/redmine_extensions-0.1.07/lib/redmine_extensions.rb:1:in `require'
/home/mcondarelli/.gem/ruby/gems/redmine_extensions-0.1.07/lib/redmine_extensions.rb:1:in `<top (required)>'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:83:in `require'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:83:in `block (2 levels) in require'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `each'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `block in require'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `each'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `require'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler.rb:114:in `require'
/opt/redmine-3.4.2/config/application.rb:5:in `<top (required)>'
/opt/redmine-3.4.2/Rakefile:5:in `require'
/opt/redmine-3.4.2/Rakefile:5:in `<top (required)>'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/rake_module.rb:29:in `load'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/application.rb:688:in `raw_load_rakefile'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/application.rb:97:in `block in load_rakefile'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/application.rb:96:in `load_rakefile'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/application.rb:80:in `block in run'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/home/mcondarelli/.gem/ruby/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/usr/bin/rake:37:in `<top (required)>'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `load'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:28:in `run'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:424:in `exec'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:27:in `dispatch'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:18:in `start'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/exe/bundle:30:in `block in <top (required)>'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/exe/bundle:22:in `<top (required)>'
/home/mcondarelli/bin/bundle:23:in `load'
/home/mcondarelli/bin/bundle:23:in `<main>'
Bundler Error Backtrace:
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:86:in `rescue in block (2 levels) in require'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `each'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `block in require'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `each'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `require'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler.rb:114:in `require'
/opt/redmine-3.4.2/config/application.rb:5:in `<top (required)>'
/opt/redmine-3.4.2/Rakefile:5:in `require'
/opt/redmine-3.4.2/Rakefile:5:in `<top (required)>'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `load'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:28:in `run'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:424:in `exec'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:27:in `dispatch'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:18:in `start'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/exe/bundle:30:in `block in <top (required)>'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/mcondarelli/.gem/ruby/gems/bundler-1.16.0.pre.3/exe/bundle:22:in `<top (required)>'
/home/mcondarelli/bin/bundle:23:in `load'
/home/mcondarelli/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
[mcondarelli@localhost plugins]$ 
```

**Comment by picman** [comment]
The error seems to be related to redmine_extensions plugin, not DMSF itself.
As a workaround I'd suggest commenting out the gem in `Gemfile`:

```ruby
    source 'https://rubygems.org'

     gem 'rubyzip', '>= 1.0.0'
     gem 'zip-zip'
     gem 'simple_enum'
     gem 'uuidtools'
     gem 'dav4rack'
     gem 'dalli'
--   gem 'redmine_extensions' unless Dir.exist?(File.expand_path('../../easyproject', __FILE__))
++   #gem 'redmine_extensions' unless Dir.exist?(File.expand_path('../../easyproject', __FILE__))
```

**Comment by mcondarelli** [comment]
Thanks.

It worked.
