### ISSUE TITLE
Weird db:migrate

### ISSUE THREAD

**Issue by n-rodriguez** [danmunn/redmine_dmsf#796]
Hi!

I've installed redmine_dmsf and everything went fine but now when I run `rake db:migrate` I got this :

```
redmine@localhost:~/current$ bundle exec rake db:migrate RAILS_ENV=production 
== 20150705172511 CreateEasySettings: migrating ===============================
-- table_exists?(:easy_settings)
   -> 0.0019s
-- create_table(:easy_settings)
   -> 0.2592s
-- index_exists?(:easy_settings, [:name, :project_id], {:unique=>true})
   -> 0.0013s
-- add_index(:easy_settings, [:name, :project_id], {:unique=>true})
   -> 0.0202s
== 20150705172511 CreateEasySettings: migrated (0.2832s) ======================

== 20160519161300 CreateEntityAssignments: migrating ==========================
-- table_exists?(:easy_entity_assignments)
   -> 0.0023s
-- create_table(:easy_entity_assignments)
   -> 0.0934s
-- add_index(:easy_entity_assignments, [:entity_from_type, :entity_from_id, :entity_to_type, :entity_to_id], {:name=>"entity_assignment_idx", :unique=>true})
   -> 0.0225s
-- add_index(:easy_entity_assignments, :entity_from_id, {:name=>"entity_assignment_idx_from"})
   -> 0.0215s
-- add_index(:easy_entity_assignments, :entity_to_id, {:name=>"entity_assignment_idx_to"})
   -> 0.0165s
== 20160519161300 CreateEntityAssignments: migrated (0.1570s) =================

rake aborted!
NoMethodError: undefined method `column' for #<Foreigner::ConnectionAdapters::ForeignKeyDefinition:0x000000000b5b6ae8>
Did you mean?  count
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:219:in `block in foreign_keys'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:213:in `map'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:213:in `foreign_keys'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:103:in `block in tables'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:102:in `each'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:102:in `tables'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/foreigner-1.7.4/lib/foreigner/schema_dumper.rb:49:in `tables_with_foreign_keys'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:38:in `dump'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:22:in `dump'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:240:in `block (4 levels) in <top (required)>'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:239:in `open'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:239:in `block (3 levels) in <top (required)>'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:52:in `block (2 levels) in <top (required)>'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
/data/www/redmine/.rvm/gems/ruby-2.3.5/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/data/www/redmine/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `eval'
/data/www/redmine/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
```

Thank you!

**Comment by picman** [comment]
Why do you think it's related to DMSF? The error is reported from a migration of a different plugin.

**Comment by n-rodriguez** [comment]
Because of this : https://github.com/danmunn/redmine_dmsf/blob/master/Gemfile#L31 and this https://github.com/easyredmine/redmine_extensions/tree/master/db/migrate

**Comment by n-rodriguez** [comment]
> The error is reported from a migration of a different plugin.

Yes, but the error happens **after** Redmine DMSF installation.

**Comment by n-rodriguez** [comment]
BTW I don't use [easyproject](https://www.easyproject.com) or stuff like that.

**Comment by picman** [comment]
Comment the dependency in the Gemfile and try again.
```ruby
source 'https://rubygems.org'

gem 'rubyzip', '>= 1.0.0'
gem 'zip-zip'
  gem 'simple_enum'
  gem 'uuidtools'
  gem 'dav4rack'
  gem 'dalli'
- gem 'redmine_extensions' unless Dir.exist?(File.expand_path('../../easyproject', __FILE__))
+ #gem 'redmine_extensions' unless Dir.exist?(File.expand_path('../../easyproject', __FILE__))
```

**Comment by n-rodriguez** [comment]
Thank you!
