### ISSUE TITLE
CookieOverflow multi upload

### ISSUE THREAD

**Issue by flybyray** [danmunn/redmine_dmsf#816]
When uploading a bunch of files (e.g. 207 files total size of 11m). the commit files dialog will show all uploaded files. if you commit them this failure occures:
the same upload works well with a older version of the plugin (1.5).
this error is only shown in the log file. the browser shows a totaly different message. but each file failed file is saved in database.

```
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):

  actionpack (4.2.8) lib/action_dispatch/middleware/cookies.rb:529:in `[]='
  actionpack (4.2.8) lib/action_dispatch/middleware/session/cookie_store.rb:110:in `set_cookie'
  rack (1.6.8) lib/rack/session/abstract/id.rb:351:in `commit_session'
  rack (1.6.8) lib/rack/session/abstract/id.rb:226:in `context'
  rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.8) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.8) lib/rack/content_length.rb:15:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/application.rb:165:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  rack (1.6.8) lib/rack/content_length.rb:15:in `call'
  rack (1.6.8) lib/rack/handler/webrick.rb:88:in `service'
```

**Comment by flybyray** [comment]
ok we startet with 1.6 since its release on 12th september 2017 (which was tagged there)
https://github.com/danmunn/redmine_dmsf/commit/da86694358160cbcbc9b87ae015a44d503c645be

now the same tag points to
https://github.com/danmunn/redmine_dmsf/commit/4382cd71b506eb63796b3b686c2c021080287087

we could track the error down to this fix:
https://github.com/danmunn/redmine_dmsf/issues/786

would be nice to have some clear versioning or tagging.
retagging or moving tags is bad practice (ok for development stuff but not for released code).

thanks for your work and 
Happy Christmas!
