### ISSUE TITLE
Fix your bug with undefined method `title_format' 

### ISSUE THREAD

**Issue by Piduna** [danmunn/redmine_dmsf#833]
When i am trying to edit setting of projects, i have (internal error). In `production.log`:

```
ActionView::Template::Error (undefined method `title_format' for #<Member:0x00560cf0a29b00>):
    21: <% member = @project.members.where(:user_id => User.current.id).first %>
    22: <% if member %>
    23:   <% mail_notification = member.dmsf_mail_notification %>
    24:   <% title_format = member.title_format %>
    25: <% end %>
    26:
    27: <%= form_tag(dmsf_user_pref_save_path(@project)) do %>
  plugins/redmine_dmsf/app/views/dmsf_state/_user_pref.html.erb:24:in `_plugins_redmine_dmsf_app_views_dmsf_state__user_pref_html_erb___1766231749538446368_47306788194720'
  app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb__1230859515936367297_47306727171800'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb__1230859515936367297_47306727171800'
  app/helpers/application_helper.rb:345:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__2191057054410634214_47306725931200'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

In `redmine_dmsf/app/views/dmsf_state/_user_pref.html.erb` , please replace
this
`<% title_format = member.title_format %>` on this `<% title_format = member.dmsf_title_format %>`

**Comment by picman** [comment]
Try git pull. It has been already fixed: 0e83f00.
