### ISSUE TITLE
No such file or directory @ rb_file_s_size

### ISSUE THREAD

**Issue by thejulian** [danmunn/redmine_dmsf#863]
When i upload several Files I get the following Error:

```
Started POST "/projects/sysadmin/dmsf/upload/file" for 10.0.1.35 at 2018-05-24 09:34:08 +0200
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"backup_201804.zip", "authenticity_token"=>"UpGNzrRLa/27gqC6jOSk0I5PxS7I41jPuDTS41+ule8F1LRrsQjCXopDJZ7IECcCKHnJO7FBOJPP3wQOP7K3AQ==", "file"=>#<ActionDispatch::Http::UploadedFile:0x00000003f9f5f8 @tempfile=#<Tempfile:/tmp/RackMultipart20180524-22047-1bms8fa.zip>, @original_filename="backup_201804.zip", @content_type="application/zip", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"backup_201804.zip\"\r\nContent-Type: application/zip\r\n">, "id"=>"sysadmin"}
  Current user: username (id=198)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (0.9ms)
Completed 200 OK in 327ms (Views: 32.5ms | ActiveRecord: 42.3ms)
Started POST "/projects/sysadmin/dmsf/upload/file" for 10.0.1.35 at 2018-05-24 09:34:09 +0200
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"boostmine-1-2.zip", "authenticity_token"=>"UpGNzrRLa/27gqC6jOSk0I5PxS7I41jPuDTS41+ule8F1LRrsQjCXopDJZ7IECcCKHnJO7FBOJPP3wQOP7K3AQ==", "file"=>#<ActionDispatch::Http::UploadedFile:0x00000003ae67c8 @tempfile=#<Tempfile:/tmp/RackMultipart20180524-22047-rgqg50.zip>, @original_filename="boostmine-1-2.zip", @content_type="application/zip", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"boostmine-1-2.zip\"\r\nContent-Type: application/zip\r\n">, "id"=>"sysadmin"}
  Current user: username (id=198)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (0.1ms)
Completed 200 OK in 38ms (Views: 0.7ms | ActiveRecord: 18.2ms)
Started POST "/projects/sysadmin/dmsf/upload/file" for 10.0.1.35 at 2018-05-24 09:34:21 +0200
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"debian-9.3.0-amd64-netinst.iso", "authenticity_token"=>"UpGNzrRLa/27gqC6jOSk0I5PxS7I41jPuDTS41+ule8F1LRrsQjCXopDJZ7IECcCKHnJO7FBOJPP3wQOP7K3AQ==", "file"=>#<ActionDispatch::Http::UploadedFile:0x000000027d9270 @tempfile=#<Tempfile:/tmp/RackMultipart20180524-22047-1oopcml.iso>, @original_filename="debian-9.3.0-amd64-netinst.iso", @content_type="application/x-cd-image", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"debian-9.3.0-amd64-netinst.iso\"\r\nContent-Type: application/x-cd-image\r\n">, "id"=>"sysadmin"}
  Current user: username (id=198)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (0.1ms)
Completed 200 OK in 1203ms (Views: 0.7ms | ActiveRecord: 29.1ms)
Started POST "/projects/sysadmin/dmsf/upload/file" for 10.0.1.35 at 2018-05-24 09:34:24 +0200
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"Rekursion_Starterkit.zip", "authenticity_token"=>"UpGNzrRLa/27gqC6jOSk0I5PxS7I41jPuDTS41+ule8F1LRrsQjCXopDJZ7IECcCKHnJO7FBOJPP3wQOP7K3AQ==", "file"=>#<ActionDispatch::Http::UploadedFile:0x0000000388b398 @tempfile=#<Tempfile:/tmp/RackMultipart20180524-22047-wjdce3.zip>, @original_filename="Rekursion_Starterkit.zip", @content_type="application/zip", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"Rekursion_Starterkit.zip\"\r\nContent-Type: application/zip\r\n">, "id"=>"sysadmin"}
  Current user: username (id=198)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (0.2ms)
Completed 200 OK in 2740ms (Views: 1.1ms | ActiveRecord: 2724.8ms)
Started POST "/projects/sysadmin/dmsf/upload/files" for 10.0.1.35 at 2018-05-24 09:34:26 +0200
Processing by DmsfUploadController#upload_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"tVqEkt3HnDi9eR1+oqV9SP2V4vSu5fRZUXATneYxoCPiH7032IQ1m4y4mFrmUf6aW6Pu4ddHlAUmm8Vwhi2CzQ==", "view_mode_o_1ce8gl2n6cfr1l7715r35fqboc1"=>"on", "o_1ce8gl2n6cfr1l7715r35fqboc1_count"=>"0", "uploaded"=>{"1"=>{"disk_filename"=>"180524093408_backup_201804.zip", "content_type"=>"application/zip", "original_filename"=>"backup_201804.zip", "tempfile_path"=>"/tmp/RackMultipart20180524-22047-1bms8fa.zip"}, "2"=>{"disk_filename"=>"180524093409_boostmine-1-2.zip", "content_type"=>"application/zip", "original_filename"=>"boostmine-1-2.zip", "tempfile_path"=>"/tmp/RackMultipart20180524-22047-rgqg50.zip"}, "3"=>{"disk_filename"=>"180524093421_debian-9.3.0-amd64-netinst.iso", "content_type"=>"application/x-cd-image", "original_filename"=>"debian-9.3.0-amd64-netinst.iso", "tempfile_path"=>"/tmp/RackMultipart20180524-22047-1oopcml.iso"}, "4"=>{"disk_filename"=>"180524093426_Rekursion_Starterkit.zip", "content_type"=>"application/zip", "original_filename"=>"Rekursion_Starterkit.zip", "tempfile_path"=>"/tmp/RackMultipart20180524-22047-wjdce3.zip"}}, "id"=>"sysadmin"}
  Current user: username (id=198)
Completed 500 Internal Server Error in 297ms (ActiveRecord: 32.6ms)

Errno::ENOENT (No such file or directory @ rb_file_s_size - /tmp/RackMultipart20180524-22047-1bms8fa.zip):
  plugins/redmine_dmsf/app/models/dmsf_upload.rb:70:in `size'
  plugins/redmine_dmsf/app/models/dmsf_upload.rb:70:in `initialize'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:57:in `new'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:57:in `block in upload_files'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:56:in `each_value'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:56:in `upload_files'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

Files:
3 zips (50MB, 4MB, 1.8KB)
1 iso (290)

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

Version 1.6.0 DMSF (with changes of  #774 - https://github.com/danmunn/redmine_dmsf/commit/c51804f78fa2bf2225d1a578da4c76260f28fcac)

**Comment by picman** [comment]
How about an upgrade to 1.6.1?

**Comment by thejulian** [comment]
aren't their a lot of problems with this one and the dependencies?

**Comment by picman** [comment]
Try it. I'm not going to deal with problems in old releases.

**Comment by thejulian** [comment]
okay - I'll need some time.
On my Testsystem I can't reproduce the Error .. but the Testsystem isn't that big as the productive ..
But I'll upgrade the productive asap.
