### ISSUE TITLE
Installation of DMSF

### ISSUE THREAD

**Issue by JuergenFB** [danmunn/redmine_dmsf#868]
I try to install the DMSF plugin. When start the command

bundle exec rake redmine:plugins:migrate RAILS_ENV="production"

I get the error message:

```
bundle exec rake redmine:plugins:migrate RAILS_ENV="production" --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Reloader:Class
Did you mean?  to_param
/srv/www/redmine/trunk/plugins/redmine_dmsf/after_init.rb:81:in `<top (required)>'
/srv/www/redmine/trunk/plugins/redmine_dmsf/init.rb:70:in `require_relative'
/srv/www/redmine/trunk/plugins/redmine_dmsf/init.rb:70:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/srv/www/redmine/trunk/lib/redmine/plugin.rb:156:in `block in load'
/srv/www/redmine/trunk/lib/redmine/plugin.rb:147:in `each'
/srv/www/redmine/trunk/lib/redmine/plugin.rb:147:in `load'
/srv/www/redmine/trunk/config/initializers/30-redmine.rb:21:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `block in load'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:655:in `block in load_config_initializer'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:654:in `load_config_initializer'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:611:in `each'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `each'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `tsort_each_child'
/usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
/srv/www/redmine/trunk/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:329:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:237:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:212:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

I'm using Ubuntu 18.04 LTS, have installed Redmine from the repository
(trunk), bundle is version 1.16.1 and rake version 12.3.1

**Comment by ahorek** [comment]
hi, Redmine 4 isn't released yet, you shouldn't use it in production

try to change this line
https://github.com/danmunn/redmine_dmsf/blob/master/after_init.rb#L81
to
_RedmineExtensions::Reloader.to_prepare do_
and it should work

**Comment by JuergenFB** [comment]
After I use the latest stable version of Redmine anything work as expected.
