### ISSUE TITLE
super: no superclass method `project_settings_tabs' 

### ISSUE THREAD

**Issue by netmeeting** [danmunn/redmine_dmsf#882]
my Bitnami redmine infomation:
Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

when I updated dmsf version from V1.60 to V1.61, then clicked the project setting ,error shows ：
Redmine. Error 500
super: no superclass method `project_settings_tabs' for #<#<Class:0x00007f3c34b4d580>:0x00007f3c352b4198> Did you mean? project_settings_tabs_with_planner 
Error log:
 /opt/redmine-3.3.0-1/apps/redmine/htdocs/plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
/opt/redmine-3.3.0-1/apps/redmine/htdocs/plugins/usability/lib/usability/projects_helper_patch.rb:24:in `project_settings_tabs_with_usability'
/opt/redmine-3.3.0-1/apps/redmine/htdocs/app/views/projects/settings.html.erb:3:in `_08f751ecd7df6d0c9b71b832fa94d556'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:14:in `render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/opt/redmine-3.3.0-1/ruby/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/opt/redmine-3.3.0-1/apps/redmine/htdocs/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-raw-upload-1.1.1/lib/rack/raw_upload.rb:18:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/opt/redmine-3.3.0-1/apps/redmine/htdocs/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/opt/redmine-3.3.0-1/ruby/lib/ruby/gems/2.3.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

what should I do? thanks a lot!

**Comment by netmeeting** [comment]
got it,thank you very much!
