### ISSUE TITLE
Test fails due to missing table 'easy_settings'

### ISSUE THREAD

**Issue by liaham** [danmunn/redmine_dmsf#914]
Hello
I installed redmine_dmsf with no other plugins in redmine. When running plugins tests, I got the error:

ERROR["test_belongs_to_project", #<Minitest::Reporters::Suite:0x000055a228a4fe78 @name="DmsfLinksTest">, 0.6473323469981551]
 test_belongs_to_project#DmsfLinksTest (0.65s)
ActiveRecord::StatementInvalid:         ActiveRecord::StatementInvalid: Mysql2::Error: Table 'rm346_test.easy_settings' doesn't exist: SHOW FULL FIELDS FROM `easy_settings`
            test_after_commit (0.4.2) lib/test_after_commit.rb:27:in `block in transaction_with_transactional_fixtures'
            test_after_commit (0.4.2) lib/test_after_commit.rb:21:in `transaction_with_transactional_fixtures'
            lib/redmine/nested_set/project_nested_set.rb:105:in `destroy_without_nested_set_update'
            lib/redmine/nested_set/project_nested_set.rb:93:in `block in destroy_children'
            lib/redmine/nested_set/project_nested_set.rb:93:in `destroy_children'
            test_after_commit (0.4.2) lib/test_after_commit.rb:27:in `block in transaction_with_transactional_fixtures'
            test_after_commit (0.4.2) lib/test_after_commit.rb:21:in `transaction_with_transactional_fixtures'
            lib/redmine/nested_set/project_nested_set.rb:105:in `destroy_without_nested_set_update'
            lib/redmine/nested_set/project_nested_set.rb:93:in `block in destroy_children'
            lib/redmine/nested_set/project_nested_set.rb:93:in `destroy_children'
            test_after_commit (0.4.2) lib/test_after_commit.rb:27:in `block in transaction_with_transactional_fixtures'
            test_after_commit (0.4.2) lib/test_after_commit.rb:21:in `transaction_with_transactional_fixtures'
            plugins/redmine_dmsf/test/unit/dmsf_link_test.rb:123:in `test_belongs_to_project'

The gem redmine_extensions (0.2.14), where the migrations for the missing tables are defined, is installed.

Is there anybody having an idea what went wrong?

Regards
liaham

My setting:
Redmine version 3.4.6
Rails version 4.2.8
Ruby version 2.4.4
Environment development 
Database adaptaer mysql2

**Comment by picman** [comment]
Related to #856, #879, and #870.
Please see the issues mentioned above.

```bundle exec rake db:migrate RAILS_ENV=test```
