### ISSUE TITLE
Getting more parameters in dmsf_files

### ISSUE THREAD

**Issue by lpereira98** [danmunn/redmine_dmsf#926]
Hello everyone, 
Im a junior and just started with doing stuff with redmine.
My query:

> "GET /redmine/projects/nea_rari_18-013/dmsf.json?folder_id=9883&key=93d2018bc6364c0be371fc87d4fc175b0fd645d3 HTTP/1.1" 200 497

And works just fine, what i need is to get more parameters from dmsf_files objects.
![table](https://user-images.githubusercontent.com/44083899/48553765-64674380-e8d4-11e8-8bf7-8afa17280f40.png)
dmsf_files only returns it's id and name, but i wanna get it's version and modified date too, just like i have in DMSF table:
![bar](https://user-images.githubusercontent.com/44083899/48553816-8bbe1080-e8d4-11e8-9b6d-d5814f85fea1.PNG)
Best regards

**Comment by picman** [comment]
For such information you should call ```GET /dmsf/files/9313.xml```.

**Comment by lpereira98** [comment]
log:

> "GET /redmine/projects/project_example/dmsf/files/9313.xml?key=93d2018bc6364c0be371fc87d4fc175b0fd645d3 HTTP/1.1" 404 459

and i get the exception:
The remote server returned an error: (404) Not Found.

**Comment by picman** [comment]
It was just an example. I took an id from your screen-shot. Does a document of id 9313 exist?

**Comment by lpereira98** [comment]
Yes it does, the example was the response to:
> "GET /redmine/projects/project_example/dmsf.json?folder_id=9883&key=93d2018bc6364c0be371fc87d4fc175b0fd645d3 HTTP/1.1" 200 497
But the json response only returns id and name in dmsf_files table and i need more parameters

**Comment by picman** [comment]
I don't know. Check the log file. The following command should return the document ID 9313 details.

```curl -v -H "Content-Type: application/xml" -H "93d2018bc6364c0be371fc87d4fc175b0fd645d3" http://localhost:3000/dmsf/files/9313.xml```

**Comment by lpereira98** [comment]
I get 500 Internal server error:

> Started GET "/redmine/dmsf/files/9313.json?key=93d2018bc6364c0be371fc87d4fc175b0fd645d3" for 127.0.0.1 at 2018-11-20 09:55:41 +0000
Processing by DmsfFilesController#show as JSON
  Parameters: {"key"=>"93d2018bc6364c0be371fc87d4fc175b0fd645d3", "id"=>"9313"}
  Current user: lpereira (id=126)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb (108.3ms)
Completed 500 Internal Server Error in 218ms (ActiveRecord: 0.0ms)

ActionView::Template::Error (undefined method `folder' for #<DmsfFile:0xaae9848>):
    3:   api.name @file.name
    4:   api.container_id @file.container_id
    5:   api.container_type @file.container_type
    6:   api.dmsf_folder_id @file.folder if @file.dmsf_folder_id
    7:   api.version "#{@file.last_revision.major_version}.#{@file.last_revision.minor_version}" if @file.last_revision
    8:   api.content_url url_for(:controller => :dmsf_files, :action => 'show', :download => '', :id => @file)
    9: end
  plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb:6:in `block (2 levels) in _plugins_redmine_dmsf_app_views_dmsf_files_show_api_rsb__699212606_92562984'
  lib/redmine/views/builders/structure.rb:74:in `method_missing'
  plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb:1:in `block in _plugins_redmine_dmsf_app_views_dmsf_files_show_api_rsb__699212606_92562984'
  lib/redmine/views/builders.rb:31:in `for'
  plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb:1:in `_plugins_redmine_dmsf_app_views_dmsf_files_show_api_rsb__699212606_92562984'
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:79:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

I'm using 1.5.9 version.

**Comment by picman** [comment]
Either upgrade to v1.6.0 or do the following fix in _app/view/dmsf_files_show.api.rsb_:
```ruby
api.dmsf_file do
  api.id @file.id
  api.name @file.name
  api.container_id @file.container_id
  api.container_type @file.container_type
--api.dmsf_folder_id @file.folder if @file.dmsf_folder_id
++api.dmsf_folder_id @file.dmsf_folder_id
  api.version "#{@file.last_revision.major_version}.#{@file.last_revision.minor_version}" if @file.last_revision
  api.content_url url_for(:controller => :dmsf_files, :action => 'show', :download => '', :id => @file)
end
```

**Comment by lpereira98** [comment]
I get:
> Started GET "/redmine/dmsf/files/9396.json?key=93d2018bc6364c0be371fc87d4fc175b0fd645d3" for 127.0.0.1 at 2018-11-20 15:49:50 +0000
Processing by DmsfFilesController#show as JSON
  Parameters: {"key"=>"93d2018bc6364c0be371fc87d4fc175b0fd645d3", "id"=>"9396"}
  Current user: lpereira (id=126)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb (0.0ms)
Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms)

SyntaxError`` (D:/redmine-3.4.2-2/apps/redmine/htdocs/plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb:6: syntax error, unexpected tIVAR, expecting keyword_end
  --api.dmsf_folder_id @file.folder if @file.dmsf_folder_id
                            ^
D:/redmine-3.4.2-2/apps/redmine/htdocs/plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb:7: syntax error, unexpected tIVAR, expecting keyword_end
  ++api.dmsf_folder_id @file.dmsf_folder_id
                            ^):
  plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb:6: syntax error, unexpected tIVAR, expecting keyword_end
  plugins/redmine_dmsf/app/views/dmsf_files/show.api.rsb:7: syntax error, unexpected tIVAR, expecting keyword_end
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:79:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Im not sure if i have to install xapian gem, i tried but im using windows so it's much harder because all documentation i saw is for Linux environment, do i need it? do i need something more?
