### ISSUE TITLE
Error 500 while send file

### ISSUE THREAD

**Issue by kojir0** [danmunn/redmine_dmsf#927]
Hello,
I've got an Error while we upload file
```
Started POST "/projects/ecl/dmsf/upload/file" for XX.XX.136.229 at 2018-11-15 18:45:49 +0100
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"schemareseauv6-20181114.txt", "authenticity_token"=>"dmGqkpxTO5pODcI7/vIKNuljXXXGl61Wn8z9AJ+lbpCD4AdKViG1ofxfxSEjLOdWvyAbcA28XXXwyVqyJWCjig==", "file"=>#<ActionDispatch::Http::UploadedFile:0x00000002f90978 @tempfile=#<Tempfile:/tmp/RackMultipart20181115-4436-1kb1nu.txt>, @original_filename="schemareseauv6-20181114.txt", @content_type="text/plain", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"schemareseauv6-20181114.txt\"\r\nContent-Type: text/plain\r\n">, "id"=>"ecl"}
  Current user: hadrien (id=12)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (35.0ms)
Completed 500 Internal Server Error in 112ms (ActiveRecord: 12.0ms)

ActionView::Template::Error (undefined method `html_safe' for nil:NilClass
Did you mean?  html_safe?):
    26:   "original_filename":"<%= @tempfile.original_filename.html_safe %>",
    27:   "content_type":     "<%= @tempfile.content_type.gsub('"', '').html_safe %>",
    28:   "disk_filename":    "<%= @disk_filename.html_safe %>",
    29:   "tempfile_path":    "<%= @tempfile_path.html_safe %>"
    30: }
  plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb:29:in `_plugins_redmine_dmsf_app_views_dmsf_upload_upload_file_html_erb__4121635303201377474_31942920'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:72:in `upload_file'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'
```
I thought it was an ruby/passenger obsolete issue so i upgraded ruby to 2.4.1 and passenger to 5.3.7 but nothing change.

Other plugins on my redmine
```
Clipboard image paste 1.12
DMSF 161
Redmine Extend Permissions plugin 0.0.2
Private Wiki 0.2.2
Zulip 0.91
```

Version of gems :

```
[root@redmine log]# ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
[root@redmine log]# 
[root@redmine redmine]# gem list

*** LOCAL GEMS ***

actioncable (5.2.1)
actionmailer (5.2.1, 4.2.8)
actionpack (5.2.1, 4.2.8)
actionpack-xml_parser (2.0.1, 1.0.2)
actionview (5.2.1, 4.2.8)
activejob (5.2.1, 4.2.8)
activemodel (5.2.1, 4.2.8)
activerecord (5.2.1, 4.2.8)
activestorage (5.2.1)
activesupport (5.2.1, 4.2.8)
addressable (2.5.2)
arel (9.0.0, 6.0.4)
bigdecimal (1.3.5, default: 1.3.0)
builder (3.2.3)
bundler (1.17.1)
bundler-unload (1.0.2)
coderay (1.1.2)
concurrent-ruby (1.1.3, 1.0.5)
crass (1.0.4)
css_parser (1.6.0)
dalli (2.7.9, 2.7.8)
did_you_mean (1.1.0)
erubi (1.7.1)
erubis (2.7.0)
executable-hooks (1.6.0, 1.3.2)
gem-wrappers (1.4.0, 1.3.2)
globalid (0.4.1)
htmlentities (4.3.4)
i18n (1.1.1, 0.7.0)
io-console (default: 0.4.6)
jquery-rails (4.3.3, 3.1.5)
json (2.1.0, default: 2.0.2)
loofah (2.2.3, 2.2.2)
mail (2.7.1, 2.6.6)
marcel (0.3.3)
method_source (0.9.2)
mime-types (3.2.2, 3.1)
mime-types-data (3.2018.0812, 3.2016.0521)
mimemagic (0.3.2)
mini_mime (1.0.1)
mini_portile2 (2.3.0)
minitest (5.11.3, 5.10.1)
mysql2 (0.5.2, 0.4.10)
net-ldap (0.16.1, 0.12.1)
net-telnet (0.2.0, 0.1.1)
nio4r (2.3.1)
nokogiri (1.8.5, 1.8.2)
openssl (2.1.2, default: 2.0.3)
ox (2.10.0, 2.9.2)
passenger (5.3.7)
power_assert (1.1.3, 0.4.1)
protected_attributes (1.1.4)
psych (3.0.3, default: 2.2.2)
public_suffix (3.0.3)
rack (2.0.6, 1.6.11, 1.6.10)
rack-openid (1.4.2)
rack-test (1.1.0, 0.6.3)
rails (5.2.1, 4.2.8)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.3, 1.0.9)
rails-html-sanitizer (1.0.4)
railties (5.2.1, 4.2.8)
rake (12.3.1, 12.0.0)
rbpdf (1.19.6)
rbpdf-font (1.19.1)
rdoc (6.0.4, default: 5.0.0)
redcarpet (3.4.0)
redmine_extensions (0.2.14, 0.2.10)
request_store (1.4.1, 1.0.5)
rmagick (2.16.0)
roadie (3.4.0, 3.2.2)
roadie-rails (1.3.0, 1.1.1)
ruby-openid (2.7.0, 2.3.0)
rubygems-bundler (1.4.5, 1.4.4)
rubyzip (1.2.2, 1.2.1)
rvm (1.11.3.9)
simple_enum (2.3.2, 2.3.1)
sprockets (3.7.2, 3.7.1)
sprockets-rails (3.2.1)
test-unit (3.2.8, 3.2.3)
thor (0.20.3, 0.20.0)
thread_safe (0.3.6)
tzinfo (1.2.5)
uuidtools (2.1.5)
websocket-driver (0.7.0)
websocket-extensions (0.1.3)
xmlrpc (0.3.0, 0.2.1)
zip-zip (0.3)
```
Have you got any idea to help me resolve this issue.

**Comment by picman** [comment]
Is it a fresh installation? Had you been able to upload documents before? Is it the target folder in the file system for documents writable for the web application? Check the plugin's settings too.

**Comment by kojir0** [comment]
It's not a fresh installation, but an upgrade.
The problem is i don't exactly when the error come up ...

Righ of file seems ok
```
[root@redmine files]# pwd 
/opt/redmine/files
[root@redmine files]# ls -als 
total 272
  4 drwxr-xr-x  8 apache apache   4096  4 mai    2018 .
  4 drwxrwxr-x 19 apache apache   4096  4 mai    2018 ..
  4 -rwxr-xr-x  1 apache apache   3247  4 mai    2018 121015122239_ab9ad2a49ea77d75964abead7a4327c9.mm
164 -rwxr-xr-x  1 apache apache 166280  4 mai    2018 121018140023_0e4cea7d6117e84b7107c5786cbb10f4.xlsx
 20 -rwxr-xr-x  1 apache apache  17575  4 mai    2018 121018140023_233712edba14c99aa464c99c56100f4d.docx
  4 -rwxr-xr-x  1 apache apache    325  4 mai    2018 130507110205_noname
 60 -rwxr-xr-x  1 apache apache  59510  4 mai    2018 130611195806_xxxxxx.pdf
 12 -rwxr-xr-x  1 apache apache   9855  4 mai    2018 140213085028_d9e6523ff819c297b37efc1d2ebbdd22.pdf
  0 drwxr-xr-x 12 apache apache    106  4 mai    2018 2014
  0 drwxr-xr-x 14 apache apache    126  4 mai    2018 2015
  0 drwxr-xr-x 14 apache apache    126  4 mai    2018 2016
  0 drwxr-xr-x 14 apache apache    126  4 mai    2018 2017
  0 drwxr-xr-x 13 apache apache    116  5 nov.  17:36 2018
  0 drwxr-xr-x  8 apache apache     88 16 nov.  10:35 dmsf
[root@redmine files]# ls -als dmsf/
total 4
0 drwxr-xr-x  8 apache apache   88 16 nov.  10:35 .
4 drwxr-xr-x  8 apache apache 4096  4 mai    2018 ..
0 drwxr-xr-x  3 apache apache   16  5 mai    2018 2014
0 drwxr-xr-x 13 apache apache  116  5 mai    2018 2015
0 drwxr-xr-x  8 apache apache   66  5 mai    2018 2016
0 drwxr-xr-x  6 apache apache   46  5 mai    2018 2017
0 drwxr-xr-x  3 apache apache   16  4 mai    2018 2018
0 drwxr-xr-x  2 apache apache    6  5 mai    2018 p_air-XXXXXX
[root@redmine files]# 
```
And configuration of DMSF is by default :
```
| 91 | plugin_redmine_dmsf                       | ---
dmsf_max_file_upload: '0'
dmsf_max_file_download: '0'
dmsf_max_email_filesize: '0'
dmsf_max_ajax_upload_filesize: '100'
dmsf_storage_directory: files/dmsf
dmsf_tmpdir: "/tmp"
dmsf_default_notifications: ''
dmsf_display_notified_recipients: ''
dmsf_global_title_format: ''
dmsf_columns:
- title
- size
- modified
- version
- workflow
- author
dmsf_documents_email_from: ''
dmsf_documents_email_reply_to: ''
dmsf_webdav: '1'
dmsf_webdav_strategy: WEBDAV_READ_ONLY
dmsf_webdav_ignore: "^(\\._|\\.DS_Store$|Thumbs.db$)"
dmsf_webdav_disable_versioning: "^\\~\\$|\\.tmp$"
dmsf_stemming_lang: french
```
If i remove the plugins and try to reinstall, how can i keep the files already uploaded through DMSF ?

**Comment by picman** [comment]
Just backup files/dmsf folder.

**Comment by kojir0** [comment]
ok the reinstallation work.
Now how can i reinject all the file, i move my backup file/dmsf but file are not present in redmine.
Is there a command to scan the folder to add file again ?

**Comment by picman** [comment]
The files are stored in the file system on the path given in the plugin's settings (dmsf/files). Links to these files are stored in the database redmine.dmsf_file_revisions table.
If files are not visible in the user's interface, it might be related to insufficient permissions too. Check Roles & Permissions. And check the database too, whether redmine.dmsf_* tables contain data.

**Comment by kojir0** [comment]
ok i reinjected mysql table with a backup and all is working again.
Thank you very much for your help.
I close the ticket.
