### ISSUE TITLE
Plz. help me. I got a error message

### ISSUE THREAD

**Issue by lee0314** [danmunn/redmine_dmsf#930]
Hello.

I installed redmine on docker in my synology nas.

Next is my app versions.
Environment:
  Redmine version                3.3.6.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
 redmine_dmsf                   1.6.2

redmine_dmsf plugin was well installing.

But I can't going to dmsf menu in project.

when  I clicked dmsf menu then it printed internal 500 error.

It is detail error message.
plz help me~

Thank you~

Best regards, LEE

------------------------------------------
Completed 500 Internal Server Error in 140ms (ActiveRecord: 45.9ms)

ActionView::Template::Error (wrong number of arguments (given 0, expected 1)):
    122:     <% end %>
    123: <% end %>
    124:
    125: <%= context_menu %>
    126:
    127: <% content_for :header_tags do %>
    128:     <%= stylesheet_link_tag 'jquery.dataTables/datatables.min.css', :plugin => :redmine_dmsf %>
  app/helpers/application_helper.rb:1158:in `context_menu'
  plugins/redmine_dmsf/app/views/dmsf/show.html.erb:125:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb___4556458878495392950_43960840'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:63:in `block (2 levels) in show'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:61:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

**Comment by picman** [comment]
I wonder how you were able to install DMSF plugin v.1.6.2 on Redmine 3.3.6. Redmine >= 3.4.0 is required.
