### ISSUE TITLE
undefined method `to_prepare' for ActionDispatch::Reloader:Class (Redmine 4.0 / Rails 5)

### ISSUE THREAD

**Issue by pskillen** [danmunn/redmine_dmsf#932]
Unable to run DB migrations after upgrading to Redmine 4.0.0, which uses Rails 5.2

This seems to be related to a deprecated method in Rails 5.x (and seems very similar to https://github.com/activeadmin/activeadmin/issues/4438). 

Command: `bundle exec rake redmine:plugins:migrate RAILS_ENV="production"`
Error source: https://github.com/danmunn/redmine_dmsf/blob/master/after_init.rb#L103

Error message:
```
root@ff99aebfb531:/usr/src/redmine#  bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Reloader:Class
Did you mean?  to_param
/usr/src/redmine/plugins/redmine_dmsf/after_init.rb:103:in `<top (required)>'
/usr/src/redmine/plugins/redmine_dmsf/init.rb:70:in `require_relative'
/usr/src/redmine/plugins/redmine_dmsf/init.rb:70:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'

...
```

**Comment by picman** [comment]
v1.6.2 is not compatible with Redmine 4.0. Either try devel-2.0.0 branch or wait for a next release.

**Comment by pskillen** [comment]
Sorry, I should have checked the devel branch before submitting a bug. For what it's worth, I can confirm this specific bug doesn't occur as of dc0eb77

**Comment by joshylad** [comment]
We are having still having this same issue in 
Redmine Version 4.0.3
DMSF Version 2.0.1 (Development branch)
Rails Version 5.2.3
Ruby Version 2.6.1

```
ematics@redmine:~/redmine$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/home/ematics/redmine/plugins/clipboard_image_paste/init.rb:32:in `<top (required)>'
/home/ematics/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/ematics/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/ematics/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/ematics/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/ematics/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'

```

**Comment by picman** [comment]
https://github.com/ruby-grape/grape/issues/1666#issuecomment-318083431
